import { CaseStudy } from "../../types/case-study";

// ─── Embedded Systems ────────────────────────────────────────────────────────
export const embeddedCaseStudiesData: CaseStudy[] = [
  {
    serialNumber: 1,
    id: "industrial-temperature-control-system",
    title: "Industrial Temperature Control System",
    category: "Embedded System Design",
    cardImageIndex: 2,
    images: [
      "/case-studies/BLUECOLD/BLUE_COLD_REV-01_BRD_03_TOP.svg",
      "/case-studies/BLUECOLD/BLUE_COLD_REV-01_BRD_03_TP.svg",
      "/case-studies/BLUECOLD/1.png",
      "/case-studies/BLUECOLD/2.png",
      "/case-studies/BLUECOLD/5.png",
    ],
    features: [
      "Hardware / Firmware Design and Development",
      "Precision Temperature Sensing and Control",
      "SAMA5D3 Processor / STM32 MCU",
      "POE+ / Ethernet Connectivity",
      "Industrial-grade Enclosure Design",
      "Multi-zone Temperature Management",
    ],
    summary:
      "An industrial-grade temperature control system designed for environments requiring precise thermal regulation. Built around the SAMA5D3 processor, the system supports multi-zone temperature monitoring with high-accuracy sensors and closed-loop PID control. POE+ connectivity enables single-cable deployment for both power and data, simplifying installation in cold-chain, laboratory, and manufacturing settings.",
    importantParts: [
      "Microchip SAMA5D3 Application Processor",
      "ST Micro High Performance MCU",
      "High-accuracy NTC / RTD Temperature Sensors",
      "Linear Technologies POE+ Controller",
    ],
    salientFeatures: [
      "Precision multi-zone temperature control.",
      "POE+ powered for simplified single-cable installation.",
      "Closed-loop PID regulation with configurable setpoints.",
      "Real-time data logging and remote monitoring.",
      "Industrial operating temperature range (-40 °C to +85 °C).",
      "Configurable alarm thresholds and relay outputs.",
      "Nano Flash storage for local data retention.",
      "Remote firmware upgrade capability.",
      "5 % improvement in thermal stability over prior generation.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Board Bring-up and Testing",
      "Enclosure Design",
    ],
  },
  {
    serialNumber: 2,
    id: "multi-io-card-for-ate",
    title: "Multi IO card for ATE",
    category: "Test & Measurement",
    cardImageIndex: 3,
    images: [
      "/case-studies/CHARA/CHARA-T_B.svg",
      "/case-studies/CHARA/CHARA-TB.svg",
      "/case-studies/CHARA/CHARA-top.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/CHARA/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/CHARA/2.1.PNG",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/CHARA/3.1.PNG",
    ],
    features: [
      "FPGA Spartan-6 Based Multi-channel IO",
      "High-speed ADC / DAC Sampling",
      "Fiber Optic Interface",
      "Hardware / Firmware Design and Development",
      "PCB Design and Layout",
      "ATE System Integration",
    ],
    summary:
      "A versatile Multi IO card designed for Automated Test Equipment (ATE) platforms, built around a Xilinx Spartan-6 FPGA. The card provides multiple high-speed analog and digital IO channels with fiber optic connectivity for noise-immune data transfer. With 12x faster sampling rates than conventional solutions, it enables precise stimulus generation and measurement capture across a wide range of device-under-test scenarios.",
    importantParts: [
      "Xilinx Spartan-6 FPGA",
      "Analog Devices High-speed ADCs",
      "Texas Instruments DAC and Power Management",
      "Fiber Optic Transceiver Module",
    ],
    salientFeatures: [
      "FPGA-based parallel IO processing.",
      "High-speed ADC sampling for precision measurement.",
      "Fiber optic interface for noise-immune communication.",
      "Multi-channel analog and digital IO.",
      "Configurable test patterns and stimulus generation.",
      "Real-time data acquisition and streaming.",
      "Modular design for integration with ATE racks.",
      "12x faster sampling rate than conventional cards.",
      "Low-latency deterministic IO response.",
    ],
    scopeOfWork: [
      "System Architecture Design",
      "FPGA Development and Programming",
      "Analog Circuit Design",
      "PCB Layout and Design",
      "Firmware Development",
      "Testing and Validation",
      "ATE Integration Support",
    ],
  },
  {
    serialNumber: 3,
    id: "smart-monitoring-system",
    title: "Smart Monitoring System",
    category: "Industrial Control Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/climate_control/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/climate_control/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/climate_control/3.png",
    ],
    paddedImages: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    features: [
      "ARM Cortex-M7 Processor",
      "FreeRTOS Real-Time Operating System",
      "Multi-sensor Environmental Monitoring",
      "L2 Managed Ethernet Switch",
      "Industrial Grade Components",
      "Remote Dashboard and Alerts",
    ],
    summary:
      "A smart environmental monitoring system powered by an ARM Cortex-M7 processor running FreeRTOS. The system continuously tracks temperature, humidity, air quality, and other environmental parameters across multiple zones. An integrated L2 managed switch enables daisy-chained sensor nodes over a single Ethernet backbone, achieving 40 % better power efficiency through intelligent duty-cycling and POE-powered deployment.",
    importantParts: [
      "ARM Cortex-M7 Processor",
      "L2 Managed Ethernet Switch IC",
      "Industrial Ethernet PHY",
      "Precision Environmental Sensors (Temp, Humidity, CO₂)",
    ],
    salientFeatures: [
      "Real-time multi-zone environmental monitoring.",
      "FreeRTOS for deterministic sensor polling.",
      "L2 managed switch for daisy-chained sensor nodes.",
      "40 % power efficiency through intelligent duty-cycling.",
      "Web-based dashboard for remote monitoring.",
      "Configurable alert thresholds via SNMP.",
      "Industrial operating temperature range.",
      "DIN rail or wall-mount installation.",
      "LED status indicators for each channel.",
    ],
    scopeOfWork: [
      "System Requirements Analysis",
      "Hardware Architecture Design",
      "RTOS Implementation",
      "Sensor Integration and Calibration",
      "Network Stack Development",
      "EMC/EMI Compliance Testing",
      "Industrial Certification",
    ],
  },
  {
    serialNumber: 4,
    id: "microscopic-camera-control",
    title: "Microscopic Camera Control",
    category: "Imaging & Optics",
    cardImageIndex: 2,
    images: [
      "/case-studies/MICROSCOPIC CAMERA/4.png",
      "/case-studies/MICROSCOPIC CAMERA/5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/microscopic_camera/1.png",
      "/case-studies/MICROSCOPIC CAMERA/2.png",
      "/case-studies/MICROSCOPIC CAMERA/3.png",
    ],
    features: [
      "High-resolution CMOS Image Sensor",
      "Precision Motor Control for Focus and Zoom",
      "OLED Status Display",
      "Hardware / Firmware Design and Development",
      "USB and Ethernet Streaming Interface",
      "Compact Enclosure Design",
    ],
    summary:
      "A microscopic camera control system designed for laboratory and inspection applications. The system drives precision stepper motors for automated focus and zoom adjustment while streaming high-resolution imagery over USB or Ethernet. An on-board OLED display provides real-time status, magnification level, and capture settings. The compact form factor integrates seamlessly with standard microscope mounts.",
    importantParts: [
      "High-resolution CMOS Image Sensor",
      "Microchip PIC Microcontroller",
      "Precision Stepper Motor Drivers",
      "OLED Display Module (96 × 64)",
      "USB 3.0 High-speed Interface IC",
      "Low-noise LDO Voltage Regulators",
    ],
    salientFeatures: [
      "Automated focus and zoom via precision motor control.",
      "High-resolution image capture and live streaming.",
      "OLED display for real-time status and settings.",
      "USB 3.0 and Ethernet output interfaces.",
      "Compatible with standard microscope mounts.",
      "Low-noise power design for image clarity.",
    ],
    scopeOfWork: [
      "Hardware Design",
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Board Bring-up and Testing",
      "Enclosure Design",
    ],
  },
  {
    serialNumber: 5,
    id: "industrial-iot-gateway-with-poe",
    title: "Industrial IOT gateway with POE",
    category: "Industrial IoT",
    cardImageIndex: 3,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/tekion_ott/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/tekion_ott/TEK_OTT_REV1P0_BRD_PR3.bot.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/tekion_ott/TEK_OTT_REV1P0_BRD_PR3.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/tekion_ott/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/tekion_ott/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/tekion_ott/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/tekion_ott/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/tekion_ott/OTT_RENDER_27_NOV_2024_MG2.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/tekion_ott/OTT_RENDER_27_NOV_2024_MG4.4.png",
    ],
    features: [
      "Complete Product Development",
      "HW / FW / Linux System Integration",
      "POE+ Powered with Ethernet Backhaul",
      "Multi-protocol IoT Gateway (LoRa, BLE, CAN)",
      "Mechanical / Enclosure Design",
      "Contract Manufacturing",
    ],
    summary:
      "An industrial IoT gateway with integrated POE+ that bridges field sensors and actuators to cloud platforms. The device aggregates data from LoRa, BLE, and CAN bus endpoints, processes it locally on an STM32F MCU, and forwards it over Ethernet. POE+ provides single-cable power and data, eliminating the need for local AC supplies in factory and warehouse deployments. With 15 km LoRa range and 99.9 % uplink accuracy, it serves as a reliable backbone for large-scale industrial monitoring.",
    importantParts: [
      "ST Microelectronics STM32F ARM Cortex MCU",
      "MultiTech LoRa Module",
      "Raytac BLE 5.0 Module",
      "POE+ PD Controller",
      "Industrial Ethernet PHY",
      "Atmel EEPROM",
    ],
    salientFeatures: [
      "POE+ powered — single-cable deployment.",
      "Multi-radio gateway: LoRa, BLE 5.0, CAN bus.",
      "15 km LoRa range for wide-area sensor coverage.",
      "99.9 % data uplink accuracy.",
      "Local edge processing and data buffering.",
      "Industrial-grade ESD / EMI / surge protection.",
      "Remote firmware upgrade via Ethernet.",
      "DIN rail and wall-mount options.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Board Bring-up and Testing",
      "Enclosure Design",
      "FCC / CE Certification",
      "Low Volume Production",
    ],
  },
  {
    serialNumber: 6,
    id: "poe-control-unit",
    title: "POE Control unit",
    category: "Power over Ethernet",
    cardImageIndex: 3,
    images: [
      "/case-studies/POE/1.1.svg",
      "/case-studies/POE/1.2.svg",
      "/case-studies/POE/1.3.svg",
      "/case-studies/POE/1.png",
      "/case-studies/POE/2.png",
    ],
    features: [
      "IEEE 802.3af/at POE+ Compliant",
      "Multi-port Managed Power Delivery",
      "Temperature and Accelerometer Sensors",
      "Hardware / Firmware Development",
      "Up to 100 m Reach per Port",
      "Compact Enclosure Design",
    ],
    summary:
      "A compact POE control unit that manages power delivery and monitoring across multiple Ethernet-connected devices. The unit is IEEE 802.3af/at compliant and provides per-port power budgeting, fault detection, and remote enable/disable control. On-board temperature and motion sensors trigger automatic safety shutdowns, while the Qi wireless charging interface allows contact-less maintenance of paired accessories. Designed for access control, IP camera, and building automation deployments.",
    importantParts: [
      "POE+ PSE Controller IC",
      "Managed Ethernet Switch IC",
      "ST Micro Temperature and Accelerometer Sensors",
      "Qi Wireless Charging Receiver",
      "Texas Instruments Power Management ICs",
      "ST Micro LDO Voltage Regulators",
    ],
    salientFeatures: [
      "IEEE 802.3af/at POE+ compliant.",
      "Per-port power budgeting and fault isolation.",
      "Up to 100 m reach per port.",
      "On-board temperature and motion sensing.",
      "Remote port enable/disable via web interface.",
      "Qi wireless charging for paired accessories.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Enclosure Design",
      "Board Bring-up and Testing",
    ],
  },
  {
    serialNumber: 7,
    id: "poe-power-injector",
    title: "POE Power Injector",
    category: "Power over Ethernet",
    cardImageIndex: 2,
    images: [
      "/case-studies/POE/2.1.svg",
      "/case-studies/POE/2.2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/poe_power_injector/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/poe_power_injector/4.png",
    ],
    features: [
      "IEEE 802.3af/at/bt POE Injection",
      "Multi-port Mid-span Design",
      "TCP/IP and MQTT Management Protocols",
      "Dual-band 2.4 GHz Monitoring Radio",
      "Hardware / PCB Design",
      "48 GPIO Expansion Pins",
    ],
    summary:
      "A multi-port POE power injector (mid-span) that adds POE capability to existing non-POE Ethernet switches. The unit injects power into up to 48 Ethernet ports simultaneously while maintaining full data pass-through at Gigabit speeds. An on-board management interface accessible via TCP/IP and MQTT enables per-port power monitoring, scheduling, and remote reboot. Three simultaneous operating modes allow mixed 802.3af, 802.3at, and 802.3bt devices on the same chassis.",
    importantParts: [
      "Multi-port POE PSE Controller",
      "High-efficiency Isolated DC-DC Converters",
      "Gigabit Ethernet Magnetics",
      "Macronix 16 Mb NOR Flash Memory",
    ],
    salientFeatures: [
      "Supports 802.3af / at / bt standards.",
      "Up to 48 injected ports per unit.",
      "TCP/IP and MQTT management protocols.",
      "Three simultaneous POE modes.",
      "Per-port power metering and scheduling.",
      "Gigabit pass-through with zero data degradation.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Power Integrity Testing",
      "Board Bring-up and Testing",
    ],
  },
  {
    serialNumber: 8,
    id: "industrial-poe-switch",
    title: "Industrial POE switch",
    category: "Power over Ethernet",
    cardImageIndex: 2,
    images: [
      "/case-studies/POE/3.1.svg",
      "/case-studies/POE/3.2.svg",
      "/case-studies/POE/5.png",
      "/case-studies/POE/6.png",
    ],
    features: [
      "Managed L2 Industrial Ethernet Switch",
      "8 / 16 / 24 Port POE+ Output",
      "WPA3 / TLS Secure Management",
      "Zero-config Plug-and-play Deployment",
      "Hardened Enclosure for Industrial Environments",
      "USB-C 5 V Console Port",
    ],
    summary:
      "A ruggedised industrial POE switch providing managed L2 switching with POE+ power delivery across 8 to 24 Gigabit ports. The zero-config deployment mode enables 90 % faster setup compared to traditional managed switches, while WPA3 and TLS-secured management protect against unauthorised access. The fanless design with an extended operating temperature range makes it suitable for factory floors, outdoor cabinets, and harsh industrial environments.",
    importantParts: [
      "Managed L2 Ethernet Switch Controller",
      "POE+ PSE Controllers (per-port)",
      "Industrial-grade Ethernet Magnetics",
      "Macronix NOR Flash Memory",
      "CUI Industrial Power Supply Module",
    ],
    salientFeatures: [
      "Managed L2 switching with POE+ on every port.",
      "Zero-config mode for 90 % faster deployment.",
      "WPA3 / TLS secured management interface.",
      "Fanless design for harsh environments.",
      "Extended operating temperature (-40 °C to +75 °C).",
      "USB-C 5 V console port for local configuration.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Power Integrity Testing",
      "Enclosure Design",
      "Board Bring-up and Testing",
    ],
  },
  {
    serialNumber: 9,
    id: "stellar-main-board",
    title: "Stellar Main Board",
    category: "Embedded System Design",
    cardImageIndex: 2,
    images: [
      "/case-studies/STELLAR MAIN BORD/MAIN BOARD 1.svg",
      "/case-studies/STELLAR MAIN BORD/MAIN BOARD 2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_main_board/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_main_board/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_main_board/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_main_board/4.png",
    ],
    features: [
      "High-density Multi-layer Main Board",
      "SFP+ Network Ports (Grandmaster / Backhaul / Auxiliary)",
      "GPS / RTC Precision Timing",
      "LOM (Lights Out Management) Module",
      "Hardware / Firmware Design and Development",
      "USB-C and Power Board Interface",
    ],
    summary:
      "A high-density embedded main board designed for network timing and synchronisation applications. Built around the FEDERON 2600 platform, the board integrates multiple SFP+ network interfaces for Grandmaster, Backhaul, and Auxiliary channels alongside a GPS/RTC subsystem for precision time-keeping. A dedicated LOM (Lights Out Management) module enables remote board management, while the power board connector supports modular power delivery. The dense multi-layer design accommodates high-speed signal routing across hundreds of components in a compact footprint.",
    importantParts: [
      "High-performance Application Processor",
      "SFP+ Transceiver Modules (Grandmaster, Backhaul, Auxiliary)",
      "GPS Receiver and RTC Module",
      "LOM (Lights Out Management) Controller",
      "USB-C Interface Controller",
      "Multi-rail Power Management ICs",
    ],
    salientFeatures: [
      "Multi-channel SFP+ network interfaces.",
      "GPS / RTC for precision timing and synchronisation.",
      "LOM module for remote management and monitoring.",
      "High-density multi-layer PCB design.",
      "Modular power board interconnect.",
      "USB-C interface for configuration and diagnostics.",
      "Compact footprint with high component density.",
    ],
    scopeOfWork: [
      "System Architecture Design",
      "Schematics Entry",
      "PCB Layout Design (Multi-layer)",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Board Bring-up and Testing",
      "Signal Integrity Analysis",
    ],
  },
  {
    serialNumber: 10,
    id: "stellar-power-board",
    title: "Portable EV Charger",
    category: "Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_power_board/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_power_board/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_power_board/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_power_board/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_power_board/5.png",
    ],
    features: [
      "High-efficiency power management board",
      "Multi-rail power distribution design",
      "Thermal-optimized layout",
      "Stable voltage regulation",
      "Protection and filtering circuits",
      "Compact embedded integration",
    ],
    summary:
      "A dedicated embedded power board engineered for efficient power distribution, thermal performance, and reliable operation across complex embedded systems.",
    importantParts: [
      "DC-DC converters",
      "Voltage regulators",
      "Power filtering components",
      "Thermal dissipation structures",
      "Protection circuits",
      "Power distribution network",
    ],
    salientFeatures: [
      "Efficient multi-rail power delivery",
      "Thermally optimized PCB design",
      "Stable and reliable voltage regulation",
      "Robust protection mechanisms",
    ],
    scopeOfWork: [
      "Power Electronics Design",
      "PCB Layout Development",
      "Thermal Analysis",
      "Power Integrity Validation",
      "Prototype Testing",
    ],
  },
  {
    serialNumber: 11,
    id: "high-speed-camera-interface",
    title: "High Speed Camera Interface",
    category: "Embedded System Design",
    cardImageIndex: 6,
    images: [
      "/case-studies/embedded/HIPPACK1/2.1.svg",
      "/case-studies/embedded/HIPPACK1/2.2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/5.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/5.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/6.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/7.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/8.jpg",
    ],
    rotatedImages: { 3: 180, 7: 180 },
    features: [
      "Real-time processing capabilities",
      "Multiple communication protocols",
      "Modular I/O expansion",
      "Manufacturing and process control",
      "Cortex-A9 Processor",
      "Modbus / EtherCAT Support",
    ],
    summary:
      "Advanced industrial automation controller with real-time processing capabilities, supporting multiple communication protocols and modular I/O expansion. Designed for manufacturing and process control applications with 99.9% system uptime.",
    importantParts: [
      "ARM Cortex-A9 Processor",
      "Real-time Kernel",
      "Industrial Ethernet Interface",
      "Modular I/O Cards",
      "Power Management Module",
      "Industrial Housing",
    ],
    salientFeatures: [
      "Real-time processing with deterministic response.",
      "Support for Modbus and EtherCAT protocols.",
      "Modular I/O expansion capability.",
      "Industrial temperature and vibration rated.",
      "99.9% system uptime in field deployments.",
      "Remote monitoring and diagnostics.",
    ],
    scopeOfWork: [
      "System Architecture Design",
      "Hardware Development",
      "Real-time Firmware Development",
      "Protocol Implementation",
      "Testing and Validation",
      "Industrial Certification",
    ],
  },
  {
    serialNumber: 12,
    id: "industrial-automation-controller",
    title: "Industrial Automation Controller",
    category: "Embedded System Design",
    cardImageIndex: 4,
    images: [
      "/case-studies/embedded/HIPPACK2/1.1.svg",
      "/case-studies/embedded/HIPPACK2/1.2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK2/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK2/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK2/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK2/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK2/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK2/4.png",
    ],
    rotatedImages: { 0: 90, 1: 90 },
    enlargedImages: { 0: 1.3, 1: 1.3 },
    features: [
      "Multi-protocol wireless aggregation",
      "Advanced mesh networking",
      "Cloud connectivity",
      "Automatic routing",
      "512 MB RAM",
      "256 device capacity",
    ],
    summary:
      "Multi-protocol wireless hub aggregating sensor data from distributed IoT devices. Features advanced mesh networking with automatic routing and cloud connectivity for analytics.",
    importantParts: [
      "Multi-radio Transceiver Module",
      "Mesh Networking Processor",
      "512 MB RAM and Storage",
      "Cloud Interface Controller",
      "Power Management",
      "Industrial Enclosure",
    ],
    salientFeatures: [
      "Support for BLE, Wi-Fi, and ZigBee simultaneously.",
      "Advanced mesh networking with automatic routing.",
      "Cloud connectivity for remote analytics.",
      "Up to 256 connected devices.",
      "500m range in open space.",
      "Low-power operation for extended deployment.",
    ],
    scopeOfWork: [
      "System Architecture",
      "Wireless Protocol Integration",
      "Mesh Networking Implementation",
      "Cloud API Development",
      "Hardware Design",
      "Testing and Validation",
    ],
  },
  {
    serialNumber: 13,
    id: "bms-controller",
    title: "BMS Controller",

    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/battery_pack/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/battery_pack/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/battery_management_system/1.3.png",
    ],
    features: [
      "High-speed data logging",
      "Onboard storage",
      "Real-time analytics",
      "Configurable sampling rates",
      "100 kHz sampling",
      "32 parallel channels",
    ],
    summary:
      "High-speed data logging device for industrial monitoring with onboard storage and real-time analytics. Supports multiple analog and digital input channels with configurable sampling rates.",
    importantParts: [
      "High-speed ADC Array",
      "Real-time Processing Processor",
      "1 TB eMMC Storage",
      "Signal Conditioning Circuits",
      "Power Management",
      "Industrial Housing",
    ],
    salientFeatures: [
      "100 kHz maximum sampling rate.",
      "32 analog input channels.",
      "1 TB onboard eMMC storage.",
      "Real-time data processing.",
      "Configurable recording parameters.",
      "Timestamp synchronization for multi-channel data.",
    ],
    scopeOfWork: [
      "High-speed ADC Design",
      "Firmware Development",
      "Storage Interface Design",
      "Real-time Processing",
      "Testing and Validation",
      "System Integration",
    ],
  },
  {
    serialNumber: 14,
    id: "ultra-low-power-bluetooth-mouse",
    title: "Ultra Low Power Bluetooth Mouse",
    category: "Embedded System Design",
    cardImageIndex: 2,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluetooth_mouse/1.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluetooth_mouse/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluetooth_mouse/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluetooth_mouse/1.3.png",
    ],
    features: [
      "Integrated environmental sensors",
      "Solar charging capability",
      "Extended battery life",
      "LoRaWAN connectivity",
      "6-point environmental sensing",
      "2-year battery autonomy",
    ],
    summary:
      "Compact environmental monitoring system with integrated sensors for temperature, humidity, air quality, and atmospheric pressure. Features solar charging and extended battery life.",
    importantParts: [
      "Multi-sensor Array",
      "Solar Charging Controller",
      "Long-life Battery Pack",
      "LoRaWAN Module",
      "Wireless Power Module",
      "Weatherproof Enclosure",
    ],
    salientFeatures: [
      "6-point environmental sensing (Temp, Humidity, AQ, Pressure, etc).",
      "Solar panel with maximum power point tracking.",
      "2-year battery autonomy on solar charging.",
      "LoRaWAN connectivity for long-range deployment.",
      "Low-power sleep modes for extended operation.",
      "IP67 weatherproof rating.",
    ],
    scopeOfWork: [
      "Sensor Integration",
      "Solar Charging Design",
      "Power Management",
      "LoRaWAN Integration",
      "Enclosure Design",
      "Field Testing and Validation",
    ],
  },
  {
    serialNumber: 15,
    id: "connected-car-demonstration-unit",
    title: "Connected Car Demonstration Unit",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/connected_car_demonstration_unit/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/connected_car_demonstration_unit/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/connected_car_demonstration_unit/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/connected_car_demonstration_unit/1.4.png",
    ],
    features: [
      "Building management system controller",
      "HVAC and lighting coordination",
      "Security system integration",
      "Energy optimization",
      "Occupancy-based automation",
      "128-zone capability",
    ],
    summary:
      "Intelligent building management system controller coordinating HVAC, lighting, and security systems. Provides energy optimization and occupancy-based automation.",
    importantParts: [
      "Dual-core ARM Processor",
      "Zone Control Modules",
      "Building Protocol Interface",
      "Occupancy Sensors",
      "Power Management",
      "Industrial Networking",
    ],
    salientFeatures: [
      "Support for up to 128 building zones.",
      "BACnet and KNX protocol support.",
      "Dual-core ARM processing for real-time control.",
      "Occupancy-based heating, cooling, and lighting.",
      "40% energy consumption reduction.",
      "Remote monitoring and diagnostics.",
    ],
    scopeOfWork: [
      "Building Protocol Integration",
      "Control Algorithm Development",
      "Hardware Design",
      "System Integration",
      "Field Testing",
      "Commissioning Support",
    ],
  },
  {
    serialNumber: 16,
    id: "medical-device-interface",
    title: "Medical Device Interface",
    category: "Embedded System Design",
    cardImageIndex: 1,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/embedded_1/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/pcb_a/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/pcb_a/1.2.png",
    ],
    features: [
      "FDA-compliant interface module",
      "Legacy medical equipment connectivity",
      "Modern networked healthcare systems",
      "Rigorous data validation",
      "Secure communication",
      "99.99% SLA uptime",
    ],
    summary:
      "FDA-compliant interface module for connecting legacy medical equipment to modern networked healthcare systems. Includes rigorous data validation and secure communication.",
    importantParts: [
      "Medical-grade Processor",
      "HL7 / DICOM Protocol Stack",
      "Secure Communication Module",
      "Data Validation Engine",
      "Battery Backup",
      "Medical-certified Housing",
    ],
    salientFeatures: [
      "FDA Class II medical device certification.",
      "HL7 and DICOM protocol support.",
      "Zero data loss incidents in field deployment.",
      "99.99% SLA uptime guarantee.",
      "Encrypted data transmission.",
      "Comprehensive audit logging.",
    ],
    scopeOfWork: [
      "FDA Compliance Planning",
      "Protocol Implementation",
      "Security Hardening",
      "Data Validation Design",
      "Testing and Validation",
      "Regulatory Submission Support",
    ],
  },
  {
    serialNumber: 17,
    id: "industrial-defect-monitoring-system",
    title: "Industrial Defect Monitoring System",
    category: "Embedded System Design",
    cardImageIndex: 4,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/femtofarad_level_capacitance/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/embedded_2/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/embedded_2/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/embedded_2/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/embedded_2/1.4.png",
    ],
    enlargedImages: { 0: 1.5 },
    features: [
      "High-precision motion control",
      "Real-time servo control",
      "Trajectory planning",
      "Multiple kinematic configurations",
      "16-axis capability",
      "±0.1mm accuracy",
    ],
    summary:
      "High-precision motion controller for industrial robotic arms with real-time servo control and trajectory planning. Supports multiple kinematic configurations.",
    importantParts: [
      "Real-time Control Processor",
      "Multi-axis Servo Drivers",
      "Motion Planning Engine",
      "Encoder Interface",
      "Industrial Networking",
      "Emergency Stop Interface",
    ],
    salientFeatures: [
      "Support for up to 16 simultaneous axes.",
      "4 kHz control loop refresh rate.",
      "±0.1mm trajectory accuracy.",
      "Multiple kinematic configuration support.",
      "Real-time trajectory planning.",
      "Safety-certified emergency stop circuits.",
    ],
    scopeOfWork: [
      "Motion Control Algorithm Development",
      "Servo Driver Integration",
      "Trajectory Planning Implementation",
      "Hardware Design",
      "Testing and Validation",
      "Safety Certification",
    ],
  },
  {
    serialNumber: 18,
    id: "gigabit-ethernet-switch-module",
    title: "Gigabit Ethernet Switch Module",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_data_acquisation/1.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_data_acquisation/1.5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_data_acquisation/1.6.png",
    ],
    features: [
      "Three-phase power monitoring",
      "Comprehensive metering",
      "Harmonics analysis",
      "Fault detection",
      "Predictive maintenance",
      "25 measurable parameters",
    ],
    summary:
      "Three-phase power distribution monitoring device with comprehensive metering, harmonics analysis, and fault detection. Enables predictive maintenance of electrical infrastructure.",
    importantParts: [
      "3-phase Measurement ICs",
      "Harmonics Analyzer",
      "Data Logging Memory",
      "Ethernet Interface",
      "Power Supply",
      "Industrial Housing",
    ],
    salientFeatures: [
      "3-phase 480V monitoring capability.",
      "Class 0.5 measurement accuracy.",
      "63rd order harmonics analysis.",
      "25 measurable electrical parameters.",
      "Predictive fault detection algorithms.",
      "Cloud connectivity for remote monitoring.",
    ],
    scopeOfWork: [
      "3-phase Measurement Design",
      "Harmonics Analysis Implementation",
      "Fault Detection Algorithms",
      "Data Logging and Storage",
      "Ethernet Integration",
      "Testing and Validation",
    ],
  },

  {
    serialNumber: 19,
    id: "robotics-motion-controller",
    title: "Robotics Motion Controller",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/mixed_signal/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/mixed_signal/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/mixed_signal/1.3.png",
    ],
    features: [
      "Analog and digital integration",
      "Signal conditioning",
      "Precision data conversion",
      "Noise isolation",
      "High-speed signal processing",
      "System-level optimization",
    ],
    summary:
      "High-performance mixed signal system combining precision analog front-end design with digital processing for accurate sensing, control, and real-time embedded applications.",
    importantParts: [
      "Analog Front-End",
      "Precision ADC/DAC",
      "Microcontroller Unit",
      "Signal Conditioning Circuit",
      "Power Management",
      "Shielded PCB Design",
    ],
    salientFeatures: [
      "High precision analog-to-digital conversion.",
      "Low-noise mixed signal architecture.",
      "Optimized PCB layout for signal integrity.",
      "Supports real-time control applications.",
      "High-speed digital signal processing.",
      "Industrial-grade reliability.",
    ],
    scopeOfWork: [
      "Analog Front-End Design",
      "ADC/DAC Integration",
      "Signal Integrity Optimization",
      "Embedded Firmware Development",
      "Noise Isolation Validation",
      "System Testing and Verification",
    ],
  },

  {
    serialNumber: 20,
    id: "rugged-industrial-io-board",
    title: "Rugged Industrial IO Board",
    category: "Industrial Automation",
    cardImageIndex: 1,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rugged_industrial_io_board/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rugged_industrial_io_board/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rugged_industrial_io_board/1.3.png",
    ],
    enlargedImages: { 0: 1.3 },
    features: [
      "Digital and analog IO",
      "Industrial protocol support",
      "Surge protection",
      "Wide temperature operation",
      "DIN rail mounting",
      "Reliable field performance",
    ],
    summary:
      "Rugged industrial IO board engineered for harsh environments with reliable analog and digital interfacing, surge protection, and seamless industrial communication support.",
    importantParts: [
      "Microcontroller Unit",
      "IO Expansion Modules",
      "RS485 Interface",
      "Surge Protection Circuit",
      "Power Supply Unit",
      "Industrial Enclosure",
    ],
    salientFeatures: [
      "Supports 24V industrial IO standards.",
      "Integrated Modbus and RS485 communication.",
      "High ESD and surge protection.",
      "Wide operating temperature range.",
      "DIN rail mounting compatibility.",
      "Long lifecycle industrial components.",
    ],
    scopeOfWork: [
      "Industrial IO Design",
      "Protocol Integration",
      "Protection Circuit Development",
      "Mechanical Ruggedization",
      "Environmental Testing",
      "Compliance Validation",
    ],
  },

  {
    serialNumber: 21,
    id: "thermal-management-system",
    title: "Thermal Analysis and Management",
    category: "Industrial Embedded Systems",
    cardImageIndex: 2,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/thermal_analysis_and_management/1.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/thermal_analysis_and_management/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/thermal_analysis_and_management/1.1.png",
    ],
    features: [
      "Multi-point temperature sensing",
      "Thermal prediction engine",
      "Automated cooling control",
      "Heat dissipation monitoring",
      "Thermal alerts",
      "Remote diagnostics",
    ],
    summary:
      "Industrial thermal management system for real-time heat monitoring, predictive analysis, and automated cooling control to improve reliability and operational efficiency.",
    importantParts: [
      "Temperature Sensor Array",
      "Thermal Controller",
      "Cooling Fan Driver",
      "Data Logger",
      "Ethernet Interface",
      "Industrial Housing",
    ],
    salientFeatures: [
      "Supports multi-zone thermal monitoring.",
      "Automated fan speed regulation.",
      "Predictive overheating alerts.",
      "Historical thermal trend analysis.",
      "Cloud-based monitoring support.",
      "Industrial-grade reliability.",
    ],
    scopeOfWork: [
      "Thermal Sensor Network Design",
      "Cooling Logic Development",
      "Predictive Analytics Implementation",
      "Ethernet Integration",
      "Dashboard Connectivity",
      "Thermal Validation Testing",
    ],
  },

  {
    serialNumber: 22,
    id: "ultra-low-noise-adc-board",
    title: "Ultra Low Noise ADC Board",
    category: "Precision Instrumentation",
    cardImageIndex: 7,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/8.5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/8.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/8.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/8.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/8.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/1.4.png",
    ],
    features: [
      "Ultra-low noise acquisition",
      "High-resolution conversion",
      "Precision analog front-end",
      "Signal isolation",
      "Low drift performance",
      "Scientific instrumentation support",
    ],
    summary:
      "Precision ADC board designed for ultra-low noise signal acquisition with high-resolution conversion, ideal for sensitive measurements and scientific instrumentation.",
    importantParts: [
      "Precision ADC",
      "Low Noise Amplifier",
      "Analog Front-End",
      "Reference Voltage Circuit",
      "Shielded PCB Layout",
      "Power Conditioning Unit",
    ],
    salientFeatures: [
      "24-bit high-resolution ADC architecture.",
      "Ultra-low input referred noise.",
      "Low thermal drift performance.",
      "High stability voltage reference.",
      "Designed for precision instrumentation.",
      "Optimized shielding and grounding.",
    ],
    scopeOfWork: [
      "Precision ADC Design",
      "Analog Front-End Development",
      "Noise Optimization",
      "Reference Circuit Implementation",
      "Signal Integrity Testing",
      "Performance Validation",
    ],
  },

  {
    serialNumber: 23,
    id: "ultra-low-power-ble-mouse",
    title: "Ultra Low Power BLE Mouse",
    category: "Consumer Electronics",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_power_ble_mouse/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_power_ble_mouse/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_power_ble_mouse/1.23.png",
    ],
    features: [
      "Bluetooth Low Energy connectivity",
      "Low standby power",
      "Precision optical tracking",
      "Multi-device switching",
      "Long battery life",
      "Compact ergonomic design",
    ],
    summary:
      "Energy-efficient BLE mouse designed for precision tracking, seamless multi-device connectivity, and extended battery life across laptops and mobile devices.",
    importantParts: [
      "BLE SoC",
      "Optical Sensor",
      "Battery Management Unit",
      "Scroll Encoder",
      "Rechargeable Battery",
      "Compact Housing",
    ],
    salientFeatures: [
      "Battery life exceeding 12 months.",
      "BLE 5.0 connectivity support.",
      "High DPI optical tracking.",
      "Quick switching across 3 devices.",
      "Ultra-low sleep mode current.",
      "Slim ergonomic industrial design.",
    ],
    scopeOfWork: [
      "BLE Hardware Design",
      "Optical Sensor Integration",
      "Power Optimization",
      "Firmware Development",
      "Battery Validation",
      "Mechanical Testing",
    ],
  },

  {
    serialNumber: 24,
    id: "wifi-6e-router",
    title: "Wi-Fi 6E Router",
    category: "Networking & Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/wi-fi_66e_router-_marma/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/wi-fi_66e_router-_marma/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/wi-fi_66e_router-_marma/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/5.png",
    ],
    features: [
      "Wi-Fi 6E connectivity",
      "High-speed multi-band support",
      "Low latency performance",
      "Advanced security protocols",
      "Mesh networking capability",
      "Remote device management",
    ],
    summary:
      "High-performance Wi-Fi 6E router delivering ultra-fast multi-band connectivity, low latency communication, and secure networking for modern connected environments.",
    importantParts: [
      "Wi-Fi 6E Chipset",
      "Multi-Band Antenna Array",
      "Network Processor",
      "Ethernet Controller",
      "Power Management Unit",
      "Thermal Shielding System",
    ],
    salientFeatures: [
      "Supports 2.4GHz, 5GHz, and 6GHz bands.",
      "Gigabit-speed low latency networking.",
      "Advanced WPA3 security support.",
      "Mesh-ready architecture.",
      "Cloud-based router management.",
      "Optimized thermal performance.",
    ],
    scopeOfWork: [
      "Router Hardware Design",
      "RF Optimization",
      "Firmware Development",
      "Security Protocol Integration",
      "Mesh Network Implementation",
      "Performance Testing and Validation",
    ],
  },

  {
    id: "capserve",
    title: "Capserve",
    category: "Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/capserve/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/capserve/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/capserve/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/capserve/2.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/capserve/2.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/capserve/2.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/capserve/2.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/capserve/3.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/capserve/3.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/capserve/3.3.png",
    ],
    features: [
      "Embedded system hardware platform",
      "Compact integrated electronics architecture",
      "Multi-board system integration",
      "Optimized power and communication design",
      "Industrial-grade embedded reliability",
      "Scalable modular hardware structure",
    ],
    summary:
      "Capserve is a scalable embedded hardware platform designed for reliable system integration, efficient communication, and industrial-grade performance.",
    importantParts: [
      "Embedded controller board",
      "Communication interfaces",
      "Power management circuitry",
      "Connector integration modules",
      "Thermal management sections",
      "Peripheral expansion interfaces",
    ],
    salientFeatures: [
      "Compact and modular embedded architecture",
      "Reliable industrial system integration",
      "Efficient power and communication handling",
      "Scalable multi-board platform design",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "System Architecture Development",
      "PCB Integration",
      "Prototype Validation",
      "Manufacturing Support",
    ],
  },
  {
    id: "bluebinaries",
    title: "Blue Binaries",
    category: "Embedded Systems",
    cardImageIndex: 4,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluebinaries/BLUE_BINARIES_PR1.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluebinaries/BLUE_BINARIES_PR1BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluebinaries/BLUE_BINARIES_PR1SIG1.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluebinaries/BLUE_BINARIES_PR1SIG2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluebinaries/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluebinaries/1.2.png",
    ],
    features: [
      "Embedded hardware platform development",
      "Multi-layer PCB and system integration",
      "Optimized signal routing architecture",
      "Efficient embedded power management",
      "Compact industrial-grade design",
      "Reliable communication interface support",
    ],
    summary:
      "Blue Binaries is an embedded systems platform designed for reliable hardware integration, efficient signal management, and scalable industrial deployment.",
    importantParts: [
      "Embedded processing unit",
      "Power regulation circuitry",
      "Signal routing layers",
      "Communication interfaces",
      "Ground and shielding structures",
      "Connector integration sections",
    ],
    salientFeatures: [
      "Compact embedded hardware architecture",
      "Reliable signal and power integrity",
      "Industrial-grade PCB integration",
      "Efficient communication subsystem support",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "PCB Layout Development",
      "Signal Integrity Optimization",
      "Prototype Validation",
      "Manufacturing Support",
    ],
  },
  {
    id: "fedarant",
    title: "Fedarant",
    category: "Embedded Systems",
    cardImageIndex: 3,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/seat_sensor_signal/P01201CB2-SEATSENSOR-SINGLE_PR1_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/seat_sensor_signal/P01201CB2-SEATSENSOR-SINGLE_PR1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/seat_sensor_signal/P01201CB2-SEATSENSOR-SINGLE_PR1_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/fedarant/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/fedarant/1.2.png",
    ],
    features: [
      "Compact embedded hardware platform",
      "Integrated system-level architecture",
      "Efficient power and signal management",
      "Industrial-grade embedded design",
      "Scalable communication interface support",
      "Reliable board-level integration",
    ],
    summary:
      "Fedarant is a compact embedded systems platform designed for reliable hardware integration, efficient communication handling, and scalable industrial deployment.",
    importantParts: [
      "Embedded controller unit",
      "Power management circuitry",
      "Communication interface modules",
      "Signal routing sections",
      "Connector integration zones",
      "Thermal balancing structures",
    ],
    salientFeatures: [
      "Compact and reliable embedded architecture",
      "Efficient signal and power distribution",
      "Scalable hardware integration support",
      "Industrial-grade design reliability",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "System Integration",
      "PCB Layout Optimization",
      "Prototype Validation",
      "Manufacturing Support",
    ],
  },
  {
    id: "high-speed-analog-board",
    title: "High Speed Analog Board",
    category: "Embedded Systems",
    cardImageIndex: 7,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_analog_board/BCW_TOP_S1.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_analog_board/BCW_TOP_S2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_analog_board/BCW_TOP_S3.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_analog_board/BCW_TOP_S14.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_analog_board/N1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_analog_board/N2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_analog_board/N3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_analog_board/2.png",
      // "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_analog_board/1.png",
    ],
    features: [
      "High-speed analog signal processing design",
      "Precision mixed-signal board architecture",
      "Low-noise analog routing optimization",
      "High-frequency signal integrity support",
      "Multi-layer embedded PCB integration",
      "Thermally optimized board layout",
    ],
    summary:
      "A high-speed analog embedded board engineered for precision signal processing, low-noise performance, and reliable high-frequency operation.",
    importantParts: [
      "Analog signal conditioning stage",
      "High-speed routing layers",
      "Power filtering circuitry",
      "Ground isolation regions",
      "Precision analog components",
      "Embedded interface connectors",
    ],
    salientFeatures: [
      "Optimized for high-frequency analog signals",
      "Low-noise precision routing architecture",
      "Reliable mixed-signal integration",
      "Thermally balanced embedded design",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Analog Circuit Integration",
      "PCB Layout Optimization",
      "Signal Integrity Validation",
      "Prototype Testing",
    ],
  },
  {
    id: "rack-pdu",
    title: "Rack PDU",
    category: "Embedded Systems",
    cardImageIndex: 2,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/pdu/RACK_PDU_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/pdu/RACK_PDU_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/pdu/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/pdu/1.2.png",
    ],
    features: [
      "Rack-mounted power distribution system",
      "Embedded power monitoring integration",
      "High-current PCB architecture",
      "Reliable multi-channel power delivery",
      "Industrial-grade thermal management",
      "Compact rack-optimized design",
    ],
    summary:
      "Rack PDU is an embedded power distribution platform designed for reliable rack-level power management, monitoring, and efficient industrial deployment.",
    importantParts: [
      "Power distribution circuitry",
      "Embedded monitoring controller",
      "High-current routing layers",
      "Protection and filtering circuits",
      "Thermal management sections",
      "Rack interface connectors",
    ],
    salientFeatures: [
      "Reliable rack-level power delivery",
      "Integrated embedded monitoring support",
      "Optimized thermal and current handling",
      "Industrial-grade system reliability",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Power Electronics Integration",
      "PCB Layout Development",
      "Thermal and Current Analysis",
      "Prototype Validation",
    ],
  },
  {
    id: "wifi6-triband-router",
    title: "WiFi 6 Triband Router",
    category: "Embedded Systems",
    cardImageIndex: 4,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/V2.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/V2.8.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/V2.7.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/V2.9.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/wifi6_triband_router/1_new.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/wifi6_triband_router/2_new.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/wifi6_triband_router/7.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/wifi6_triband_router/7.2.png",
    ],
    // rotatedImages: { 1: 90, 2: 90, 3: 90 },
    // enlargedImages: { 1: 1.5, 2: 1.3, 3: 1.3 },
    features: [
      "WiFi 6 triband networking platform",
      "High-speed wireless communication architecture",
      "Optimized RF and antenna integration",
      "Compact embedded networking design",
      "Efficient thermal management system",
      "Multi-device connectivity support",
    ],
    summary:
      "A high-performance WiFi 6 triband router platform designed for fast wireless communication, reliable connectivity, and efficient embedded networking operation.",
    importantParts: [
      "WiFi 6 chipset",
      "RF antenna modules",
      "Embedded networking processor",
      "Power management circuitry",
      "Thermal dissipation structure",
      "Ethernet and connectivity interfaces",
    ],
    salientFeatures: [
      "High-speed triband wireless performance",
      "Optimized RF signal handling",
      "Reliable multi-device connectivity",
      "Compact thermally efficient design",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "RF and Antenna Integration",
      "PCB Layout Development",
      "Thermal Optimization",
      "Prototype Testing and Validation",
    ],
  },
  {
    id: "rf-power-processor",
    title: "RF Power Processor",
    category: "Embedded Systems",
    cardImageIndex: 4,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rf_power_processor/RF-POWER-PROCESSOR-TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rf_power_processor/RF-POWER-PROCESSOR-top.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rf_power_processor/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rf_power_processor/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rf_power_processor/3.png",
    ],
    features: [
      "RF power processing architecture",
      "High-frequency signal handling design",
      "Precision RF routing optimization",
      "Efficient thermal power management",
      "Embedded high-power electronics integration",
      "Industrial-grade RF system reliability",
    ],
    summary:
      "RF Power Processor is a high-frequency embedded platform engineered for reliable RF signal processing, efficient power handling, and stable industrial operation.",
    importantParts: [
      "RF signal processing circuitry",
      "Power amplification stages",
      "Thermal dissipation structures",
      "High-frequency routing layers",
      "Power regulation modules",
      "RF interface connectors",
    ],
    salientFeatures: [
      "Optimized for high-frequency RF operation",
      "Efficient thermal and power management",
      "Reliable RF signal integrity",
      "Industrial-grade embedded system stability",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "RF Circuit Integration",
      "PCB Layout Optimization",
      "Thermal and Signal Analysis",
      "Prototype Validation",
    ],
  },
  {
    id: "ultra-low-cost-bldc-motor-controller-for-evs",
    title: "Ultra Low Cost BLDC Motor Controller for EVs",
    category: "Embedded Systems",
    cardImageIndex: 8,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lucas_tvs/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lucas_tvs/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lucas_tvs/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_cost_bldc_motor_controller_for_evs/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_cost_bldc_motor_controller_for_evs/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_cost_bldc_motor_controller_for_evs/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_cost_bldc_motor_controller_for_evs/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_cost_bldc_motor_controller_for_evs/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_cost_bldc_motor_controller_for_evs/Ultra Low Cost BLDC Motor Controller for EVs.png",
    ],
    // rotatedImages: { 0: 90, 1: 90, 2: 90 },
    // enlargedImages: { 0: 1.7, 1: 1.7, 2: 1.7 },
    features: [
      "Low-cost EV motor control platform",
      "BLDC motor driver integration",
      "Efficient power electronics architecture",
      "Compact embedded controller design",
      "Thermal-aware high-current layout",
      "Scalable electric vehicle integration",
    ],
    summary:
      "An ultra low-cost BLDC motor controller platform designed for electric vehicles, delivering efficient motor control, compact integration, and reliable embedded performance.",
    importantParts: [
      "BLDC motor driver stage",
      "Embedded control processor",
      "Power MOSFET section",
      "Current sensing circuitry",
      "Thermal management structures",
      "Power input and output interfaces",
    ],
    salientFeatures: [
      "Cost-optimized EV motor controller design",
      "Efficient BLDC motor driving capability",
      "Compact embedded power electronics layout",
      "Reliable thermal and current handling",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Motor Control Electronics Development",
      "PCB Layout Optimization",
      "Thermal and Power Analysis",
      "Prototype Validation",
    ],
  },

  {
    id: "high-speed-analog-mux",
    title: "High Speed Analog Mux",
    category: "Embedded Systems",
    cardImageIndex: 1,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/acellenttech_br/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/acellenttech_br/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/acellenttech_br/1.3.png",
    ],
    features: [
      "Embedded hardware system integration",
      "Compact industrial electronics platform",
      "Optimized signal and power routing",
      "Reliable embedded communication architecture",
      "Scalable board-level design",
      "Industrial-grade system reliability",
    ],
    summary:
      "AcellentTech BR is an embedded systems platform designed for reliable hardware integration, efficient communication handling, and scalable industrial deployment.",
    importantParts: [
      "Embedded processing unit",
      "Power management circuitry",
      "Communication interfaces",
      "Signal routing sections",
      "Thermal management regions",
      "Connector integration modules",
    ],
    salientFeatures: [
      "Compact embedded hardware architecture",
      "Reliable industrial-grade performance",
      "Efficient signal and power management",
      "Scalable system-level integration",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "System Architecture Development",
      "PCB Integration",
      "Prototype Validation",
      "Manufacturing Support",
    ],
  },
  {
    id: "automotive",
    title: "Automotive Embedded Platform",
    category: "Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/N4.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/N4.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/2.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/2.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/3.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/3.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/4.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/4.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/N8.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/N8.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/N9.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/N9.2.png",
      // "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/5.1.png",
      // "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/automotive/5.2.png",
    ],
    features: [
      "Automotive-grade embedded electronics platform",
      "Vehicle communication system integration",
      "High-reliability embedded architecture",
      "Efficient power and thermal management",
      "Compact automotive hardware design",
      "Scalable embedded control system",
    ],
    summary:
      "An automotive embedded platform designed for reliable vehicle electronics integration, efficient communication handling, and rugged industrial-grade performance.",
    importantParts: [
      "Embedded control processor",
      "Automotive communication interfaces",
      "Power regulation circuitry",
      "Thermal management structures",
      "Signal routing sections",
      "Vehicle interface connectors",
    ],
    salientFeatures: [
      "Automotive-grade reliability and stability",
      "Efficient embedded communication handling",
      "Compact and scalable hardware architecture",
      "Optimized thermal and power management",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Automotive System Integration",
      "PCB Layout Development",
      "Thermal and Signal Analysis",
      "Prototype Validation",
    ],
  },
  {
    id: "smart-rail",
    title: "Smart Rail",
    category: "Embedded Systems",
    cardImageIndex: 8,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/smart_rail/SMART_RAIL_CB/smart_rail_controller_board_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/smart_rail/SMART_RAIL_CB/smart_rail_controller_board_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/smart_rail/SMART_RAIL_CB/smart_rail_controller_board_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/smart_rail/N1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/smart_rail/SMART_RAIL_PB/SMART_RAIL_POWER_BOARD_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/smart_rail/SMART_RAIL_PB/SMART_RAIL_POWER_BOARD_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/smart_rail/N2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/smart_rail/N3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/smart_rail/N4.png",
    ],
    features: [
      "Smart rail embedded control platform",
      "Integrated controller and power boards",
      "Industrial-grade communication architecture",
      "Efficient rail power management system",
      "Scalable embedded monitoring support",
      "Reliable multi-board system integration",
    ],
    summary:
      "Smart Rail is an embedded systems platform engineered for intelligent rail infrastructure control, power management, and reliable industrial operation.",
    importantParts: [
      "Smart rail controller board",
      "Power distribution board",
      "Embedded processing unit",
      "Communication interfaces",
      "Power regulation circuitry",
      "Signal routing and monitoring sections",
    ],
    salientFeatures: [
      "Integrated controller and power architecture",
      "Reliable industrial embedded performance",
      "Efficient rail power distribution design",
      "Scalable monitoring and communication support",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Power Electronics Integration",
      "PCB Layout Development",
      "System Integration Testing",
      "Prototype Validation",
    ],
  },
  {
    id: "lung-sound-recorder",
    title: "Lung Sound Recorder",
    category: "Embedded Systems",
    cardImageIndex: 3,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/lung_sound_recorder/LSR_1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/lung_sound_recorder/LSR_1_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/lung_sound_recorder/3.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/lung_sound_recorder/3.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/lung_sound_recorder/3.1.png",
    ],
    features: [
      "Medical-grade lung sound acquisition system",
      "Embedded audio signal processing platform",
      "Compact wearable healthcare device design",
      "Low-noise analog front-end integration",
      "Efficient embedded power management",
      "Portable diagnostic system architecture",
    ],
    summary:
      "Lung Sound Recorder is an embedded medical device platform designed for accurate respiratory sound acquisition, portable diagnostics, and reliable healthcare monitoring.",
    importantParts: [
      "Audio acquisition circuitry",
      "Embedded processing unit",
      "Low-noise analog front-end",
      "Power management subsystem",
      "Medical sensor interface",
      "Signal conditioning stages",
    ],
    salientFeatures: [
      "High-quality respiratory sound capture",
      "Compact portable medical device architecture",
      "Low-noise embedded signal processing",
      "Reliable healthcare monitoring integration",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Medical Electronics Integration",
      "PCB Layout Development",
      "Signal Integrity Optimization",
      "Prototype Validation",
    ],
  },
  {
    id: "lubrication-controller",
    title: "Lubrication Controller",
    category: "Embedded Systems",
    cardImageIndex: 3,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LUBER/LUBE_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LUBER/LUBE_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LUBER/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LUBER/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LUBER/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LUBER/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LUBER/5.png",
    ],
    features: [
      "Industrial lubrication control platform",
      "Embedded monitoring and control system",
      "Reliable multi-layer PCB integration",
      "Efficient power and signal management",
      "Compact industrial embedded architecture",
      "Scalable machine automation support",
    ],
    summary:
      "Luber is an embedded industrial control platform designed for automated lubrication management, reliable monitoring, and efficient machine integration.",
    importantParts: [
      "Embedded controller unit",
      "Power regulation circuitry",
      "Lubrication control interfaces",
      "Signal routing sections",
      "Industrial communication modules",
      "Monitoring and protection circuits",
    ],
    salientFeatures: [
      "Reliable industrial automation support",
      "Compact embedded control architecture",
      "Efficient monitoring and signal handling",
      "Scalable lubrication management platform",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Industrial Control Integration",
      "PCB Layout Development",
      "System Validation",
      "Prototype Testing",
    ],
  },
  {
    id: "medical-recorder-device",
    title: "Medical Recorder Device",
    category: "Embedded Systems",
    cardImageIndex: 2,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LSR3_Medical_Recorder/LSR-BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LSR3_Medical_Recorder/LSR-TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LSR3_Medical_Recorder/V3.2.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LSR3_Medical_Recorder/V3.2.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LSR3_Medical_Recorder/V3.2.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/LSR3_Medical_Recorder/V3.2.4.png",
      "/case-studies/industrialCaseStudies/2/LSR-10.png",
      "/case-studies/industrialCaseStudies/2/LSR-11.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/ID_Service_2.mp4",
    ],
    features: [
      "Portable medical recording platform",
      "Embedded biomedical signal acquisition",
      "Low-noise medical electronics integration",
      "Compact healthcare device architecture",
      "Reliable embedded data processing",
      "Battery-efficient portable operation",
    ],
    summary:
      "LSR3 Medical Recorder is a portable embedded healthcare platform engineered for biomedical signal acquisition, reliable recording, and efficient medical monitoring applications.",
    importantParts: [
      "Biomedical signal acquisition circuitry",
      "Embedded processing unit",
      "Low-noise analog front-end",
      "Power management subsystem",
      "Sensor and recording interfaces",
      "Data storage and communication modules",
    ],
    salientFeatures: [
      "Portable medical-grade recording system",
      "Low-noise biomedical signal handling",
      "Compact and efficient embedded design",
      "Reliable healthcare monitoring capability",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Medical Electronics Integration",
      "Signal Conditioning Development",
      "PCB Layout Optimization",
      "Prototype Validation",
    ],
  },
  {
    id: "smart-obd2",
    title: "Smart OBD2",
    category: "Embedded Systems",
    cardImageIndex: 4,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/OBD/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/OBD/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/OBD/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Smart_OBD2/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Smart_OBD2/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Smart_OBD2/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/10April2022TekionOBD.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/10April2022TekionOBD.5.png",
    ],
    // rotatedImages: { 0: 90, 1: 90, 2: 90 },
    // enlargedImages: { 0: 1.7, 1: 1.7, 2: 1.7 },
    features: [
      "Smart automotive diagnostic platform",
      "OBD2 vehicle communication integration",
      "Compact embedded automotive design",
      "Real-time vehicle monitoring support",
      "Efficient power and data management",
      "Industrial-grade automotive reliability",
    ],
    summary:
      "Smart OBD2 is an embedded automotive diagnostics platform designed for reliable vehicle communication, real-time monitoring, and intelligent automotive data processing.",
    importantParts: [
      "OBD2 communication interface",
      "Embedded processing unit",
      "Power regulation circuitry",
      "Vehicle data acquisition modules",
      "Wireless communication interfaces",
      "Signal conditioning sections",
    ],
    salientFeatures: [
      "Reliable real-time vehicle diagnostics",
      "Compact automotive embedded architecture",
      "Efficient communication and data handling",
      "Industrial-grade automotive integration",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Automotive Electronics Integration",
      "PCB Layout Development",
      "Signal and Power Optimization",
      "Prototype Validation",
    ],
  },
  {
    id: "security-system-controller",
    title: "Security System Controller",
    category: "Embedded Systems",
    cardImageIndex: 5,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Security_System_Controller/Mx1_PR1.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Security_System_Controller/Mx1_PR2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Security_System_Controller/Mx1_PR3.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Security_System_Controller/Mx1_PR4.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Security_System_Controller/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Security_System_Controller/V2.6.11.PNG",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Security_System_Controller/6.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/Security_System_Controller/2.png",
    ],
    enlargedImages: { 4: 1.1 },
    features: [
      "Embedded security control platform",
      "Multi-layer controller board architecture",
      "Reliable monitoring and access integration",
      "Industrial-grade signal routing design",
      "Efficient power and communication management",
      "Scalable embedded security infrastructure",
    ],
    summary:
      "Security System Controller is an embedded platform designed for reliable security monitoring, intelligent access control, and scalable industrial system integration.",
    importantParts: [
      "Embedded control processor",
      "Security monitoring interfaces",
      "Power management circuitry",
      "Signal routing layers",
      "Communication modules",
      "Access control integration sections",
    ],
    salientFeatures: [
      "Reliable embedded security architecture",
      "Efficient communication and monitoring support",
      "Scalable multi-board controller integration",
      "Industrial-grade operational stability",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Security System Integration",
      "PCB Layout Development",
      "Signal and Power Optimization",
      "Prototype Validation",
    ],
  },
  {
    id: "ir-ble-ac-controller",
    title: "IR BLE AC Controller",
    category: "Embedded Systems",
    cardImageIndex: 3,
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/IR_BLE_AC_Controller/IR BLE AC CONTROLLER_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/IR_BLE_AC_Controller/IR BLE AC CONTROLLER_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/IR_BLE_AC_Controller/IR BLE AC CONTROLLER_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/IR_BLE_AC_Controller/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/IR_BLE_AC_Controller/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/IR_BLE_AC_Controller/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/IR_BLE_AC_Controller/BLE_MESH_AC_CONTROLLER_RENDER_11.5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/IR_BLE_AC_Controller/BLE_MESH_AC_CONTROLLER_RENDER_11.6.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/IR_BLE_AC_Controller/BLE_MESH_AC_CONTROLLER_RENDER_11.7.png",
    ],
    features: [
      "IR and BLE based AC control platform",
      "BLE mesh communication integration",
      "Smart home embedded control architecture",
      "Compact low-power embedded design",
      "Wireless appliance automation support",
      "Reliable multi-layer PCB integration",
    ],
    summary:
      "IR BLE AC Controller is a smart embedded control platform designed for wireless air-conditioner automation using IR transmission and BLE mesh connectivity.",
    importantParts: [
      "BLE communication module",
      "IR transmission circuitry",
      "Embedded control processor",
      "Power management subsystem",
      "Signal routing layers",
      "Wireless mesh networking interfaces",
    ],
    salientFeatures: [
      "Wireless BLE mesh appliance control",
      "Reliable IR-based AC automation",
      "Compact low-power embedded design",
      "Scalable smart home integration",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Wireless Communication Integration",
      "PCB Layout Development",
      "Power Optimization",
      "Prototype Validation",
    ],
  },
  {
    id: "dosingpump",
    title: "Dosing Pump",
    category: "Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/dosingpump/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/dosingpump/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/dosingpump/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/dosingpump/4.png",
    ],
    rotatedImages: {},
    features: [
      "Embedded fluid dosing control platform",
      "Precision pump control electronics",
      "Compact industrial embedded design",
      "Reliable sensor and actuator integration",
      "Efficient power management system",
      "Industrial automation compatibility",
    ],
    summary:
      "Dosing Pump is an embedded control platform designed for precise fluid dispensing, reliable industrial automation, and efficient system integration.",
    importantParts: [
      "Pump control circuitry",
      "Embedded processing unit",
      "Sensor integration modules",
      "Motor driver stage",
      "Power regulation section",
      "Industrial interface connectors",
    ],
    salientFeatures: [
      "Precision fluid dosing control",
      "Reliable embedded automation platform",
      "Compact industrial hardware architecture",
      "Efficient actuator and sensor integration",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "Control Electronics Development",
      "PCB Layout Optimization",
      "System Integration Testing",
      "Prototype Validation",
    ],
  },
];
