import { CaseStudy } from "../../types/case-study";

// ─── Embedded Systems ────────────────────────────────────────────────────────
export const embeddedCaseStudiesData: CaseStudy[] = [
  {
    id: "industrial-temperature-control-system",
    title: "Industrial Temperature Control System",
    category: "Embedded System Design",
    images: [
      "/case-studies/BLUECOLD/1.png",
      "/case-studies/BLUECOLD/2.png",
      "/case-studies/BLUECOLD/BLUE_COLD_REV-01_BRD_03_TOP.svg",
      "/case-studies/BLUECOLD/BLUE_COLD_REV-01_BRD_03_TP.svg",
      "/case-studies/BLUECOLD/5.png",
    ],
    features: [
      "Hardware / Firmware Design and Development",
      "Precision Temperature Sensing and Control",
      "SAMA5D3 Processor / STM32 MCU",
      "POE+ / Ethernet Connectivity",
      "Industrial-grade Enclosure Design",
      "Multi-zone Temperature Management",
    ],
    summary:
      "An industrial-grade temperature control system designed for environments requiring precise thermal regulation. Built around the SAMA5D3 processor, the system supports multi-zone temperature monitoring with high-accuracy sensors and closed-loop PID control. POE+ connectivity enables single-cable deployment for both power and data, simplifying installation in cold-chain, laboratory, and manufacturing settings.",
    importantParts: [
      "Microchip SAMA5D3 Application Processor",
      "ST Micro High Performance MCU",
      "High-accuracy NTC / RTD Temperature Sensors",
      "Linear Technologies POE+ Controller",
    ],
    salientFeatures: [
      "Precision multi-zone temperature control.",
      "POE+ powered for simplified single-cable installation.",
      "Closed-loop PID regulation with configurable setpoints.",
      "Real-time data logging and remote monitoring.",
      "Industrial operating temperature range (-40 °C to +85 °C).",
      "Configurable alarm thresholds and relay outputs.",
      "Nano Flash storage for local data retention.",
      "Remote firmware upgrade capability.",
      "5 % improvement in thermal stability over prior generation.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Board Bring-up and Testing",
      "Enclosure Design",
    ],
  },
  {
    id: "multi-io-card-for-ate",
    title: "Multi IO card for ATE",
    category: "Test & Measurement",
    images: [
      "/case-studies/CHARA/1.png",
      "/case-studies/CHARA/2.png",
      "/case-studies/CHARA/3.png",
      "/case-studies/CHARA/CHARA-T_B.svg",
      "/case-studies/CHARA/CHARA-TB.svg",
      "/case-studies/CHARA/CHARA-top.svg",
    ],
    features: [
      "FPGA Spartan-6 Based Multi-channel IO",
      "High-speed ADC / DAC Sampling",
      "Fiber Optic Interface",
      "Hardware / Firmware Design and Development",
      "PCB Design and Layout",
      "ATE System Integration",
    ],
    summary:
      "A versatile Multi IO card designed for Automated Test Equipment (ATE) platforms, built around a Xilinx Spartan-6 FPGA. The card provides multiple high-speed analog and digital IO channels with fiber optic connectivity for noise-immune data transfer. With 12x faster sampling rates than conventional solutions, it enables precise stimulus generation and measurement capture across a wide range of device-under-test scenarios.",
    importantParts: [
      "Xilinx Spartan-6 FPGA",
      "Analog Devices High-speed ADCs",
      "Texas Instruments DAC and Power Management",
      "Fiber Optic Transceiver Module",
    ],
    salientFeatures: [
      "FPGA-based parallel IO processing.",
      "High-speed ADC sampling for precision measurement.",
      "Fiber optic interface for noise-immune communication.",
      "Multi-channel analog and digital IO.",
      "Configurable test patterns and stimulus generation.",
      "Real-time data acquisition and streaming.",
      "Modular design for integration with ATE racks.",
      "12x faster sampling rate than conventional cards.",
      "Low-latency deterministic IO response.",
    ],
    scopeOfWork: [
      "System Architecture Design",
      "FPGA Development and Programming",
      "Analog Circuit Design",
      "PCB Layout and Design",
      "Firmware Development",
      "Testing and Validation",
      "ATE Integration Support",
    ],
  },
  {
    id: "smart-monitoring-system",
    title: "Smart Monitoring System",
    category: "Industrial Control Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/climate_control/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/climate_control/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/climate_control/3.png",
    ],
    paddedImages: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    features: [
      "ARM Cortex-M7 Processor",
      "FreeRTOS Real-Time Operating System",
      "Multi-sensor Environmental Monitoring",
      "L2 Managed Ethernet Switch",
      "Industrial Grade Components",
      "Remote Dashboard and Alerts",
    ],
    summary:
      "A smart environmental monitoring system powered by an ARM Cortex-M7 processor running FreeRTOS. The system continuously tracks temperature, humidity, air quality, and other environmental parameters across multiple zones. An integrated L2 managed switch enables daisy-chained sensor nodes over a single Ethernet backbone, achieving 40 % better power efficiency through intelligent duty-cycling and POE-powered deployment.",
    importantParts: [
      "ARM Cortex-M7 Processor",
      "L2 Managed Ethernet Switch IC",
      "Industrial Ethernet PHY",
      "Precision Environmental Sensors (Temp, Humidity, CO₂)",
    ],
    salientFeatures: [
      "Real-time multi-zone environmental monitoring.",
      "FreeRTOS for deterministic sensor polling.",
      "L2 managed switch for daisy-chained sensor nodes.",
      "40 % power efficiency through intelligent duty-cycling.",
      "Web-based dashboard for remote monitoring.",
      "Configurable alert thresholds via SNMP.",
      "Industrial operating temperature range.",
      "DIN rail or wall-mount installation.",
      "LED status indicators for each channel.",
    ],
    scopeOfWork: [
      "System Requirements Analysis",
      "Hardware Architecture Design",
      "RTOS Implementation",
      "Sensor Integration and Calibration",
      "Network Stack Development",
      "EMC/EMI Compliance Testing",
      "Industrial Certification",
    ],
  },
  {
    id: "microscopic-camera-control",
    title: "Microscopic Camera Control",
    category: "Imaging & Optics",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/microscopic_camera/1.png",
      "/case-studies/MICROSCOPIC CAMERA/2.png",
      "/case-studies/MICROSCOPIC CAMERA/3.png",
      "/case-studies/MICROSCOPIC CAMERA/4.png",
      "/case-studies/MICROSCOPIC CAMERA/5.png",
    ],
    features: [
      "High-resolution CMOS Image Sensor",
      "Precision Motor Control for Focus and Zoom",
      "OLED Status Display",
      "Hardware / Firmware Design and Development",
      "USB and Ethernet Streaming Interface",
      "Compact Enclosure Design",
    ],
    summary:
      "A microscopic camera control system designed for laboratory and inspection applications. The system drives precision stepper motors for automated focus and zoom adjustment while streaming high-resolution imagery over USB or Ethernet. An on-board OLED display provides real-time status, magnification level, and capture settings. The compact form factor integrates seamlessly with standard microscope mounts.",
    importantParts: [
      "High-resolution CMOS Image Sensor",
      "Microchip PIC Microcontroller",
      "Precision Stepper Motor Drivers",
      "OLED Display Module (96 × 64)",
      "USB 3.0 High-speed Interface IC",
      "Low-noise LDO Voltage Regulators",
    ],
    salientFeatures: [
      "Automated focus and zoom via precision motor control.",
      "High-resolution image capture and live streaming.",
      "OLED display for real-time status and settings.",
      "USB 3.0 and Ethernet output interfaces.",
      "Compatible with standard microscope mounts.",
      "Low-noise power design for image clarity.",
    ],
    scopeOfWork: [
      "Hardware Design",
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Board Bring-up and Testing",
      "Enclosure Design",
    ],
  },
  {
    id: "industrial-iot-gateway-with-poe",
    title: "Industrial IOT gateway with POE",
    category: "Industrial IoT",
    images: [
      "/case-studies/OTT/4.png",
      "/case-studies/OTT/2.png",
      "/case-studies/OTT/3.png",
      "/case-studies/OTT/1.png",
      "/case-studies/OTT/TEK_OTT_REV1P0_BRD_PR3.svg",
      "/case-studies/OTT/TEK_OTT_REV1P0_BRD_PR3.bot.svg",
      "/case-studies/OTT/OTT_RENDER_27_NOV_2024_MG2.1.png",
      "/case-studies/OTT/OTT_RENDER_27_NOV_2024_MG4.4.png",
    ],
    features: [
      "Complete Product Development",
      "HW / FW / Linux System Integration",
      "POE+ Powered with Ethernet Backhaul",
      "Multi-protocol IoT Gateway (LoRa, BLE, CAN)",
      "Mechanical / Enclosure Design",
      "Contract Manufacturing",
    ],
    summary:
      "An industrial IoT gateway with integrated POE+ that bridges field sensors and actuators to cloud platforms. The device aggregates data from LoRa, BLE, and CAN bus endpoints, processes it locally on an STM32F MCU, and forwards it over Ethernet. POE+ provides single-cable power and data, eliminating the need for local AC supplies in factory and warehouse deployments. With 15 km LoRa range and 99.9 % uplink accuracy, it serves as a reliable backbone for large-scale industrial monitoring.",
    importantParts: [
      "ST Microelectronics STM32F ARM Cortex MCU",
      "MultiTech LoRa Module",
      "Raytac BLE 5.0 Module",
      "POE+ PD Controller",
      "Industrial Ethernet PHY",
      "Atmel EEPROM",
    ],
    salientFeatures: [
      "POE+ powered — single-cable deployment.",
      "Multi-radio gateway: LoRa, BLE 5.0, CAN bus.",
      "15 km LoRa range for wide-area sensor coverage.",
      "99.9 % data uplink accuracy.",
      "Local edge processing and data buffering.",
      "Industrial-grade ESD / EMI / surge protection.",
      "Remote firmware upgrade via Ethernet.",
      "DIN rail and wall-mount options.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Board Bring-up and Testing",
      "Enclosure Design",
      "FCC / CE Certification",
      "Low Volume Production",
    ],
  },
  {
    id: "poe-control-unit",
    title: "POE Control unit",
    category: "Power over Ethernet",
    images: [
      "/case-studies/POE/1.png",
      "/case-studies/POE/2.png",
      "/case-studies/POE/1.1.svg",
      "/case-studies/POE/1.2.svg",
      "/case-studies/POE/1.3.svg",
    ],
    features: [
      "IEEE 802.3af/at POE+ Compliant",
      "Multi-port Managed Power Delivery",
      "Temperature and Accelerometer Sensors",
      "Hardware / Firmware Development",
      "Up to 100 m Reach per Port",
      "Compact Enclosure Design",
    ],
    summary:
      "A compact POE control unit that manages power delivery and monitoring across multiple Ethernet-connected devices. The unit is IEEE 802.3af/at compliant and provides per-port power budgeting, fault detection, and remote enable/disable control. On-board temperature and motion sensors trigger automatic safety shutdowns, while the Qi wireless charging interface allows contact-less maintenance of paired accessories. Designed for access control, IP camera, and building automation deployments.",
    importantParts: [
      "POE+ PSE Controller IC",
      "Managed Ethernet Switch IC",
      "ST Micro Temperature and Accelerometer Sensors",
      "Qi Wireless Charging Receiver",
      "Texas Instruments Power Management ICs",
      "ST Micro LDO Voltage Regulators",
    ],
    salientFeatures: [
      "IEEE 802.3af/at POE+ compliant.",
      "Per-port power budgeting and fault isolation.",
      "Up to 100 m reach per port.",
      "On-board temperature and motion sensing.",
      "Remote port enable/disable via web interface.",
      "Qi wireless charging for paired accessories.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Enclosure Design",
      "Board Bring-up and Testing",
    ],
  },
  {
    id: "poe-power-injector",
    title: "POE Power Injector",
    category: "Power over Ethernet",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/poe_power_injector/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/poe_power_injector/4.png",
      "/case-studies/POE/2.1.svg",
      "/case-studies/POE/2.2.svg",
    ],
    features: [
      "IEEE 802.3af/at/bt POE Injection",
      "Multi-port Mid-span Design",
      "TCP/IP and MQTT Management Protocols",
      "Dual-band 2.4 GHz Monitoring Radio",
      "Hardware / PCB Design",
      "48 GPIO Expansion Pins",
    ],
    summary:
      "A multi-port POE power injector (mid-span) that adds POE capability to existing non-POE Ethernet switches. The unit injects power into up to 48 Ethernet ports simultaneously while maintaining full data pass-through at Gigabit speeds. An on-board management interface accessible via TCP/IP and MQTT enables per-port power monitoring, scheduling, and remote reboot. Three simultaneous operating modes allow mixed 802.3af, 802.3at, and 802.3bt devices on the same chassis.",
    importantParts: [
      "Multi-port POE PSE Controller",
      "High-efficiency Isolated DC-DC Converters",
      "Gigabit Ethernet Magnetics",
      "Macronix 16 Mb NOR Flash Memory",
    ],
    salientFeatures: [
      "Supports 802.3af / at / bt standards.",
      "Up to 48 injected ports per unit.",
      "TCP/IP and MQTT management protocols.",
      "Three simultaneous POE modes.",
      "Per-port power metering and scheduling.",
      "Gigabit pass-through with zero data degradation.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Power Integrity Testing",
      "Board Bring-up and Testing",
    ],
  },
  {
    id: "industrial-poe-switch",
    title: "Industrial POE switch",
    category: "Power over Ethernet",
    images: [
      "/case-studies/POE/5.png",
      "/case-studies/POE/6.png",
      "/case-studies/POE/3.1.svg",
      "/case-studies/POE/3.2.svg",
    ],
    features: [
      "Managed L2 Industrial Ethernet Switch",
      "8 / 16 / 24 Port POE+ Output",
      "WPA3 / TLS Secure Management",
      "Zero-config Plug-and-play Deployment",
      "Hardened Enclosure for Industrial Environments",
      "USB-C 5 V Console Port",
    ],
    summary:
      "A ruggedised industrial POE switch providing managed L2 switching with POE+ power delivery across 8 to 24 Gigabit ports. The zero-config deployment mode enables 90 % faster setup compared to traditional managed switches, while WPA3 and TLS-secured management protect against unauthorised access. The fanless design with an extended operating temperature range makes it suitable for factory floors, outdoor cabinets, and harsh industrial environments.",
    importantParts: [
      "Managed L2 Ethernet Switch Controller",
      "POE+ PSE Controllers (per-port)",
      "Industrial-grade Ethernet Magnetics",
      "Macronix NOR Flash Memory",
      "CUI Industrial Power Supply Module",
    ],
    salientFeatures: [
      "Managed L2 switching with POE+ on every port.",
      "Zero-config mode for 90 % faster deployment.",
      "WPA3 / TLS secured management interface.",
      "Fanless design for harsh environments.",
      "Extended operating temperature (-40 °C to +75 °C).",
      "USB-C 5 V console port for local configuration.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Power Integrity Testing",
      "Enclosure Design",
      "Board Bring-up and Testing",
    ],
  },
  {
    id: "stellar-main-board",
    title: "Stellar Main Board",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_main_board/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_main_board/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_main_board/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_main_board/4.png",
      "/case-studies/STELLAR MAIN BORD/MAIN BOARD 1.svg",
      "/case-studies/STELLAR MAIN BORD/MAIN BOARD 2.svg",
    ],
    features: [
      "High-density Multi-layer Main Board",
      "SFP+ Network Ports (Grandmaster / Backhaul / Auxiliary)",
      "GPS / RTC Precision Timing",
      "LOM (Lights Out Management) Module",
      "Hardware / Firmware Design and Development",
      "USB-C and Power Board Interface",
    ],
    summary:
      "A high-density embedded main board designed for network timing and synchronisation applications. Built around the FEDERON 2600 platform, the board integrates multiple SFP+ network interfaces for Grandmaster, Backhaul, and Auxiliary channels alongside a GPS/RTC subsystem for precision time-keeping. A dedicated LOM (Lights Out Management) module enables remote board management, while the power board connector supports modular power delivery. The dense multi-layer design accommodates high-speed signal routing across hundreds of components in a compact footprint.",
    importantParts: [
      "High-performance Application Processor",
      "SFP+ Transceiver Modules (Grandmaster, Backhaul, Auxiliary)",
      "GPS Receiver and RTC Module",
      "LOM (Lights Out Management) Controller",
      "USB-C Interface Controller",
      "Multi-rail Power Management ICs",
    ],
    salientFeatures: [
      "Multi-channel SFP+ network interfaces.",
      "GPS / RTC for precision timing and synchronisation.",
      "LOM module for remote management and monitoring.",
      "High-density multi-layer PCB design.",
      "Modular power board interconnect.",
      "USB-C interface for configuration and diagnostics.",
      "Compact footprint with high component density.",
    ],
    scopeOfWork: [
      "System Architecture Design",
      "Schematics Entry",
      "PCB Layout Design (Multi-layer)",
      "PCB Fabrication and Assembly",
      "Firmware Development",
      "Board Bring-up and Testing",
      "Signal Integrity Analysis",
    ],
  },
  {
    id: "stellar-power-board",
    title: "Portable EV Charger",
    category: "Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_power_board/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_power_board/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_power_board/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_power_board/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/stellar_power_board/5.png",
    ],
    rotatedImages: {},
    features: [
      "High-efficiency power management board",
      "Multi-rail power distribution design",
      "Thermal-optimized layout",
      "Stable voltage regulation",
      "Protection and filtering circuits",
      "Compact embedded integration",
    ],
    summary:
      "A dedicated embedded power board engineered for efficient power distribution, thermal performance, and reliable operation across complex embedded systems.",
    importantParts: [
      "DC-DC converters",
      "Voltage regulators",
      "Power filtering components",
      "Thermal dissipation structures",
      "Protection circuits",
      "Power distribution network",
    ],
    salientFeatures: [
      "Efficient multi-rail power delivery",
      "Thermally optimized PCB design",
      "Stable and reliable voltage regulation",
      "Robust protection mechanisms",
    ],
    scopeOfWork: [
      "Power Electronics Design",
      "PCB Layout Development",
      "Thermal Analysis",
      "Power Integrity Validation",
      "Prototype Testing",
    ],
  },
  {
    id: "industrial-automation-controller",
    title: "Industrial Automation Controller",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK/4.png",
      "/case-studies/embedded/HIPPACK1/2.1.svg",
      "/case-studies/embedded/HIPPACK1/2.2.svg",
    ],
    features: [
      "Real-time processing capabilities",
      "Multiple communication protocols",
      "Modular I/O expansion",
      "Manufacturing and process control",
      "Cortex-A9 Processor",
      "Modbus / EtherCAT Support",
    ],
    summary:
      "Advanced industrial automation controller with real-time processing capabilities, supporting multiple communication protocols and modular I/O expansion. Designed for manufacturing and process control applications with 99.9% system uptime.",
    importantParts: [
      "ARM Cortex-A9 Processor",
      "Real-time Kernel",
      "Industrial Ethernet Interface",
      "Modular I/O Cards",
      "Power Management Module",
      "Industrial Housing",
    ],
    salientFeatures: [
      "Real-time processing with deterministic response.",
      "Support for Modbus and EtherCAT protocols.",
      "Modular I/O expansion capability.",
      "Industrial temperature and vibration rated.",
      "99.9% system uptime in field deployments.",
      "Remote monitoring and diagnostics.",
    ],
    scopeOfWork: [
      "System Architecture Design",
      "Hardware Development",
      "Real-time Firmware Development",
      "Protocol Implementation",
      "Testing and Validation",
      "Industrial Certification",
    ],
  },
  {
    id: "high-speed-camera-interface",
    title: "High Speed Camera Interface",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK2/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK2/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK2/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/HIPPACK2/4.png",
      "/case-studies/embedded/HIPPACK2/1.1.svg",
      "/case-studies/embedded/HIPPACK2/1.2.svg",
    ],
    features: [
      "Multi-protocol wireless aggregation",
      "Advanced mesh networking",
      "Cloud connectivity",
      "Automatic routing",
      "512 MB RAM",
      "256 device capacity",
    ],
    summary:
      "Multi-protocol wireless hub aggregating sensor data from distributed IoT devices. Features advanced mesh networking with automatic routing and cloud connectivity for analytics.",
    importantParts: [
      "Multi-radio Transceiver Module",
      "Mesh Networking Processor",
      "512 MB RAM and Storage",
      "Cloud Interface Controller",
      "Power Management",
      "Industrial Enclosure",
    ],
    salientFeatures: [
      "Support for BLE, Wi-Fi, and ZigBee simultaneously.",
      "Advanced mesh networking with automatic routing.",
      "Cloud connectivity for remote analytics.",
      "Up to 256 connected devices.",
      "500m range in open space.",
      "Low-power operation for extended deployment.",
    ],
    scopeOfWork: [
      "System Architecture",
      "Wireless Protocol Integration",
      "Mesh Networking Implementation",
      "Cloud API Development",
      "Hardware Design",
      "Testing and Validation",
    ],
  },
  {
    id: "real-time-data-logger",
    title: "Real-time Data Logger",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/battery_pack/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/battery_pack/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/battery_management_system/1.3.png",
    ],
    features: [
      "High-speed data logging",
      "Onboard storage",
      "Real-time analytics",
      "Configurable sampling rates",
      "100 kHz sampling",
      "32 parallel channels",
    ],
    summary:
      "High-speed data logging device for industrial monitoring with onboard storage and real-time analytics. Supports multiple analog and digital input channels with configurable sampling rates.",
    importantParts: [
      "High-speed ADC Array",
      "Real-time Processing Processor",
      "1 TB eMMC Storage",
      "Signal Conditioning Circuits",
      "Power Management",
      "Industrial Housing",
    ],
    salientFeatures: [
      "100 kHz maximum sampling rate.",
      "32 analog input channels.",
      "1 TB onboard eMMC storage.",
      "Real-time data processing.",
      "Configurable recording parameters.",
      "Timestamp synchronization for multi-channel data.",
    ],
    scopeOfWork: [
      "High-speed ADC Design",
      "Firmware Development",
      "Storage Interface Design",
      "Real-time Processing",
      "Testing and Validation",
      "System Integration",
    ],
  },
  {
    id: "environmental-monitoring-station",
    title: "Environmental Monitoring Station",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluetooth_mouse/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluetooth_mouse/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluetooth_mouse/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/bluetooth_mouse/1.4.png",
    ],
    features: [
      "Integrated environmental sensors",
      "Solar charging capability",
      "Extended battery life",
      "LoRaWAN connectivity",
      "6-point environmental sensing",
      "2-year battery autonomy",
    ],
    summary:
      "Compact environmental monitoring system with integrated sensors for temperature, humidity, air quality, and atmospheric pressure. Features solar charging and extended battery life.",
    importantParts: [
      "Multi-sensor Array",
      "Solar Charging Controller",
      "Long-life Battery Pack",
      "LoRaWAN Module",
      "Wireless Power Module",
      "Weatherproof Enclosure",
    ],
    salientFeatures: [
      "6-point environmental sensing (Temp, Humidity, AQ, Pressure, etc).",
      "Solar panel with maximum power point tracking.",
      "2-year battery autonomy on solar charging.",
      "LoRaWAN connectivity for long-range deployment.",
      "Low-power sleep modes for extended operation.",
      "IP67 weatherproof rating.",
    ],
    scopeOfWork: [
      "Sensor Integration",
      "Solar Charging Design",
      "Power Management",
      "LoRaWAN Integration",
      "Enclosure Design",
      "Field Testing and Validation",
    ],
  },
  {
    id: "smart-building-controller",
    title: "Smart Building Controller",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/connected_car_demonstration_unit/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/connected_car_demonstration_unit/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/connected_car_demonstration_unit/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/connected_car_demonstration_unit/1.4.png",
    ],
    features: [
      "Building management system controller",
      "HVAC and lighting coordination",
      "Security system integration",
      "Energy optimization",
      "Occupancy-based automation",
      "128-zone capability",
    ],
    summary:
      "Intelligent building management system controller coordinating HVAC, lighting, and security systems. Provides energy optimization and occupancy-based automation.",
    importantParts: [
      "Dual-core ARM Processor",
      "Zone Control Modules",
      "Building Protocol Interface",
      "Occupancy Sensors",
      "Power Management",
      "Industrial Networking",
    ],
    salientFeatures: [
      "Support for up to 128 building zones.",
      "BACnet and KNX protocol support.",
      "Dual-core ARM processing for real-time control.",
      "Occupancy-based heating, cooling, and lighting.",
      "40% energy consumption reduction.",
      "Remote monitoring and diagnostics.",
    ],
    scopeOfWork: [
      "Building Protocol Integration",
      "Control Algorithm Development",
      "Hardware Design",
      "System Integration",
      "Field Testing",
      "Commissioning Support",
    ],
  },
  {
    id: "medical-device-interface",
    title: "Medical Device Interface",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/pcb_a/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/pcb_a/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/embedded_1/1.3.png",
    ],
    features: [
      "FDA-compliant interface module",
      "Legacy medical equipment connectivity",
      "Modern networked healthcare systems",
      "Rigorous data validation",
      "Secure communication",
      "99.99% SLA uptime",
    ],
    summary:
      "FDA-compliant interface module for connecting legacy medical equipment to modern networked healthcare systems. Includes rigorous data validation and secure communication.",
    importantParts: [
      "Medical-grade Processor",
      "HL7 / DICOM Protocol Stack",
      "Secure Communication Module",
      "Data Validation Engine",
      "Battery Backup",
      "Medical-certified Housing",
    ],
    salientFeatures: [
      "FDA Class II medical device certification.",
      "HL7 and DICOM protocol support.",
      "Zero data loss incidents in field deployment.",
      "99.99% SLA uptime guarantee.",
      "Encrypted data transmission.",
      "Comprehensive audit logging.",
    ],
    scopeOfWork: [
      "FDA Compliance Planning",
      "Protocol Implementation",
      "Security Hardening",
      "Data Validation Design",
      "Testing and Validation",
      "Regulatory Submission Support",
    ],
  },
  {
    id: "robotics-motion-controller",
    title: "Robotics Motion Controller",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/embedded_2/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/embedded_2/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/embedded_2/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/embedded_2/1.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/femtofarad_level_capacitance/1.3.png",
    ],
    features: [
      "High-precision motion control",
      "Real-time servo control",
      "Trajectory planning",
      "Multiple kinematic configurations",
      "16-axis capability",
      "±0.1mm accuracy",
    ],
    summary:
      "High-precision motion controller for industrial robotic arms with real-time servo control and trajectory planning. Supports multiple kinematic configurations.",
    importantParts: [
      "Real-time Control Processor",
      "Multi-axis Servo Drivers",
      "Motion Planning Engine",
      "Encoder Interface",
      "Industrial Networking",
      "Emergency Stop Interface",
    ],
    salientFeatures: [
      "Support for up to 16 simultaneous axes.",
      "4 kHz control loop refresh rate.",
      "±0.1mm trajectory accuracy.",
      "Multiple kinematic configuration support.",
      "Real-time trajectory planning.",
      "Safety-certified emergency stop circuits.",
    ],
    scopeOfWork: [
      "Motion Control Algorithm Development",
      "Servo Driver Integration",
      "Trajectory Planning Implementation",
      "Hardware Design",
      "Testing and Validation",
      "Safety Certification",
    ],
  },
  {
    id: "power-distribution-monitor",
    title: "Power Distribution Monitor",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_data_acquisation/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_data_acquisation/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/high_speed_data_acquisation/1.3.png",
    ],
    features: [
      "Three-phase power monitoring",
      "Comprehensive metering",
      "Harmonics analysis",
      "Fault detection",
      "Predictive maintenance",
      "25 measurable parameters",
    ],
    summary:
      "Three-phase power distribution monitoring device with comprehensive metering, harmonics analysis, and fault detection. Enables predictive maintenance of electrical infrastructure.",
    importantParts: [
      "3-phase Measurement ICs",
      "Harmonics Analyzer",
      "Data Logging Memory",
      "Ethernet Interface",
      "Power Supply",
      "Industrial Housing",
    ],
    salientFeatures: [
      "3-phase 480V monitoring capability.",
      "Class 0.5 measurement accuracy.",
      "63rd order harmonics analysis.",
      "25 measurable electrical parameters.",
      "Predictive fault detection algorithms.",
      "Cloud connectivity for remote monitoring.",
    ],
    scopeOfWork: [
      "3-phase Measurement Design",
      "Harmonics Analysis Implementation",
      "Fault Detection Algorithms",
      "Data Logging and Storage",
      "Ethernet Integration",
      "Testing and Validation",
    ],
  },

  {
    id: "mixed-signal-system",
    title: "Mixed Signal System",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/mixed_signal/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/mixed_signal/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/mixed_signal/1.3.png",
    ],
    features: [
      "Analog and digital integration",
      "Signal conditioning",
      "Precision data conversion",
      "Noise isolation",
      "High-speed signal processing",
      "System-level optimization",
    ],
    summary:
      "High-performance mixed signal system combining precision analog front-end design with digital processing for accurate sensing, control, and real-time embedded applications.",
    importantParts: [
      "Analog Front-End",
      "Precision ADC/DAC",
      "Microcontroller Unit",
      "Signal Conditioning Circuit",
      "Power Management",
      "Shielded PCB Design",
    ],
    salientFeatures: [
      "High precision analog-to-digital conversion.",
      "Low-noise mixed signal architecture.",
      "Optimized PCB layout for signal integrity.",
      "Supports real-time control applications.",
      "High-speed digital signal processing.",
      "Industrial-grade reliability.",
    ],
    scopeOfWork: [
      "Analog Front-End Design",
      "ADC/DAC Integration",
      "Signal Integrity Optimization",
      "Embedded Firmware Development",
      "Noise Isolation Validation",
      "System Testing and Verification",
    ],
  },

  {
    id: "rugged-industrial-io-board",
    title: "Rugged Industrial IO Board",
    category: "Industrial Automation",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rugged_industrial_io_board/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rugged_industrial_io_board/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/rugged_industrial_io_board/1.1.png",
    ],
    features: [
      "Digital and analog IO",
      "Industrial protocol support",
      "Surge protection",
      "Wide temperature operation",
      "DIN rail mounting",
      "Reliable field performance",
    ],
    summary:
      "Rugged industrial IO board engineered for harsh environments with reliable analog and digital interfacing, surge protection, and seamless industrial communication support.",
    importantParts: [
      "Microcontroller Unit",
      "IO Expansion Modules",
      "RS485 Interface",
      "Surge Protection Circuit",
      "Power Supply Unit",
      "Industrial Enclosure",
    ],
    salientFeatures: [
      "Supports 24V industrial IO standards.",
      "Integrated Modbus and RS485 communication.",
      "High ESD and surge protection.",
      "Wide operating temperature range.",
      "DIN rail mounting compatibility.",
      "Long lifecycle industrial components.",
    ],
    scopeOfWork: [
      "Industrial IO Design",
      "Protocol Integration",
      "Protection Circuit Development",
      "Mechanical Ruggedization",
      "Environmental Testing",
      "Compliance Validation",
    ],
  },

  {
    id: "thermal-management-system",
    title: "Thermal Analysis and Management",
    category: "Industrial Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/thermal_analysis_and_management/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/thermal_analysis_and_management/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/thermal_analysis_and_management/1.4.png",
    ],
    features: [
      "Multi-point temperature sensing",
      "Thermal prediction engine",
      "Automated cooling control",
      "Heat dissipation monitoring",
      "Thermal alerts",
      "Remote diagnostics",
    ],
    summary:
      "Industrial thermal management system for real-time heat monitoring, predictive analysis, and automated cooling control to improve reliability and operational efficiency.",
    importantParts: [
      "Temperature Sensor Array",
      "Thermal Controller",
      "Cooling Fan Driver",
      "Data Logger",
      "Ethernet Interface",
      "Industrial Housing",
    ],
    salientFeatures: [
      "Supports multi-zone thermal monitoring.",
      "Automated fan speed regulation.",
      "Predictive overheating alerts.",
      "Historical thermal trend analysis.",
      "Cloud-based monitoring support.",
      "Industrial-grade reliability.",
    ],
    scopeOfWork: [
      "Thermal Sensor Network Design",
      "Cooling Logic Development",
      "Predictive Analytics Implementation",
      "Ethernet Integration",
      "Dashboard Connectivity",
      "Thermal Validation Testing",
    ],
  },

  {
    id: "ultra-low-noise-adc-board",
    title: "Ultra Low Noise ADC Board",
    category: "Precision Instrumentation",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_noice_adc_board/1.3.png",
    ],
    features: [
      "Ultra-low noise acquisition",
      "High-resolution conversion",
      "Precision analog front-end",
      "Signal isolation",
      "Low drift performance",
      "Scientific instrumentation support",
    ],
    summary:
      "Precision ADC board designed for ultra-low noise signal acquisition with high-resolution conversion, ideal for sensitive measurements and scientific instrumentation.",
    importantParts: [
      "Precision ADC",
      "Low Noise Amplifier",
      "Analog Front-End",
      "Reference Voltage Circuit",
      "Shielded PCB Layout",
      "Power Conditioning Unit",
    ],
    salientFeatures: [
      "24-bit high-resolution ADC architecture.",
      "Ultra-low input referred noise.",
      "Low thermal drift performance.",
      "High stability voltage reference.",
      "Designed for precision instrumentation.",
      "Optimized shielding and grounding.",
    ],
    scopeOfWork: [
      "Precision ADC Design",
      "Analog Front-End Development",
      "Noise Optimization",
      "Reference Circuit Implementation",
      "Signal Integrity Testing",
      "Performance Validation",
    ],
  },

  {
    id: "ultra-low-power-ble-mouse",
    title: "Ultra Low Power BLE Mouse",
    category: "Consumer Electronics",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_power_ble_mouse/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_power_ble_mouse/1.23.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/ultra_low_power_ble_mouse/1.3.png",
    ],
    features: [
      "Bluetooth Low Energy connectivity",
      "Low standby power",
      "Precision optical tracking",
      "Multi-device switching",
      "Long battery life",
      "Compact ergonomic design",
    ],
    summary:
      "Energy-efficient BLE mouse designed for precision tracking, seamless multi-device connectivity, and extended battery life across laptops and mobile devices.",
    importantParts: [
      "BLE SoC",
      "Optical Sensor",
      "Battery Management Unit",
      "Scroll Encoder",
      "Rechargeable Battery",
      "Compact Housing",
    ],
    salientFeatures: [
      "Battery life exceeding 12 months.",
      "BLE 5.0 connectivity support.",
      "High DPI optical tracking.",
      "Quick switching across 3 devices.",
      "Ultra-low sleep mode current.",
      "Slim ergonomic industrial design.",
    ],
    scopeOfWork: [
      "BLE Hardware Design",
      "Optical Sensor Integration",
      "Power Optimization",
      "Firmware Development",
      "Battery Validation",
      "Mechanical Testing",
    ],
  },

  {
    id: "wifi-6e-router-marma",
    title: "Wi-Fi 6E Router - Marma",
    category: "Networking & Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/wi-fi_66e_router-_marma/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/wi-fi_66e_router-_marma/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/embedded/wi-fi_66e_router-_marma/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/5.png",
    ],
    features: [
      "Wi-Fi 6E connectivity",
      "High-speed multi-band support",
      "Low latency performance",
      "Advanced security protocols",
      "Mesh networking capability",
      "Remote device management",
    ],
    summary:
      "High-performance Wi-Fi 6E router delivering ultra-fast multi-band connectivity, low latency communication, and secure networking for modern connected environments.",
    importantParts: [
      "Wi-Fi 6E Chipset",
      "Multi-Band Antenna Array",
      "Network Processor",
      "Ethernet Controller",
      "Power Management Unit",
      "Thermal Shielding System",
    ],
    salientFeatures: [
      "Supports 2.4GHz, 5GHz, and 6GHz bands.",
      "Gigabit-speed low latency networking.",
      "Advanced WPA3 security support.",
      "Mesh-ready architecture.",
      "Cloud-based router management.",
      "Optimized thermal performance.",
    ],
    scopeOfWork: [
      "Router Hardware Design",
      "RF Optimization",
      "Firmware Development",
      "Security Protocol Integration",
      "Mesh Network Implementation",
      "Performance Testing and Validation",
    ],
  },
];
