import { CaseStudy } from "../../types/case-study";

// ─── Engineering Support Services ────────────────────────────────────────────
export const engineeringSupportCaseStudiesData: CaseStudy[] = [
  {
    id: "value-added-services",
    title: "Value Added Services",
    category: "Industrial Services",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services/2.jpg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services/3.jpg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services/20231130_185415.jpg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services/20231130_185424%20-%20Trim.mp4",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services/20231130_185716%20-%20Trim.mp4",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services/20250507_113945.jpg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services/20251011_142408.jpg",
    ],
    rotatedImages: {},
    features: [
      "End-to-end industrial support services",
      "On-site technical assistance",
      "Product integration and deployment support",
      "Industrial installation coordination",
      "Maintenance and operational assistance",
      "Custom engineering service workflows",
    ],
    summary:
      "A collection of value-added industrial services focused on deployment support, integration assistance, and operational reliability across engineering projects.",
    importantParts: [
      "On-site deployment activities",
      "Technical integration workflows",
      "Installation support systems",
      "Field service coordination",
      "Industrial operational support",
      "Customer-specific engineering assistance",
    ],
    salientFeatures: [
      "Comprehensive industrial support services",
      "Field-ready technical assistance",
      "Reliable deployment and integration workflows",
      "Customer-focused engineering execution",
    ],
    scopeOfWork: [
      "Technical Support Services",
      "Industrial Deployment Assistance",
      "System Integration Support",
      "Operational Coordination",
      "Field Service Execution",
    ],
  },
  {
    id: "value-added-services-testing",
    title: "Testing & Validation Services",
    category: "Value Added Services",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services_testing/1000016282.jpg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services_testing/1000016425.jpg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services_testing/1000016426.jpg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services_testing/1000016427.jpg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services_testing/1000016428.jpg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services_testing/1000130945.jpg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_services_testing/video.mp4",
    ],
    rotatedImages: {},
    features: [
      "Product testing and validation services",
      "Environmental and field testing support",
      "Functional verification and performance evaluation",
      "Engineering test setup development",
      "Reliability and durability assessment",
      "Documentation and reporting services",
    ],
    summary:
      "Comprehensive testing and validation services covering product qualification, performance verification, environmental testing, and field validation for engineering products and systems.",
    importantParts: [
      "Functional testing procedures",
      "Environmental test setups",
      "Performance measurement systems",
      "Validation documentation",
      "Reliability assessment workflows",
      "Field testing activities",
    ],
    salientFeatures: [
      "End-to-end product validation support",
      "Comprehensive testing methodologies",
      "Field and laboratory verification",
      "Detailed engineering reporting",
    ],
    scopeOfWork: [
      "Functional Testing",
      "Validation & Verification",
      "Environmental Testing",
      "Reliability Assessment",
      "Engineering Documentation",
    ],
  },
  {
    id: "value-added-services-production",
    title: "Production & Manufacturing Support",
    category: "Value Added Services",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_service_production/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_service_production/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_service_production/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_service_production/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_service_production/5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_service_production/6.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_service_production/7.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_service_production/8.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_service_production/9.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/value_added_service_production/10.png",
    ],
    rotatedImages: {},
    features: [
      "Production engineering support",
      "Manufacturing process optimization",
      "Assembly and integration services",
      "Quality assurance and inspection",
      "Supply chain coordination",
      "Pilot and mass production assistance",
    ],
    summary:
      "Comprehensive production and manufacturing support services covering assembly, process optimization, quality assurance, and scalable product realization from prototype to production.",
    importantParts: [
      "Production line setup",
      "Assembly workflows",
      "Quality inspection processes",
      "Manufacturing documentation",
      "Supply chain coordination",
      "Production validation activities",
    ],
    salientFeatures: [
      "End-to-end manufacturing support",
      "Production-ready engineering processes",
      "Quality-focused execution",
      "Scalable volume manufacturing assistance",
    ],
    scopeOfWork: [
      "Production Engineering",
      "Assembly Support",
      "Quality Assurance",
      "Manufacturing Process Development",
      "Production Validation",
    ],
  },

  {
    id: "multi-disciplinary-engineering-support",
    title: "Multi-Disciplinary Engineering Support",
    category: "Engineering Support Services",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/engineering_support_services/multi_disciplinary_engineering_support/DSC_2078.JPG",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/engineering_support_services/multi_disciplinary_engineering_support/DSC_2080.JPG",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/engineering_support_services/multi_disciplinary_engineering_support/DSC_2083.JPG",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/engineering_support_services/multi_disciplinary_engineering_support/DSC_2110.JPG",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/engineering_support_services/multi_disciplinary_engineering_support/DSC_2115.JPG",
    ],
    rotatedImages: {},
    features: [
      "Cross-functional engineering expertise",
      "Hardware and mechanical system integration",
      "Product development lifecycle support",
      "Prototype development and validation",
      "Engineering analysis and optimization",
      "Production and deployment assistance",
    ],
    summary:
      "Multi-disciplinary engineering support services bringing together expertise across hardware, embedded systems, mechanical design, and product development to solve complex engineering challenges.",
    importantParts: [
      "Cross-functional engineering teams",
      "Prototype development workflows",
      "System integration processes",
      "Engineering validation activities",
      "Testing and analysis infrastructure",
      "Production support processes",
    ],
    salientFeatures: [
      "Integrated multi-disciplinary engineering expertise",
      "End-to-end product development support",
      "Collaborative system-level problem solving",
      "Scalable engineering resources and capabilities",
    ],
    scopeOfWork: [
      "Engineering Consulting",
      "System Integration",
      "Prototype Development",
      "Testing and Validation",
      "Production Support",
    ],
  },
];
