import { CaseStudy } from "../../types/case-study";

// ─── Industrial Design ────────────────────────────────────────────────────────
export const industrialCaseStudiesData: CaseStudy[] = [
  {
    serialNumber: 1,
    id: "oxygen-generator",
    title: "Oxygen Generator",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/5.png",
    ],
    features: [
      "Handheld controller enclosure optimised for factory floor use",
      "Balanced grip ergonomics for long-duration operation",
      "IP54-rated sealed I/O ports and robust mounting points",
      "Split-housing concept aligned to DFM and assembly feasibility",
      "Tactile button layout with glove-friendly actuation force",
      "ABS / TPE over-mould construction",
    ],
    summary:
      "An industrial design study focused on a handheld automation controller built for demanding shop-floor environments. The concept prioritises operator comfort, clear visual hierarchy on the front face, and manufacturable geometry so the product can move from concept to pilot production with minimal redesign. The split-housing strategy enables straightforward assembly and in-field serviceability.",
    importantParts: [
      "Impact-resistant ABS primary shell",
      "TPE over-mould grip zones",
      "Sealed membrane keypad with tactile dome switches",
      "Integrated lanyard lug and belt-clip boss",
      "Snap-fit PCB retention system",
      "Colour-coded I/O port surround",
    ],
    salientFeatures: [
      "Rugged visual language suited to industrial settings.",
      "Improved hand feel and confident grip geometry.",
      "Clear front-face interaction zones reduce operator errors.",
      "IP54 rated enclosure resists dust and splash.",
      "DFM-reviewed design ready for tooling transition.",
      "Service-accessible battery and PCB compartment.",
    ],
    scopeOfWork: [
      "Industrial design concepting and ideation",
      "Form exploration and refinement",
      "3D CAD surfacing and detailing",
      "Design-for-manufacture review",
      "Prototype build and ergonomics evaluation",
    ],
  },
  {
    serialNumber: 2,
    id: "medical-diagnostic-system",
    title: "Medical Diagnostic System",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/rettina_scanner/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/rettina_scanner/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/rettina_scanner/3.png",
    ],
    features: [
      "IEC 60601-compliant enclosure design",
      "Antimicrobial surface finish for clinical environments",
      "5-inch capacitive touch display with glove-mode support",
      "User-centred control layout validated through HF testing",
      "Cable management and mounting arm compatibility",
      "Designed for sterilisation wipe-down procedures",
    ],
    summary:
      "A user-centred medical diagnostic device concept developed to improve diagnostic workflow speed and reduce clinician cognitive load. The enclosure features a clean, uncluttered visual language, an intuitive control hierarchy, and geometry that supports routine sterile wipe-down protocols. Human factors testing informed button placement and screen tilt angle to serve seated and standing operators.",
    importantParts: [
      "Medical-grade polycarbonate enclosure",
      "Antimicrobial textured surface treatment",
      "Flush-mounted 5″ capacitive touch panel",
      "Rubber-sealed connector bulkhead",
      "Integrated VESA / arm mount interface",
      "Internal cable routing channels",
    ],
    salientFeatures: [
      "IEC 60601 compliant form factor.",
      "Antimicrobial finish withstands repeated disinfection.",
      "Touch panel supports glove and stylus input.",
      "Cable management minimises clutter at point of care.",
      "30% faster diagnosis workflow in usability trials.",
      "Compliant with IEC 62366 usability engineering standard.",
    ],
    scopeOfWork: [
      "Human factors and use-environment research",
      "Industrial design and CMF specification",
      "3D CAD enclosure modelling",
      "Medical standards compliance review",
      "Prototype fabrication and usability evaluation",
      "Design-for-manufacture documentation",
    ],
  },
  {
    serialNumber: 3,
    id: "compact-edge-gateway-enclosure",
    title: "Compact Edge Gateway Enclosure",
    category: "Industrial Design",
    images: [
      "/case-studies/industrialCaseStudies/1/ENCLOSURE_ASSM_1.9.png",
      "/case-studies/industrialCaseStudies/1/ENCLOSURE_ASSM_1.10.png",
      "/case-studies/industrialCaseStudies/1/ENCLOSURE_ASSM_1.11.png",
    ],
    features: [
      "Fanless aluminium heatsink enclosure for passive cooling",
      "Compact form factor with multiple SMA antenna ports",
      "Integrated Ethernet (RJ45), USB, and M12 connectors",
      "Finned top cover for thermal management",
      "Industrial-grade aluminium construction",
      "Designed for edge computing and IoT gateway applications",
    ],
    summary:
      "A compact, fanless edge gateway enclosure designed for continuous industrial operation without active cooling. The finned aluminium top cover provides efficient passive heat dissipation, while the silver die-cast body houses multiple SMA antenna connectors, Ethernet, USB, and M12 industrial interfaces. The robust construction and thermal design make it suitable for deployment in harsh environments where reliability and silent operation are critical.",
    importantParts: [
      "Die-cast aluminium primary enclosure shell",
      "Finned heatsink top cover for passive cooling",
      "SMA antenna connector array",
      "RJ45 Ethernet and USB interface ports",
      "M12 industrial circular connector",
      "Internal PCB mounting and retention system",
    ],
    salientFeatures: [
      "Fanless passive cooling via finned heatsink top.",
      "Multiple SMA ports for multi-radio antenna support.",
      "Integrated Ethernet, USB, and M12 connectivity.",
      "Compact footprint for space-constrained deployments.",
      "Industrial-grade aluminium construction.",
      "Silent operation with no moving parts.",
    ],
    scopeOfWork: [
      "Industrial design concepting and form exploration",
      "Thermal management and heatsink design",
      "3D CAD enclosure modelling and detailing",
      "Connector panel layout and I/O planning",
      "Design-for-manufacture review",
      "Prototype build and thermal evaluation",
    ],
  },
  {
    serialNumber: 4,
    id: "medical-recording-device",
    title: "Medical Recording Device",
    category: "Industrial Design",
    images: [
      "/case-studies/industrialCaseStudies/2/LSR-1.png",
      "/case-studies/industrialCaseStudies/2/LSR-6.png",
      "/case-studies/industrialCaseStudies/2/LSR-7.png",
      "/case-studies/industrialCaseStudies/2/LSR-8.png",
      "/case-studies/industrialCaseStudies/2/LSR-9.png",
      "/case-studies/industrialCaseStudies/2/LSR-10.png",
      "/case-studies/industrialCaseStudies/2/LSR-11.png",
    ],
    features: [
      "Compact puck-shaped form factor for clinical use",
      "LSR (Liquid Silicone Rubber) overmould construction",
      "USB-C charging and data interface",
      "Integrated power button and status LED",
      "Medical-grade surface finish for easy sterilisation",
      "Designed for bedside recording and monitoring",
    ],
    summary:
      "A compact, puck-shaped medical recording device designed for clinical environments. The device features an LSR (Liquid Silicone Rubber) overmoulded enclosure that provides a soft, antimicrobial surface finish suitable for repeated sterilisation. The minimalist design includes a single power button, status LED, and USB-C interface, enabling bedside data recording with minimal clinician interaction. The low-profile form factor sits discreetly on any surface while maintaining a premium medical aesthetic.",
    importantParts: [
      "LSR (Liquid Silicone Rubber) overmoulded shell",
      "Medical-grade polycarbonate base plate",
      "USB-C charging and data port",
      "Tactile power button with LED indicator",
      "Anti-slip rubber base pad",
      "Internal PCB and battery retention cradle",
    ],
    salientFeatures: [
      "LSR overmould for antimicrobial surface properties.",
      "Compact puck form factor for unobtrusive placement.",
      "USB-C interface for charging and data transfer.",
      "Medical-grade finish for repeated wipe-down sterilisation.",
      "Single-button operation for clinical simplicity.",
      "Low-profile design for bedside deployment.",
    ],
    scopeOfWork: [
      "Industrial design and CMF specification",
      "LSR overmould tooling design",
      "3D CAD enclosure modelling",
      "Medical standards compliance review",
      "Prototype fabrication and usability evaluation",
      "Design-for-manufacture documentation",
    ],
  },
  {
    serialNumber: 5,
    id: "inline-moisture-meter",
    title: "Inline Moisture Meter",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.21.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.19.png",
    ],
    features: [
      "Continuous PPG and SpO₂ biometric sensing",
      "Low-profile wrist-worn enclosure under 11 mm thick",
      "Qi wireless inductive charging",
      "5-day battery life with always-on display mode",
      "Interchangeable silicone strap system",
      "IPX7 water-resistant construction",
    ],
    summary:
      "A compact wrist-worn health monitor designed for continuous patient monitoring in both clinical and home settings. The ultra-slim form factor conceals the sensor array and battery within an 11 mm profile. Industrial design focused on comfort-first strap geometry, a scratch-resistant mineral glass lens, and a wireless charging surface that is flush with the underside of the device for one-hand dock placement.",
    importantParts: [
      "Mineral glass display lens",
      "Aluminium mid-frame with integrated antenna keep-out",
      "Custom silicone strap with quick-release lug",
      "Optical PPG / SpO₂ sensor window",
      "Inductive charging coil housing",
      "Haptic feedback motor mount",
    ],
    salientFeatures: [
      "Sub-11 mm total thickness for all-day comfort.",
      "Continuous 72-hour biometric monitoring.",
      "Qi wireless charging — no exposed contacts.",
      "IPX7 rated for swimming and showering.",
      "Interchangeable strap system for clinical and consumer use.",
      "Scratch-resistant mineral glass lens.",
    ],
    scopeOfWork: [
      "Wearable concept design and CMF",
      "Ergonomic wrist-geometry study",
      "3D CAD and DFM for injection moulding",
      "Strap and clasp mechanism design",
      "Prototype build and fit evaluation",
      "IP rating compliance review",
    ],
  },
  {
    serialNumber: 6,
    id: "desktop-moisture-meter",
    title: "Desktop Moisture Meter",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.6.png",
    ],
    features: [
      "IP67 and MIL-STD-810G rated enclosure",
      "Transflective LCD for sunlight-readable operation",
      "Reinforced TPE over-mould drop protection",
      "Large tactile buttons operable with thick gloves",
      "3.6 Ah Li-Ion battery with hot-swap capability",
      "Integrated probe storage and belt-clip holster",
    ],
    summary:
      "A ruggedised portable tester for electrical field diagnostics, engineered to survive harsh outdoor and industrial environments. The reinforced over-mould body absorbs 1.8 m drop impacts while the transflective display remains readable in direct sunlight. The control layout was validated with field technicians to ensure all primary functions are accessible single-handed, with large glove-safe buttons and a recessed joystick navigation cluster.",
    importantParts: [
      "PC/ABS primary shell with integral stiffening ribs",
      "TPE 1.8 m drop-rated over-mould frame",
      "Transflective 3.5″ display with gorilla glass",
      "IP67-sealed probe and power port bay",
      "Hot-swap 3.6 Ah Li-Ion battery system",
      "Rubberised tactile dome keypad",
    ],
    salientFeatures: [
      "IP67 and MIL-STD-810G certified.",
      "1.8 m drop-test compliant.",
      "Transflective display readable in full sunlight.",
      "All functions accessible single-handed.",
      "Hot-swap battery for uninterrupted field operation.",
      "Integrated test-lead storage reduces accessory loss.",
    ],
    scopeOfWork: [
      "Ruggedised industrial design concepting",
      "Drop and ingress protection engineering",
      "3D CAD surfacing and assembly modelling",
      "Field-technician usability study",
      "Prototype drop and environmental testing",
      "MIL-STD compliance documentation",
    ],
  },
  {
    serialNumber: 1,
    id: "uv-disinfection-system",
    title: "UV Disinfection System",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER__1.0.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER__3.2.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_4.17.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_TOP_ISO_1.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_BOTTOM_ISO_1.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_LEFT.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_RIGHT.png",
    ],
    features: [
      "Wall-mounted UV-C disinfection unit",
      "Triple UV lamp array for wide-area coverage",
      "Sleek white and silver two-tone enclosure",
      "Integrated occupancy and ambient light sensors",
      "Sealed lamp windows for safe UV containment",
      "Designed for healthcare and commercial spaces",
    ],
    summary:
      "A wall-mounted UV disinfection system branded SafeSpaceUV, engineered for continuous air and surface sanitisation in healthcare, commercial, and public environments. The enclosure houses a triple UV-C lamp array behind sealed optical windows, delivering broad-area coverage while containing UV radiation safely. The two-tone white and silver finish blends into modern interiors, while the wall-mount design keeps floor space free and positions the unit at optimal height for effective disinfection.",
    importantParts: [
      "UV-C lamp modules with sealed optical windows",
      "Two-tone ABS / polycarbonate enclosure shell",
      "Wall-mount bracket and retention system",
      "Integrated occupancy sensor module",
      "Internal reflector array for UV distribution",
      "Thermal management and airflow channels",
    ],
    salientFeatures: [
      "Triple UV-C lamp array for wide-area disinfection.",
      "Sealed optical windows for safe UV containment.",
      "Wall-mount design for optimal positioning.",
      "Two-tone premium finish for modern interiors.",
      "Integrated sensors for automated operation.",
      "DFM-reviewed geometry for production readiness.",
    ],
    scopeOfWork: [
      "Concept ideation and form factor exploration",
      "3D CAD enclosure modelling and detailing",
      "UV optics and reflector design",
      "Thermal management analysis",
      "Wall-mount bracket engineering",
      "Design-for-manufacture review",
      "Prototype build and fit evaluation",
    ],
  },
];
