import { CaseStudy } from "../../types/case-study";

// ─── Industrial Design ────────────────────────────────────────────────────────
export const industrialCaseStudiesData: CaseStudy[] = [
  {
    id: "handheld-industrial-controller",
    title: "Handheld Industrial Controller",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/5.png",
    ],
    features: [
      "Handheld controller enclosure optimised for factory floor use",
      "Balanced grip ergonomics for long-duration operation",
      "IP54-rated sealed I/O ports and robust mounting points",
      "Split-housing concept aligned to DFM and assembly feasibility",
      "Tactile button layout with glove-friendly actuation force",
      "ABS / TPE over-mould construction",
    ],
    summary:
      "An industrial design study focused on a handheld automation controller built for demanding shop-floor environments. The concept prioritises operator comfort, clear visual hierarchy on the front face, and manufacturable geometry so the product can move from concept to pilot production with minimal redesign. The split-housing strategy enables straightforward assembly and in-field serviceability.",
    importantParts: [
      "Impact-resistant ABS primary shell",
      "TPE over-mould grip zones",
      "Sealed membrane keypad with tactile dome switches",
      "Integrated lanyard lug and belt-clip boss",
      "Snap-fit PCB retention system",
      "Colour-coded I/O port surround",
    ],
    salientFeatures: [
      "Rugged visual language suited to industrial settings.",
      "Improved hand feel and confident grip geometry.",
      "Clear front-face interaction zones reduce operator errors.",
      "IP54 rated enclosure resists dust and splash.",
      "DFM-reviewed design ready for tooling transition.",
      "Service-accessible battery and PCB compartment.",
    ],
    scopeOfWork: [
      "Industrial design concepting and ideation",
      "Form exploration and refinement",
      "3D CAD surfacing and detailing",
      "Design-for-manufacture review",
      "Prototype build and ergonomics evaluation",
    ],
  },
  {
    id: "medical-diagnostic-system",
    title: "Medical Diagnostic System",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/rettina_scanner/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/rettina_scanner/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/rettina_scanner/3.png",
    ],
    features: [
      "IEC 60601-compliant enclosure design",
      "Antimicrobial surface finish for clinical environments",
      "5-inch capacitive touch display with glove-mode support",
      "User-centred control layout validated through HF testing",
      "Cable management and mounting arm compatibility",
      "Designed for sterilisation wipe-down procedures",
    ],
    summary:
      "A user-centred medical diagnostic device concept developed to improve diagnostic workflow speed and reduce clinician cognitive load. The enclosure features a clean, uncluttered visual language, an intuitive control hierarchy, and geometry that supports routine sterile wipe-down protocols. Human factors testing informed button placement and screen tilt angle to serve seated and standing operators.",
    importantParts: [
      "Medical-grade polycarbonate enclosure",
      "Antimicrobial textured surface treatment",
      "Flush-mounted 5″ capacitive touch panel",
      "Rubber-sealed connector bulkhead",
      "Integrated VESA / arm mount interface",
      "Internal cable routing channels",
    ],
    salientFeatures: [
      "IEC 60601 compliant form factor.",
      "Antimicrobial finish withstands repeated disinfection.",
      "Touch panel supports glove and stylus input.",
      "Cable management minimises clutter at point of care.",
      "30% faster diagnosis workflow in usability trials.",
      "Compliant with IEC 62366 usability engineering standard.",
    ],
    scopeOfWork: [
      "Human factors and use-environment research",
      "Industrial design and CMF specification",
      "3D CAD enclosure modelling",
      "Medical standards compliance review",
      "Prototype fabrication and usability evaluation",
      "Design-for-manufacture documentation",
    ],
  },
  {
    id: "compact-edge-gateway-enclosure",
    title: "Compact Edge Gateway Enclosure",
    category: "Industrial Design",
    images: [
      "/case-studies/industrialCaseStudies/1/ENCLOSURE_ASSM_1.9.png",
      "/case-studies/industrialCaseStudies/1/ENCLOSURE_ASSM_1.10.png",
      "/case-studies/industrialCaseStudies/1/ENCLOSURE_ASSM_1.11.png",
    ],
    features: [
      "Fanless aluminium heatsink enclosure for passive cooling",
      "Compact form factor with multiple SMA antenna ports",
      "Integrated Ethernet (RJ45), USB, and M12 connectors",
      "Finned top cover for thermal management",
      "Industrial-grade aluminium construction",
      "Designed for edge computing and IoT gateway applications",
    ],
    summary:
      "A compact, fanless edge gateway enclosure designed for continuous industrial operation without active cooling. The finned aluminium top cover provides efficient passive heat dissipation, while the silver die-cast body houses multiple SMA antenna connectors, Ethernet, USB, and M12 industrial interfaces. The robust construction and thermal design make it suitable for deployment in harsh environments where reliability and silent operation are critical.",
    importantParts: [
      "Die-cast aluminium primary enclosure shell",
      "Finned heatsink top cover for passive cooling",
      "SMA antenna connector array",
      "RJ45 Ethernet and USB interface ports",
      "M12 industrial circular connector",
      "Internal PCB mounting and retention system",
    ],
    salientFeatures: [
      "Fanless passive cooling via finned heatsink top.",
      "Multiple SMA ports for multi-radio antenna support.",
      "Integrated Ethernet, USB, and M12 connectivity.",
      "Compact footprint for space-constrained deployments.",
      "Industrial-grade aluminium construction.",
      "Silent operation with no moving parts.",
    ],
    scopeOfWork: [
      "Industrial design concepting and form exploration",
      "Thermal management and heatsink design",
      "3D CAD enclosure modelling and detailing",
      "Connector panel layout and I/O planning",
      "Design-for-manufacture review",
      "Prototype build and thermal evaluation",
    ],
  },
  {
    id: "medical-recording-device",
    title: "Medical Recording Device",
    category: "Industrial Design",
    images: [
      "/case-studies/industrialCaseStudies/2/LSR-1.png",
      "/case-studies/industrialCaseStudies/2/LSR-6.png",
      "/case-studies/industrialCaseStudies/2/LSR-7.png",
      "/case-studies/industrialCaseStudies/2/LSR-8.png",
      "/case-studies/industrialCaseStudies/2/LSR-9.png",
      "/case-studies/industrialCaseStudies/2/LSR-10.png",
      "/case-studies/industrialCaseStudies/2/LSR-11.png",
    ],
    features: [
      "Compact puck-shaped form factor for clinical use",
      "LSR (Liquid Silicone Rubber) overmould construction",
      "USB-C charging and data interface",
      "Integrated power button and status LED",
      "Medical-grade surface finish for easy sterilisation",
      "Designed for bedside recording and monitoring",
    ],
    summary:
      "A compact, puck-shaped medical recording device designed for clinical environments. The device features an LSR (Liquid Silicone Rubber) overmoulded enclosure that provides a soft, antimicrobial surface finish suitable for repeated sterilisation. The minimalist design includes a single power button, status LED, and USB-C interface, enabling bedside data recording with minimal clinician interaction. The low-profile form factor sits discreetly on any surface while maintaining a premium medical aesthetic.",
    importantParts: [
      "LSR (Liquid Silicone Rubber) overmoulded shell",
      "Medical-grade polycarbonate base plate",
      "USB-C charging and data port",
      "Tactile power button with LED indicator",
      "Anti-slip rubber base pad",
      "Internal PCB and battery retention cradle",
    ],
    salientFeatures: [
      "LSR overmould for antimicrobial surface properties.",
      "Compact puck form factor for unobtrusive placement.",
      "USB-C interface for charging and data transfer.",
      "Medical-grade finish for repeated wipe-down sterilisation.",
      "Single-button operation for clinical simplicity.",
      "Low-profile design for bedside deployment.",
    ],
    scopeOfWork: [
      "Industrial design and CMF specification",
      "LSR overmould tooling design",
      "3D CAD enclosure modelling",
      "Medical standards compliance review",
      "Prototype fabrication and usability evaluation",
      "Design-for-manufacture documentation",
    ],
  },
  {
    id: "wearable-health-monitor",
    title: "Wearable Health Monitor",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.21.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.19.png",
    ],
    features: [
      "Continuous PPG and SpO₂ biometric sensing",
      "Low-profile wrist-worn enclosure under 11 mm thick",
      "Qi wireless inductive charging",
      "5-day battery life with always-on display mode",
      "Interchangeable silicone strap system",
      "IPX7 water-resistant construction",
    ],
    summary:
      "A compact wrist-worn health monitor designed for continuous patient monitoring in both clinical and home settings. The ultra-slim form factor conceals the sensor array and battery within an 11 mm profile. Industrial design focused on comfort-first strap geometry, a scratch-resistant mineral glass lens, and a wireless charging surface that is flush with the underside of the device for one-hand dock placement.",
    importantParts: [
      "Mineral glass display lens",
      "Aluminium mid-frame with integrated antenna keep-out",
      "Custom silicone strap with quick-release lug",
      "Optical PPG / SpO₂ sensor window",
      "Inductive charging coil housing",
      "Haptic feedback motor mount",
    ],
    salientFeatures: [
      "Sub-11 mm total thickness for all-day comfort.",
      "Continuous 72-hour biometric monitoring.",
      "Qi wireless charging — no exposed contacts.",
      "IPX7 rated for swimming and showering.",
      "Interchangeable strap system for clinical and consumer use.",
      "Scratch-resistant mineral glass lens.",
    ],
    scopeOfWork: [
      "Wearable concept design and CMF",
      "Ergonomic wrist-geometry study",
      "3D CAD and DFM for injection moulding",
      "Strap and clasp mechanism design",
      "Prototype build and fit evaluation",
      "IP rating compliance review",
    ],
  },
  {
    id: "portable-field-tester",
    title: "Portable Field Tester",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.6.png",
    ],
    features: [
      "IP67 and MIL-STD-810G rated enclosure",
      "Transflective LCD for sunlight-readable operation",
      "Reinforced TPE over-mould drop protection",
      "Large tactile buttons operable with thick gloves",
      "3.6 Ah Li-Ion battery with hot-swap capability",
      "Integrated probe storage and belt-clip holster",
    ],
    summary:
      "A ruggedised portable tester for electrical field diagnostics, engineered to survive harsh outdoor and industrial environments. The reinforced over-mould body absorbs 1.8 m drop impacts while the transflective display remains readable in direct sunlight. The control layout was validated with field technicians to ensure all primary functions are accessible single-handed, with large glove-safe buttons and a recessed joystick navigation cluster.",
    importantParts: [
      "PC/ABS primary shell with integral stiffening ribs",
      "TPE 1.8 m drop-rated over-mould frame",
      "Transflective 3.5″ display with gorilla glass",
      "IP67-sealed probe and power port bay",
      "Hot-swap 3.6 Ah Li-Ion battery system",
      "Rubberised tactile dome keypad",
    ],
    salientFeatures: [
      "IP67 and MIL-STD-810G certified.",
      "1.8 m drop-test compliant.",
      "Transflective display readable in full sunlight.",
      "All functions accessible single-handed.",
      "Hot-swap battery for uninterrupted field operation.",
      "Integrated test-lead storage reduces accessory loss.",
    ],
    scopeOfWork: [
      "Ruggedised industrial design concepting",
      "Drop and ingress protection engineering",
      "3D CAD surfacing and assembly modelling",
      "Field-technician usability study",
      "Prototype drop and environmental testing",
      "MIL-STD compliance documentation",
    ],
  },
  // {
  //   id: "smart-home-controller",
  //   title: "Smart Home Controller",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Wall-mount and in-panel installation in under 5 minutes",
  //     "Full-surface capacitive touch with haptic feedback",
  //     "Integrated ambient LED ring with 16M colour support",
  //     "Wi-Fi 6 and Zigbee 3.0 dual-radio connectivity",
  //     "Premium matte-white and brushed-aluminium CMF",
  //     "Snap-in clip system with no visible fasteners",
  //   ],
  //   summary:
  //     "A minimalist wall-mount smart home hub designed to blend into premium interior spaces while delivering whole-home control. The frameless full-surface capacitive touch panel eliminates visible buttons, and the integrated ambient LED ring provides status feedback without interrupting the clean aesthetic. The flush snap-in installation system requires no visible screws and takes under five minutes to mount into a standard back-box.",
  //   importantParts: [
  //     "Tempered glass front panel with AR coating",
  //     "Aluminium accent bezel with brushed finish",
  //     "Full-surface PCAP touch controller",
  //     "Integrated LED ring diffuser",
  //     "Snap-in wall-mount retention clip assembly",
  //     "Thermal management back-plate",
  //   ],
  //   salientFeatures: [
  //     "Zero visible fasteners — seamless flush-mount finish.",
  //     "Full-surface touch panel with glove and stylus support.",
  //     "Ambient LED ring with 16M colour zones.",
  //     "Wi-Fi 6 and Zigbee 3.0 simultaneous operation.",
  //     "Under 5-minute installation into standard back-box.",
  //     "Premium matte-white and brushed-aluminium CMF.",
  //   ],
  //   scopeOfWork: [
  //     "Premium CMF and brand language development",
  //     "Enclosure industrial design and 3D CAD",
  //     "Snap-in mount mechanism design",
  //     "LED diffuser optics study",
  //     "Pre-production prototype review",
  //     "Design-for-manufacture and tooling handoff",
  //   ],
  // },
  // {
  //   id: "capes-cell-sensor",
  //   title: "CAPES Cell Sensor",
  //   category: "Medical Device Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Advanced Cell Analysis Technology",
  //     "Real-time Sensor Integration",
  //     "High-precision Measurement",
  //     "Medical-grade Certification",
  //     "Data Acquisition and Processing",
  //     "Portable Design",
  //   ],
  //   summary:
  //     "A sophisticated cell sensing device designed for advanced medical diagnostics and research applications. The CAPES Cell Sensor combines precision measurement technology with real-time data acquisition to enable comprehensive cellular analysis. Built with medical-grade components and rigorous quality standards, the device delivers reliable results in clinical and laboratory environments.",
  //   importantParts: [
  //     "High-precision sensor array",
  //     "Real-time data acquisition circuitry",
  //     "Medical-grade connectors and enclosure",
  //     "Advanced signal conditioning electronics",
  //     "Microcontroller-based processing unit",
  //     "Isolated power supply for noise immunity",
  //   ],
  //   salientFeatures: [
  //     "Real-time cellular measurement and analysis.",
  //     "High-precision sensor array for accurate diagnostics.",
  //     "Medical-grade component selection and certification.",
  //     "Compact portable form factor.",
  //     "Data logging and wireless transmission capability.",
  //     "Integrated calibration and quality assurance.",
  //     "Low power consumption for extended operation.",
  //   ],
  //   scopeOfWork: [
  //     "System Architecture Design",
  //     "Hardware Design and Development",
  //     "PCB Layout and Design",
  //     "Firmware Development",
  //     "Sensor Integration and Calibration",
  //     "Testing and Validation",
  //     "Medical Compliance and Certification",
  //     "Enclosure and Industrial Design",
  //   ],
  // },
  // {
  //   id: "industrial-hmi-touch-panel",
  //   title: "Industrial HMI Touch Panel",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Flush-mount operator panel for machine control cabinets",
  //     "10-inch capacitive touch display with glove support",
  //     "Powder-coated aluminium front bezel",
  //     "Sealed gasket interface for dusty environments",
  //     "Rear cable routing and strain relief",
  //     "Service-friendly modular internal layout",
  //   ],
  //   summary:
  //     "A dummy industrial design case study for a rugged HMI touch panel intended for machine control and plant-floor monitoring. The concept focuses on a clean front interface, resilient mounting details, and simplified service access for maintenance teams.",
  //   importantParts: [
  //     "Powder-coated aluminium bezel",
  //     "Capacitive touch display module",
  //     "EPDM cabinet sealing gasket",
  //     "Rear service cover",
  //     "Cable strain relief bracket",
  //     "Internal PCB mounting frame",
  //   ],
  //   salientFeatures: [
  //     "Glove-friendly touch interface.",
  //     "Flush cabinet installation.",
  //     "Sealed front face for dusty areas.",
  //     "Tool-accessible rear service panel.",
  //     "Industrial CMF suitable for control rooms.",
  //   ],
  //   scopeOfWork: [
  //     "Industrial design concepting",
  //     "Display and bezel integration",
  //     "Mounting detail development",
  //     "3D CAD enclosure modelling",
  //     "Prototype review",
  //   ],
  // },
  // {
  //   id: "railway-diagnostic-handset",
  //   title: "Railway Diagnostic Handset",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Rugged handheld form factor for trackside inspection",
  //     "High-visibility colour accents for field use",
  //     "Weather-sealed connector bay",
  //     "Large tactile keypad for outdoor operation",
  //     "Integrated wrist strap and drop protection",
  //     "Sunlight-readable display recess",
  //   ],
  //   summary:
  //     "A dummy concept for a portable railway diagnostic handset used during field inspection and maintenance. The design balances impact protection, quick handling, and clear interaction hierarchy for outdoor service teams.",
  //   importantParts: [
  //     "PC/ABS main enclosure",
  //     "TPE corner protection",
  //     "Sealed connector door",
  //     "Tactile keypad assembly",
  //     "Wrist strap anchor",
  //     "Recessed display lens",
  //   ],
  //   salientFeatures: [
  //     "High grip security in wet conditions.",
  //     "Protected connectors for outdoor diagnostics.",
  //     "Large buttons reduce field input errors.",
  //     "Bright colour accents support fast identification.",
  //     "Drop-resistant enclosure architecture.",
  //   ],
  //   scopeOfWork: [
  //     "Field-use research",
  //     "Form factor exploration",
  //     "Rugged enclosure design",
  //     "Keypad layout development",
  //     "Prototype ergonomics testing",
  //   ],
  // },
  // {
  //   id: "smart-energy-meter-enclosure",
  //   title: "Smart Energy Meter Enclosure",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Compact wall-mounted meter enclosure",
  //     "Transparent inspection window",
  //     "Tamper-evident screw covers",
  //     "Ventilated internal electronics chamber",
  //     "DIN rail and wall-mount compatibility",
  //     "Utility-grade moulded plastic construction",
  //   ],
  //   summary:
  //     "A dummy industrial design study for a smart energy meter enclosure designed for utility and facility management applications. The enclosure prioritises secure access, readable status visibility, and straightforward installation.",
  //   importantParts: [
  //     "UV-stable polycarbonate cover",
  //     "Transparent inspection window",
  //     "Tamper-evident fastener caps",
  //     "DIN rail mounting clip",
  //     "Cable entry knockouts",
  //     "Ventilated electronics bay",
  //   ],
  //   salientFeatures: [
  //     "Tamper-aware external detailing.",
  //     "Clear status visibility through inspection window.",
  //     "Flexible wall or DIN rail mounting.",
  //     "Cable knockouts support varied installation layouts.",
  //     "Mould-ready enclosure split strategy.",
  //   ],
  //   scopeOfWork: [
  //     "Enclosure architecture",
  //     "Mounting strategy design",
  //     "Tamper feature development",
  //     "3D CAD detailing",
  //     "DFM review",
  //   ],
  // },
  // {
  //   id: "warehouse-scanner-dock",
  //   title: "Warehouse Scanner Dock",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Desktop and wall-mount charging dock",
  //     "One-handed scanner insertion geometry",
  //     "Replaceable pogo-pin charging module",
  //     "Weighted anti-slip base",
  //     "LED charge status light pipe",
  //     "Cable exit channels for tidy workstations",
  //   ],
  //   summary:
  //     "A dummy product design case study for a charging dock used with warehouse barcode scanners. The concept improves daily usability with guided docking geometry, durable charging contacts, and a compact footprint for busy packing stations.",
  //   importantParts: [
  //     "Injection-moulded dock body",
  //     "Replaceable pogo-pin module",
  //     "LED light pipe",
  //     "Anti-slip rubber base",
  //     "Wall-mount screw slots",
  //     "Cable management channels",
  //   ],
  //   salientFeatures: [
  //     "One-handed docking reduces handling time.",
  //     "Replaceable contacts extend service life.",
  //     "Desktop and wall installation supported.",
  //     "Charge status visible from the operator position.",
  //     "Cable routing keeps workstations cleaner.",
  //   ],
  //   scopeOfWork: [
  //     "Use-case observation",
  //     "Docking geometry design",
  //     "Charging module integration",
  //     "Prototype fit testing",
  //     "Manufacturing documentation",
  //   ],
  // },
  // {
  //   id: "industrial-safety-beacon",
  //   title: "Industrial Safety Beacon",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Stackable visual alert beacon for factory equipment",
  //     "360-degree translucent lens geometry",
  //     "Twist-lock modular assembly",
  //     "Surface and pole-mount options",
  //     "Weather-resistant gasketed construction",
  //     "High-contrast base for industrial visibility",
  //   ],
  //   summary:
  //     "A dummy case study for a modular industrial safety beacon used on automated machinery and production cells. The design explores clear visibility, quick assembly, and durable mounting options for plant-floor deployment.",
  //   importantParts: [
  //     "Translucent polycarbonate lens",
  //     "Twist-lock module interface",
  //     "Gasketed base housing",
  //     "Pole-mount adaptor",
  //     "LED board support frame",
  //     "Cable gland entry",
  //   ],
  //   salientFeatures: [
  //     "360-degree signal visibility.",
  //     "Modular stackable construction.",
  //     "Fast twist-lock assembly.",
  //     "Multiple mounting configurations.",
  //     "Weather-resistant industrial housing.",
  //   ],
  //   scopeOfWork: [
  //     "Signal visibility study",
  //     "Modular housing design",
  //     "Lens and diffuser development",
  //     "Mounting accessory design",
  //     "Prototype validation",
  //   ],
  // },
  // {
  //   id: "agri-sensor-node",
  //   title: "Agri Sensor Node",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Outdoor sensor enclosure for farm monitoring",
  //     "Solar panel integration on angled top surface",
  //     "Stake and pole mounting support",
  //     "Breathable membrane vent for pressure equalisation",
  //     "Protected sensor window and cable glands",
  //     "Low-cost injection-moulded housing strategy",
  //   ],
  //   summary:
  //     "A dummy industrial design case study for an outdoor agriculture sensor node. The enclosure is shaped for solar exposure, weather protection, and quick installation across crop fields and remote monitoring points.",
  //   importantParts: [
  //     "UV-resistant enclosure shell",
  //     "Integrated solar panel recess",
  //     "Sensor window cover",
  //     "Cable gland ports",
  //     "Pole-mount bracket",
  //     "Pressure equalisation vent",
  //   ],
  //   salientFeatures: [
  //     "Solar-ready enclosure surface.",
  //     "Outdoor-rated sensor protection.",
  //     "Fast field mounting with stake or pole.",
  //     "Vent manages pressure and condensation.",
  //     "Cost-conscious moulded housing design.",
  //   ],
  //   scopeOfWork: [
  //     "Outdoor product concepting",
  //     "Solar panel packaging",
  //     "Mounting accessory design",
  //     "Ingress protection detailing",
  //     "Prototype field review",
  //   ],
  // },
  // {
  //   id: "factory-router-enclosure",
  //   title: "Factory Router Enclosure",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "DIN rail industrial networking enclosure",
  //     "Passive ventilation and heat-spreading features",
  //     "Front-facing Ethernet and power access",
  //     "Antenna-ready side walls",
  //     "Status LED light-pipe array",
  //     "Compact service label zone",
  //   ],
  //   summary:
  //     "A dummy case study for a factory router enclosure designed for networking panels and automation cabinets. The concept organises connectors, antennas, and status feedback into a compact housing suitable for repeated installation.",
  //   importantParts: [
  //     "DIN rail clip",
  //     "Vented enclosure body",
  //     "LED light-pipe strip",
  //     "Antenna port bosses",
  //     "Front connector panel",
  //     "Internal heat spreader",
  //   ],
  //   salientFeatures: [
  //     "DIN rail mounting for cabinet installation.",
  //     "Clear front I/O access.",
  //     "Passive thermal design.",
  //     "Antenna-ready enclosure layout.",
  //     "Readable status indication in dense panels.",
  //   ],
  //   scopeOfWork: [
  //     "Networking enclosure concept",
  //     "Connector layout planning",
  //     "Thermal feature design",
  //     "CAD assembly modelling",
  //     "DFM support",
  //   ],
  // },
  // {
  //   id: "lab-centrifuge-control-module",
  //   title: "Lab Centrifuge Control Module",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Angled control module for benchtop lab equipment",
  //     "Chemical-resistant front overlay",
  //     "Rotary encoder and membrane-key interface",
  //     "Recessed display for glare reduction",
  //     "Hidden fasteners for clean lab aesthetic",
  //     "Serviceable rear electronics cassette",
  //   ],
  //   summary:
  //     "A dummy industrial design case study for a control module used on benchtop laboratory centrifuges. The design improves operator visibility, wipe-down cleaning, and service access while maintaining a precise laboratory product language.",
  //   importantParts: [
  //     "Angled front housing",
  //     "Chemical-resistant overlay",
  //     "Rotary encoder knob",
  //     "Membrane keypad",
  //     "Recessed display lens",
  //     "Rear electronics cassette",
  //   ],
  //   salientFeatures: [
  //     "Angled interface supports standing operation.",
  //     "Wipe-clean front surface.",
  //     "Reduced display glare.",
  //     "Hidden fasteners create a clean lab appearance.",
  //     "Rear cassette simplifies service access.",
  //   ],
  //   scopeOfWork: [
  //     "Lab workflow research",
  //     "Interface layout design",
  //     "CMF specification",
  //     "Enclosure CAD modelling",
  //     "Prototype usability review",
  //   ],
  // },
  // {
  //   id: "ev-charger-pedestal",
  //   title: "EV Charger Pedestal",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Public charging pedestal enclosure",
  //     "Cable holster and connector parking feature",
  //     "Vandal-resistant metal outer body",
  //     "Readable payment and status interface zone",
  //     "Service door with concealed hinge",
  //     "Weather-protected cable exit geometry",
  //   ],
  //   summary:
  //     "A dummy industrial design case study for a public EV charger pedestal. The concept focuses on durable urban deployment, intuitive cable handling, and a clean service architecture for installation and maintenance teams.",
  //   importantParts: [
  //     "Powder-coated metal pedestal body",
  //     "Connector holster",
  //     "Status display window",
  //     "Concealed service hinge",
  //     "Cable exit guide",
  //     "Foundation mounting plate",
  //   ],
  //   salientFeatures: [
  //     "Durable metal body for public spaces.",
  //     "Integrated cable parking reduces clutter.",
  //     "Clear user interface zone.",
  //     "Service access separated from user touchpoints.",
  //     "Weather-protected cable routing.",
  //   ],
  //   scopeOfWork: [
  //     "Public product design concept",
  //     "Cable management development",
  //     "Sheet-metal enclosure design",
  //     "Service access planning",
  //     "Prototype review",
  //   ],
  // },
  // {
  //   id: "cold-chain-tracker",
  //   title: "Cold Chain Tracker",
  //   category: "Industrial Design",
  //   images: ["/case-studies/image_vacationing.png"],
  //   features: [
  //     "Compact tracker for refrigerated logistics",
  //     "Clip-on and adhesive mounting options",
  //     "Large status indicator for quick inspection",
  //     "Low-temperature material selection",
  //     "Sealed USB-C service port",
  //     "Rounded form for packaging compatibility",
  //   ],
  //   summary:
  //     "A dummy product design case study for a cold chain tracking device used on refrigerated shipments and storage containers. The enclosure supports quick attachment, easy visual inspection, and reliable operation in low-temperature environments.",
  //   importantParts: [
  //     "Low-temperature rated housing",
  //     "Clip-on mounting bracket",
  //     "Adhesive pad interface",
  //     "Large status LED diffuser",
  //     "Sealed USB-C cover",
  //     "Internal battery cradle",
  //   ],
  //   salientFeatures: [
  //     "Flexible clip or adhesive mounting.",
  //     "High-visibility status feedback.",
  //     "Material selection suited to cold environments.",
  //     "Sealed service port.",
  //     "Packaging-friendly rounded enclosure.",
  //   ],
  //   scopeOfWork: [
  //     "Logistics product concepting",
  //     "Mounting accessory design",
  //     "Low-temperature material review",
  //     "3D CAD detailing",
  //     "Prototype handling test",
  //   ],
  // },
];
