import { CaseStudy } from "../../types/case-study";

// ─── Industrial Design ────────────────────────────────────────────────────────
export const industrialCaseStudiesData: CaseStudy[] = [
  {
    serialNumber: 1,
    id: "oxygen-generator",
    title: "Oxygen Generator",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/oxygen_concentrator/5.png",
    ],
    features: [
      "Handheld controller enclosure optimised for factory floor use",
      "Balanced grip ergonomics for long-duration operation",
      "IP54-rated sealed I/O ports and robust mounting points",
      "Split-housing concept aligned to DFM and assembly feasibility",
      "Tactile button layout with glove-friendly actuation force",
      "ABS / TPE over-mould construction",
    ],
    summary:
      "An industrial design study focused on a handheld automation controller built for demanding shop-floor environments. The concept prioritises operator comfort, clear visual hierarchy on the front face, and manufacturable geometry so the product can move from concept to pilot production with minimal redesign. The split-housing strategy enables straightforward assembly and in-field serviceability.",
    importantParts: [
      "Impact-resistant ABS primary shell",
      "TPE over-mould grip zones",
      "Sealed membrane keypad with tactile dome switches",
      "Integrated lanyard lug and belt-clip boss",
      "Snap-fit PCB retention system",
      "Colour-coded I/O port surround",
    ],
    salientFeatures: [
      "Rugged visual language suited to industrial settings.",
      "Improved hand feel and confident grip geometry.",
      "Clear front-face interaction zones reduce operator errors.",
      "IP54 rated enclosure resists dust and splash.",
      "DFM-reviewed design ready for tooling transition.",
      "Service-accessible battery and PCB compartment.",
    ],
    scopeOfWork: [
      "Industrial design concepting and ideation",
      "Form exploration and refinement",
      "3D CAD surfacing and detailing",
      "Design-for-manufacture review",
      "Prototype build and ergonomics evaluation",
    ],
  },
  {
    serialNumber: 2,
    id: "medical-diagnostic-system",
    title: "Medical Diagnostic System",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/rettina_scanner/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/rettina_scanner/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/rettina_scanner/3.png",
    ],
    features: [
      "IEC 60601-compliant enclosure design",
      "Antimicrobial surface finish for clinical environments",
      "5-inch capacitive touch display with glove-mode support",
      "User-centred control layout validated through HF testing",
      "Cable management and mounting arm compatibility",
      "Designed for sterilisation wipe-down procedures",
    ],
    summary:
      "A user-centred medical diagnostic device concept developed to improve diagnostic workflow speed and reduce clinician cognitive load. The enclosure features a clean, uncluttered visual language, an intuitive control hierarchy, and geometry that supports routine sterile wipe-down protocols. Human factors testing informed button placement and screen tilt angle to serve seated and standing operators.",
    importantParts: [
      "Medical-grade polycarbonate enclosure",
      "Antimicrobial textured surface treatment",
      "Flush-mounted 5″ capacitive touch panel",
      "Rubber-sealed connector bulkhead",
      "Integrated VESA / arm mount interface",
      "Internal cable routing channels",
    ],
    salientFeatures: [
      "IEC 60601 compliant form factor.",
      "Antimicrobial finish withstands repeated disinfection.",
      "Touch panel supports glove and stylus input.",
      "Cable management minimises clutter at point of care.",
      "30% faster diagnosis workflow in usability trials.",
      "Compliant with IEC 62366 usability engineering standard.",
    ],
    scopeOfWork: [
      "Human factors and use-environment research",
      "Industrial design and CMF specification",
      "3D CAD enclosure modelling",
      "Medical standards compliance review",
      "Prototype fabrication and usability evaluation",
      "Design-for-manufacture documentation",
    ],
  },
  {
    serialNumber: 3,
    id: "compact-edge-gateway-enclosure",
    title: "Compact Edge Gateway Enclosure",
    category: "Industrial Design",
    images: [
      "/case-studies/industrialCaseStudies/1/ENCLOSURE_ASSM_1.9.png",
      "/case-studies/industrialCaseStudies/1/ENCLOSURE_ASSM_1.10.png",
      "/case-studies/industrialCaseStudies/1/ENCLOSURE_ASSM_1.11.png",
    ],
    features: [
      "Fanless aluminium heatsink enclosure for passive cooling",
      "Compact form factor with multiple SMA antenna ports",
      "Integrated Ethernet (RJ45), USB, and M12 connectors",
      "Finned top cover for thermal management",
      "Industrial-grade aluminium construction",
      "Designed for edge computing and IoT gateway applications",
    ],
    summary:
      "A compact, fanless edge gateway enclosure designed for continuous industrial operation without active cooling. The finned aluminium top cover provides efficient passive heat dissipation, while the silver die-cast body houses multiple SMA antenna connectors, Ethernet, USB, and M12 industrial interfaces. The robust construction and thermal design make it suitable for deployment in harsh environments where reliability and silent operation are critical.",
    importantParts: [
      "Die-cast aluminium primary enclosure shell",
      "Finned heatsink top cover for passive cooling",
      "SMA antenna connector array",
      "RJ45 Ethernet and USB interface ports",
      "M12 industrial circular connector",
      "Internal PCB mounting and retention system",
    ],
    salientFeatures: [
      "Fanless passive cooling via finned heatsink top.",
      "Multiple SMA ports for multi-radio antenna support.",
      "Integrated Ethernet, USB, and M12 connectivity.",
      "Compact footprint for space-constrained deployments.",
      "Industrial-grade aluminium construction.",
      "Silent operation with no moving parts.",
    ],
    scopeOfWork: [
      "Industrial design concepting and form exploration",
      "Thermal management and heatsink design",
      "3D CAD enclosure modelling and detailing",
      "Connector panel layout and I/O planning",
      "Design-for-manufacture review",
      "Prototype build and thermal evaluation",
    ],
  },
  {
    serialNumber: 4,
    id: "medical-recording-device",
    title: "Medical Recording Device",
    category: "Industrial Design",
    images: [
      "/case-studies/industrialCaseStudies/2/LSR-1.png",
      "/case-studies/industrialCaseStudies/2/LSR-6.png",
      "/case-studies/industrialCaseStudies/2/LSR-7.png",
      "/case-studies/industrialCaseStudies/2/LSR-8.png",
      "/case-studies/industrialCaseStudies/2/LSR-9.png",
      "/case-studies/industrialCaseStudies/2/LSR-10.png",
      "/case-studies/industrialCaseStudies/2/LSR-11.png",
    ],
    features: [
      "Compact puck-shaped form factor for clinical use",
      "LSR (Liquid Silicone Rubber) overmould construction",
      "USB-C charging and data interface",
      "Integrated power button and status LED",
      "Medical-grade surface finish for easy sterilisation",
      "Designed for bedside recording and monitoring",
    ],
    summary:
      "A compact, puck-shaped medical recording device designed for clinical environments. The device features an LSR (Liquid Silicone Rubber) overmoulded enclosure that provides a soft, antimicrobial surface finish suitable for repeated sterilisation. The minimalist design includes a single power button, status LED, and USB-C interface, enabling bedside data recording with minimal clinician interaction. The low-profile form factor sits discreetly on any surface while maintaining a premium medical aesthetic.",
    importantParts: [
      "LSR (Liquid Silicone Rubber) overmoulded shell",
      "Medical-grade polycarbonate base plate",
      "USB-C charging and data port",
      "Tactile power button with LED indicator",
      "Anti-slip rubber base pad",
      "Internal PCB and battery retention cradle",
    ],
    salientFeatures: [
      "LSR overmould for antimicrobial surface properties.",
      "Compact puck form factor for unobtrusive placement.",
      "USB-C interface for charging and data transfer.",
      "Medical-grade finish for repeated wipe-down sterilisation.",
      "Single-button operation for clinical simplicity.",
      "Low-profile design for bedside deployment.",
    ],
    scopeOfWork: [
      "Industrial design and CMF specification",
      "LSR overmould tooling design",
      "3D CAD enclosure modelling",
      "Medical standards compliance review",
      "Prototype fabrication and usability evaluation",
      "Design-for-manufacture documentation",
    ],
  },

  {
    serialNumber: 1,
    id: "uv-disinfection-system",
    title: "UV Disinfection System",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER__1.0.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER__3.2.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_4.17.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_TOP_ISO_1.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_BOTTOM_ISO_1.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_LEFT.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_RIGHT.png",
    ],
    features: [
      "Wall-mounted UV-C disinfection unit",
      "Triple UV lamp array for wide-area coverage",
      "Sleek white and silver two-tone enclosure",
      "Integrated occupancy and ambient light sensors",
      "Sealed lamp windows for safe UV containment",
      "Designed for healthcare and commercial spaces",
    ],
    summary:
      "A wall-mounted UV disinfection system branded SafeSpaceUV, engineered for continuous air and surface sanitisation in healthcare, commercial, and public environments. The enclosure houses a triple UV-C lamp array behind sealed optical windows, delivering broad-area coverage while containing UV radiation safely. The two-tone white and silver finish blends into modern interiors, while the wall-mount design keeps floor space free and positions the unit at optimal height for effective disinfection.",
    importantParts: [
      "UV-C lamp modules with sealed optical windows",
      "Two-tone ABS / polycarbonate enclosure shell",
      "Wall-mount bracket and retention system",
      "Integrated occupancy sensor module",
      "Internal reflector array for UV distribution",
      "Thermal management and airflow channels",
    ],
    salientFeatures: [
      "Triple UV-C lamp array for wide-area disinfection.",
      "Sealed optical windows for safe UV containment.",
      "Wall-mount design for optimal positioning.",
      "Two-tone premium finish for modern interiors.",
      "Integrated sensors for automated operation.",
      "DFM-reviewed geometry for production readiness.",
    ],
    scopeOfWork: [
      "Concept ideation and form factor exploration",
      "3D CAD enclosure modelling and detailing",
      "UV optics and reflector design",
      "Thermal management analysis",
      "Wall-mount bracket engineering",
      "Design-for-manufacture review",
      "Prototype build and fit evaluation",
    ],
  },
  {
    serialNumber: 6,
    id: "6e-wifi-router-enclosure",
    title: "6E Wi-Fi Router Enclosure",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/5.png",
    ],
    features: [
      "Robust pressure gauge enclosure design",
      "Stainless steel wetted parts",
      "IP65 ingress protection rating",
      "Panel-mount configuration",
      "Pressure range 0-1000 PSI",
      "±0.5% accuracy class",
    ],
    summary:
      "Robust pressure gauge enclosure with stainless steel wetted parts, IP65 rating, and panel-mount configuration for harsh industrial environments.",
    importantParts: [
      "Stainless steel measurement housing",
      "Precision Bourdon tube",
      "Panel-mount bracket",
      "Protective cover/window",
      "Industrial connector",
      "Damping restrictor",
    ],
    salientFeatures: [
      "Stainless steel construction for corrosion resistance.",
      "IP65 protection against dust and water.",
      "±0.5% measurement accuracy class.",
      "0-1000 PSI pressure range capability.",
    ],
    scopeOfWork: [
      "Mechanical Design and CAD",
      "Material Selection",
      "Pressure Testing",
      "IP Rating Compliance",
      "Manufacturing Drawings",
    ],
  },
  {
    serialNumber: 14,
    id: "360-degree-camera-4k",
    title: "360 Degree Camera with 4K Resolution",
    category: "Imaging & Embedded Vision Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/360_degree_camera_with_4k_resolution/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/360_degree_camera_with_4k_resolution/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/360_degree_camera_with_4k_resolution/1.3.png",
    ],
    features: [
      "360° panoramic video capture",
      "4K ultra HD recording",
      "Real-time video stitching",
      "Low-light image optimization",
      "Wireless connectivity",
      "Cloud media access",
    ],
    summary:
      "Advanced 360-degree 4K camera system built for immersive video capture, surveillance, and smart monitoring with seamless panoramic stitching and remote access.",
    importantParts: [
      "4K Image Sensors",
      "Video Processing Unit",
      "Wide-Angle Lens Array",
      "Wireless Communication Module",
      "Storage Controller",
      "Thermal Management System",
    ],
    salientFeatures: [
      "True 360° panoramic 4K recording.",
      "Real-time image stitching engine.",
      "Low-light optimized image processing.",
      "Wi-Fi enabled remote monitoring.",
      "Cloud storage integration support.",
      "Compact high-performance thermal design.",
    ],
    scopeOfWork: [
      "Imaging Hardware Design",
      "Lens and Sensor Integration",
      "Video Processing Development",
      "Wireless Connectivity Implementation",
      "Thermal Optimization",
      "Performance Validation",
    ],
  },
  {
    serialNumber: 21,
    id: "smart-tap",
    title: "Smart Tap",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/smart_tap/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/smart_tap/2.png",
    ],
    rotatedImages: {},
    features: [
      "Touchless smart water dispensing design",
      "Compact sensor-integrated housing",
      "Waterproof enclosure structure",
      "Modern ergonomic aesthetics",
      "Easy maintenance access",
      "Reliable mounting mechanism",
    ],
    summary:
      "A smart tap mechanical design focused on touchless operation, compact integration, and durable long-term performance in modern environments.",
    importantParts: [
      "Sensor housing",
      "Water outlet assembly",
      "Mounting base",
      "Protective casing",
      "Internal routing chamber",
      "Maintenance access panel",
    ],
    salientFeatures: [
      "Touch-free user interaction",
      "Compact waterproof enclosure",
      "Elegant ergonomic structure",
      "Easy installation and servicing",
    ],
    scopeOfWork: [
      "Product Design",
      "Mechanical CAD Development",
      "Waterproof Enclosure Design",
      "Prototype Validation",
      "Manufacturing Support",
    ],
  },

  {
    serialNumber: 22,
    id: "smart-wifi-stethoscope",
    title: "Smart Wi-Fi Stethoscope",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/smart_Wi-Fi_stethoscope/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/smart_Wi-Fi_stethoscope/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/smart_Wi-Fi_stethoscope/3.png",
    ],
    rotatedImages: {},
    features: [
      "Portable medical device enclosure",
      "Integrated Wi-Fi electronics support",
      "Lightweight ergonomic body",
      "Doctor-friendly handling design",
      "Compact battery compartment",
      "Medical-grade assembly structure",
    ],
    summary:
      "A smart Wi-Fi stethoscope mechanical design built for portability, medical usability, and seamless embedded electronics integration.",
    importantParts: [
      "Chest piece housing",
      "Handle enclosure",
      "Battery compartment",
      "Electronics chamber",
      "Wireless module support",
      "Protective casing structure",
    ],
    salientFeatures: [
      "Compact portable medical form factor",
      "Ergonomic handling for clinicians",
      "Integrated wireless device support",
      "Medical-grade enclosure development",
    ],
    scopeOfWork: [
      "Medical Product Design",
      "Mechanical CAD Modeling",
      "Ergonomic Design Validation",
      "Prototype Development",
      "DFM and Assembly Support",
    ],
  },
  {
    serialNumber: 19,
    id: "warehouse-camera-controller-unit",
    title: "Warehouse Camera Controller Unit",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/5.png",
    ],
    rotatedImages: {},
    features: [
      "AI-enabled industrial enclosure",
      "Compact system packaging",
      "Thermal airflow optimization",
      "Structural rigidity design",
      "Cable routing support",
      "Field-ready robust construction",
    ],
    summary:
      "A compact AI box enclosure designed for embedded intelligence systems with optimized thermal management and rugged deployment readiness.",
    importantParts: [
      "Main enclosure body",
      "Ventilation channels",
      "Mounting brackets",
      "Connector access panels",
      "Cooling support structure",
      "Cable management frame",
    ],
    salientFeatures: [
      "Compact high-density enclosure",
      "Efficient thermal airflow path",
      "Strong structural protection",
      "Service-friendly access design",
    ],
    scopeOfWork: [
      "Industrial Design",
      "Mechanical CAD Development",
      "Thermal Optimization",
      "Prototype Validation",
      "DFM Support",
    ],
  },
];
