import { CaseStudy } from "../../types/case-study";

// ─── Mechanical Design ────────────────────────────────────────────────────────
export const mechanicalCaseStudiesData: CaseStudy[] = [
  // {
  //   id: "capserve-cell-sensor",
  //   title: "CapServe Cell Sensor",
  //   category: "Mechanical Design",
  //   images: [
  //     "/case-studies/CAPSERVE/CAPES_CELL_SENSOR_20_APR_2026.1.png",
  //     "/case-studies/CAPSERVE/CAPES_CELL_SENSOR_20_APR_2026.2.png",
  //     "/case-studies/CAPSERVE/CAPES_CELL_SENSOR_20_APR_2026.3.png",
  //     "/case-studies/CAPSERVE/CAPES_CELL_SENSOR_20_APR_2026.4.png",
  //   ],
  //   features: [
  //     "Compact cell sensor enclosure for field deployment",
  //     "IP65-rated sealed housing with snap-fit assembly",
  //     "Integrated mounting bracket for pole and surface installation",
  //     "Optimised internal cavity for PCB and battery stack",
  //     "UV-stable ABS construction for outdoor environments",
  //     "Designed for DFM and low-volume injection moulding",
  //   ],
  //   summary:
  //     "A precision mechanical enclosure developed for the CapServe cell sensor platform. The design balances a compact footprint with full IP65 ingress protection, enabling reliable outdoor deployment in cellular monitoring applications. The snap-fit housing strategy eliminates exposed fasteners and speeds field servicing, while the integrated pole-mount bracket allows flexible installation across diverse site conditions. All geometry was reviewed for injection-moulding feasibility before handoff to tooling.",
  //   importantParts: [
  //     "UV-stable ABS primary enclosure shell",
  //     "TPE gasket seal for IP65 ingress protection",
  //     "Snap-fit lid retention with tool-free access",
  //     "Integrated pole and flat-surface mounting bracket",
  //     "Internal PCB stand-offs and battery retention ribs",
  //     "Overmoulded cable entry gland",
  //   ],
  //   salientFeatures: [
  //     "IP65 sealed enclosure for outdoor and industrial use.",
  //     "Snap-fit assembly — no visible fasteners.",
  //     "Flexible mounting: pole, wall, or flat surface.",
  //     "UV-stable materials rated for extended outdoor exposure.",
  //     "Service-friendly design with tool-free lid removal.",
  //     "DFM-approved geometry ready for production tooling.",
  //   ],
  //   scopeOfWork: [
  //     "Concept ideation and form factor exploration",
  //     "3D CAD enclosure modelling and detailing",
  //     "Gasket and sealing strategy for IP65 compliance",
  //     "Mounting bracket design and load analysis",
  //     "Design-for-manufacture review",
  //     "Prototype build and fit/seal evaluation",
  //     "Tooling handoff documentation",
  //   ],
  // },
  {
    id: "uv-disinfection-system",
    title: "UV Disinfection System",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER__1.0.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER__3.2.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_4.17.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_TOP_ISO_1.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_BOTTOM_ISO_1.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_LEFT.png",
      "/case-studies/mechanicalCaseStudies/1/MYNATEK_RENDER_9_RIGHT.png",
    ],
    features: [
      "Wall-mounted UV-C disinfection unit",
      "Triple UV lamp array for wide-area coverage",
      "Sleek white and silver two-tone enclosure",
      "Integrated occupancy and ambient light sensors",
      "Sealed lamp windows for safe UV containment",
      "Designed for healthcare and commercial spaces",
    ],
    summary:
      "A wall-mounted UV disinfection system branded SafeSpaceUV, engineered for continuous air and surface sanitisation in healthcare, commercial, and public environments. The enclosure houses a triple UV-C lamp array behind sealed optical windows, delivering broad-area coverage while containing UV radiation safely. The two-tone white and silver finish blends into modern interiors, while the wall-mount design keeps floor space free and positions the unit at optimal height for effective disinfection.",
    importantParts: [
      "UV-C lamp modules with sealed optical windows",
      "Two-tone ABS / polycarbonate enclosure shell",
      "Wall-mount bracket and retention system",
      "Integrated occupancy sensor module",
      "Internal reflector array for UV distribution",
      "Thermal management and airflow channels",
    ],
    salientFeatures: [
      "Triple UV-C lamp array for wide-area disinfection.",
      "Sealed optical windows for safe UV containment.",
      "Wall-mount design for optimal positioning.",
      "Two-tone premium finish for modern interiors.",
      "Integrated sensors for automated operation.",
      "DFM-reviewed geometry for production readiness.",
    ],
    scopeOfWork: [
      "Concept ideation and form factor exploration",
      "3D CAD enclosure modelling and detailing",
      "UV optics and reflector design",
      "Thermal management analysis",
      "Wall-mount bracket engineering",
      "Design-for-manufacture review",
      "Prototype build and fit evaluation",
    ],
  },
  {
    id: "industrial-splice-detector",
    title: "Industrial Splice Detector",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/2/SPLICE_DETECTOR_RENDER_2.4.png",
      "/case-studies/mechanicalCaseStudies/2/SPLICE_DETECTOR_RENDER_2.5.png",
      "/case-studies/mechanicalCaseStudies/2/SPLICE_DETECTOR_RENDER_2.6.png",
    ],
    features: [
      "Extruded aluminium enclosure with heatsink fins",
      "M12 industrial circular connectors",
      "RS-232, RS-485, and EtherCAT / Profinet interfaces",
      "7-segment LED threshold display",
      "LED status indicators for real-time diagnostics",
      "24 VDC powered for industrial environments",
    ],
    summary:
      "A ruggedised industrial splice detector enclosure designed for manufacturing and quality inspection lines. The extruded aluminium body with integrated heatsink fins ensures reliable thermal performance during continuous operation. Industrial M12 connectors provide robust RS-232, RS-485, and EtherCAT/Profinet connectivity, while front-panel LED indicators and a 7-segment display give operators instant visibility into detection thresholds and system status. The 24 VDC power input and QR code traceability label support seamless factory floor integration.",
    importantParts: [
      "Extruded aluminium enclosure with heatsink fins",
      "M12 industrial circular connectors (multiple)",
      "7-segment LED display module",
      "LED status indicator array",
      "DIN rail or panel mounting hardware",
      "Industrial-grade PCB retention system",
    ],
    salientFeatures: [
      "Extruded aluminium construction with integral heatsink.",
      "M12 connectors for vibration-proof industrial wiring.",
      "RS-232, RS-485, and EtherCAT / Profinet support.",
      "Front-panel 7-segment threshold display.",
      "LED status indicators for real-time diagnostics.",
      "24 VDC industrial power input.",
    ],
    scopeOfWork: [
      "Mechanical enclosure design and aluminium extrusion profile",
      "Connector panel layout and I/O planning",
      "3D CAD modelling and detailing",
      "Thermal analysis and heatsink optimisation",
      "Design-for-manufacture review",
      "Prototype build and environmental testing",
    ],
  },
  {
    id: "ott-media-gateway",
    title: "OTT Media Gateway",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG2.1.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG2.2.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG4.4.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG4.5.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG4.6.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG5.7.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG5.8.png",
    ],
    features: [
      "Compact desktop enclosure with dual antenna mounts",
      "Angular faceted design language for premium shelf presence",
      "Front-panel Debug, IR EXT, USB, and SD Card ports",
      "Integrated antenna hinge mechanisms",
      "Ventilated base for passive thermal management",
      "Designed for consumer and commercial OTT streaming",
    ],
    summary:
      "A sleek OTT media gateway enclosure branded TEKION, designed for consumer and commercial streaming applications. The angular, faceted enclosure features dual external antenna mounts with articulating hinges, providing flexible positioning for optimal wireless reception. Front-panel access to Debug, IR EXT, USB, and SD Card interfaces simplifies setup and maintenance, while the ventilated base plate ensures reliable passive cooling during continuous streaming operation.",
    importantParts: [
      "Injection-moulded ABS primary enclosure shell",
      "Dual articulating antenna hinge mounts",
      "Front-panel I/O port assembly (USB, SD, IR, Debug)",
      "Ventilated base plate with rubber feet",
      "Internal antenna cable routing channels",
      "PCB and heatsink retention system",
    ],
    salientFeatures: [
      "Angular faceted design for premium shelf presence.",
      "Dual articulating antenna mounts for flexible positioning.",
      "Front-panel access to all user-facing ports.",
      "Passive cooling via ventilated base plate.",
      "Compact footprint for living room or rack placement.",
      "DFM-reviewed for high-volume injection moulding.",
    ],
    scopeOfWork: [
      "Industrial design and form exploration",
      "3D CAD enclosure modelling and detailing",
      "Antenna hinge mechanism design",
      "Thermal management analysis",
      "Design-for-manufacture review",
      "Prototype build and fit evaluation",
    ],
  },
  {
    id: "rf-signal-generator-enclosure",
    title: "RF Signal Generator Enclosure",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/4/PG10_RENDER_28_OCT_2024_MG1.1.png",
      "/case-studies/mechanicalCaseStudies/4/PG10_RENDER_28_OCT_2024_MG1.2.png",
      "/case-studies/mechanicalCaseStudies/4/PG10_RENDER_28_OCT_2024_MG1.3.png",
    ],
    features: [
      "Heavy-duty sheet metal enclosure with ventilated panels",
      "Front-panel Ethernet, Analog Interface, and RF Output ports",
      "Integrated AC input (170 – 240 V) with IEC power entry",
      "LED status indicators (RST, PWR, STAT, CFG)",
      "N-type RF output connector and earth terminal",
      "Rack-mount and benchtop compatible form factor",
    ],
    summary:
      "A robust sheet metal enclosure designed for an RF signal generator platform. The heavy-duty construction provides effective EMI shielding and structural rigidity, while ventilated side panels ensure adequate airflow for sustained operation. The front panel houses Ethernet, analog interface, and N-type RF output connectors alongside LED status indicators and a main power switch. The universal AC input (170 – 240 V) and earth terminal support worldwide deployment in laboratory and production test environments.",
    importantParts: [
      "Powder-coated sheet metal enclosure panels",
      "IEC C14 power entry module with fuse",
      "N-type RF output connector",
      "D-sub analog interface connector",
      "RJ45 Ethernet management port",
      "LED indicator and switch assembly",
    ],
    salientFeatures: [
      "Heavy-duty sheet metal for EMI shielding.",
      "Ventilated panels for sustained thermal performance.",
      "Universal AC input (170 – 240 V, 50 – 60 Hz).",
      "N-type RF output for test and measurement.",
      "Front-panel LED indicators for system status.",
      "Rack-mount and benchtop compatible.",
    ],
    scopeOfWork: [
      "Sheet metal enclosure design and detailing",
      "Connector panel layout and cut-out engineering",
      "Ventilation and thermal management analysis",
      "EMI shielding strategy and review",
      "3D CAD modelling and drawing package",
      "Prototype fabrication and fit evaluation",
    ],
  },
  {
    id: "pulse-oximeter-enclosure",
    title: "Pulse Oximeter Enclosure",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/5/PULSE_OXIMETER_RENDER_2.1.png",
      "/case-studies/mechanicalCaseStudies/5/PULSE_OXIMETER_RENDER_2.2.png",
      "/case-studies/mechanicalCaseStudies/5/PULSE_OXIMETER_RENDER_3.1.png",
    ],
    features: [
      "Compact fingertip clip-on form factor",
      "Two-piece snap-fit shell with contrasting colours",
      "Finger channel optimised for comfort and sensor contact",
      "Medical-grade polycarbonate and ABS construction",
      "Designed for single-hand operation",
      "Ventilation slots for sensor heat dissipation",
    ],
    summary:
      "A compact pulse oximeter enclosure designed for clinical and point-of-care SpO2 monitoring. The two-piece clip-on design features a white polycarbonate upper shell and blue ABS cradle, providing a clean medical aesthetic and intuitive finger insertion. The internal finger channel geometry is optimised for consistent optical sensor contact across a range of finger sizes, while ventilation slots manage sensor heat during prolonged monitoring sessions.",
    importantParts: [
      "Medical-grade polycarbonate upper shell",
      "ABS lower cradle with finger channel",
      "Spring-loaded clip hinge mechanism",
      "Optical sensor window and alignment features",
      "Ventilation slots for thermal management",
      "Screw-fastened assembly for serviceability",
    ],
    salientFeatures: [
      "Clip-on design for single-hand operation.",
      "Optimised finger channel for consistent sensor contact.",
      "Medical-grade materials for clinical environments.",
      "Two-tone colour scheme for clear orientation.",
      "Ventilated design for extended monitoring.",
      "DFM-reviewed for injection moulding production.",
    ],
    scopeOfWork: [
      "Medical device enclosure concept design",
      "Finger channel ergonomic study",
      "3D CAD modelling and assembly detailing",
      "Material selection and biocompatibility review",
      "Hinge mechanism design and testing",
      "Design-for-manufacture documentation",
    ],
  },
  {
    id: "qsafe-tilt-sensor",
    title: "QSafe Tilt Sensor",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/6/QSAFE_TILT_SENSOR_RENDER_23_DEC_2023.16.png",
      "/case-studies/mechanicalCaseStudies/6/QSAFE_TILT_SENSOR_RENDER_23_DEC_2023.17.png",
      "/case-studies/mechanicalCaseStudies/6/QSAFE_TILT_SENSOR_RENDER_23_DEC_2023.20.png",
    ],
    features: [
      "Sealed industrial enclosure with flanged mounting base",
      "Power button and status LED for field diagnostics",
      "IP-rated construction for outdoor and industrial use",
      "Four-point flange mounting for structural installations",
      "UV-stable grey ABS construction",
      "Compact form factor for pole and surface mounting",
    ],
    summary:
      "A ruggedised tilt sensor enclosure branded QSafe, designed for structural monitoring and safety applications in outdoor and industrial environments. The sealed grey ABS enclosure features a flanged four-point mounting base for secure attachment to poles, walls, and structural members. A front-panel power button and green status LED provide quick field diagnostics without requiring a connected display. The IP-rated construction ensures reliable operation in rain, dust, and temperature extremes.",
    importantParts: [
      "UV-stable ABS enclosure shell",
      "Flanged four-point mounting base",
      "Sealed power button assembly",
      "Status LED indicator module",
      "Internal gasket for IP-rated sealing",
      "PCB and battery retention features",
    ],
    salientFeatures: [
      "IP-rated sealed enclosure for outdoor deployment.",
      "Four-point flange mounting for structural installations.",
      "Front-panel power button and status LED.",
      "UV-stable materials for extended sun exposure.",
      "Compact form factor for unobtrusive installation.",
      "DFM-approved geometry for production tooling.",
    ],
    scopeOfWork: [
      "Enclosure concept design and form exploration",
      "Mounting bracket and flange design",
      "3D CAD modelling and detailing",
      "Gasket and sealing strategy for IP compliance",
      "Design-for-manufacture review",
      "Prototype build and environmental testing",
    ],
  },
  {
    id: "industrial-pressure-gauge",
    title: "Industrial Pressure Gauge",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/marma/5.png",
    ],
    features: [
      "Robust pressure gauge enclosure design",
      "Stainless steel wetted parts",
      "IP65 ingress protection rating",
      "Panel-mount configuration",
      "Pressure range 0-1000 PSI",
      "±0.5% accuracy class",
    ],
    summary:
      "Robust pressure gauge enclosure with stainless steel wetted parts, IP65 rating, and panel-mount configuration for harsh industrial environments.",
    importantParts: [
      "Stainless steel measurement housing",
      "Precision Bourdon tube",
      "Panel-mount bracket",
      "Protective cover/window",
      "Industrial connector",
      "Damping restrictor",
    ],
    salientFeatures: [
      "Stainless steel construction for corrosion resistance.",
      "IP65 protection against dust and water.",
      "±0.5% measurement accuracy class.",
      "0-1000 PSI pressure range capability.",
    ],
    scopeOfWork: [
      "Mechanical Design and CAD",
      "Material Selection",
      "Pressure Testing",
      "IP Rating Compliance",
      "Manufacturing Drawings",
    ],
  },
  {
    id: "compact-flow-meter-housing",
    title: "Compact Flow Meter Housing",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/10April2022TekionOBD.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/10April2022TekionOBD.5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/20Jan2022TekionOBD.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/10April2022TekionOBD.11.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/10April2022TekionOBD.9.png",
    ],
    features: [
      "Lightweight composite flow meter housing",
      "Integrated display window",
      "Snap-fit assembly design",
      "Inline installation compatibility",
      "Minimal pressure drop design",
      "Engineering plastic construction",
    ],
    summary:
      "Lightweight composite flow meter housing with integrated display window, snap-fit assembly, and optimised for inline installation in fluid systems.",
    importantParts: [
      "Engineering polymer housing",
      "Transparent viewing window",
      "Snap-fit connector body",
      "Measurement turbine assembly",
      "Flow straightener",
      "Quick-disconnect couplings",
    ],
    salientFeatures: [
      "Lightweight engineering plastic construction.",
      "Integrated display window for reading.",
      "Snap-fit assembly for field serviceability.",
      "1-100 L/min flow rate capability.",
      "Minimal pressure drop design.",
    ],
    scopeOfWork: [
      "Enclosure Design and CAD",
      "Material Selection for Flow Compatibility",
      "Window Integration Design",
      "Flow Path Optimization",
      "Testing and Validation",
    ],
  },
  {
    id: "temperature-transmitter-pod",
    title: "Temperature Transmitter Pod",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/pneumatic/PNEUMATIC_TEST_JIG_RENDER.2.1.png",
    ],
    features: [
      "Submersible temperature transmitter design",
      "Corrosion-resistant titanium probe",
      "Precision thermowell geometry",
      "IP68 waterproof rating",
      "Marine application grade",
      "5000m submersion depth rating",
    ],
    summary:
      "Submersible temperature transmitter with corrosion-resistant titanium probe, precision thermowell design, and IP68 waterproof rating for marine applications.",
    importantParts: [
      "Titanium probe and housing",
      "Precision thermowell",
      "RTD sensor element",
      "Waterproof connector",
      "Cable gland assembly",
      "Hydrodynamic fairings",
    ],
    salientFeatures: [
      "Titanium construction for corrosion resistance.",
      "IP68 waterproof rating (-40°C to +125°C).",
      "5000m submersion depth capability.",
      "±0.5°C measurement accuracy.",
      "Marine-grade reliability.",
    ],
    scopeOfWork: [
      "Probe Design and CAD",
      "Thermowell Optimization",
      "Material Selection for Seawater",
      "Waterproof Connector Integration",
      "Deep-water Testing Validation",
    ],
  },
  {
    id: "ventilation-control-damper",
    title: "Ventilation Control Damper",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SDR/SDR_RENDERING_11_JAN_2025_S1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SDR/SDR_RENDERING_11_JAN_2025_S1.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SDR/SDR_RENDERING_11_JAN_2025_S1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SDR/SDR_RENDERING_11_JAN_2025_S1.7.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SDR/SDR_RENDERING_11_JAN_2025_S1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ventilation_control_damper/military_man_bigcat_2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ventilation_control_damper/military_man_with_bigcat3.7.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ventilation_control_damper/military_man_with_bigcat3.6.png",
    ],
    features: [
      "Motorised ventilation damper assembly",
      "Low-friction blade mechanism",
      "Sealed bearing design",
      "Position feedback sensor",
      "Building automation integration",
      "100k cycle life rating",
    ],
    summary:
      "Motorised ventilation damper with low-friction blade mechanism, sealed bearing design, and position feedback for building automation integration.",
    importantParts: [
      "24V DC motor assembly",
      "Low-friction damper blade",
      "Sealed precision bearings",
      "Position feedback potentiometer",
      "Aluminium frame",
      "Thermal insulation gasket",
    ],
    salientFeatures: [
      "24V DC motor with modulating control.",
      "0-10V position feedback capability.",
      "100k cycle life rated construction.",
      "Low-friction for energy efficiency.",
      "Thermal break frame design.",
    ],
    scopeOfWork: [
      "Motor Assembly Design",
      "Blade Mechanism Development",
      "Bearing Selection and Integration",
      "Feedback Sensor Integration",
      "Testing and Life Cycle Validation",
    ],
  },
  {
    id: "safety-relief-valve-housing",
    title: "Safety Relief Valve Housing",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SMOAD/SMOAD.1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SMOAD/SMOAD.14.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SMOAD/SMOAD.15.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SMOAD/SMOAD.png",
    ],
    features: [
      "Certified pressure relief valve design",
      "Redundant safety features",
      "Manifold-block integration",
      "ASME standards compliance",
      "Up to 5000 PSI pressure rating",
      "Zero leakage rating",
    ],
    summary:
      "Certified pressure relief valve with redundant safety features, manifold-block integration, and compliance with ASME standards for petrochemical applications.",
    importantParts: [
      "Ductile iron valve body",
      "Hardened steel seat",
      "Precision spring assembly",
      "Redundant sealing design",
      "Manifold integration block",
      "Inspection ports",
    ],
    salientFeatures: [
      "ASME certified design.",
      "Redundant safety mechanisms.",
      "Up to 5000 PSI rated capacity.",
      "Zero leakage performance.",
      "Petrochemical grade materials.",
    ],
    scopeOfWork: [
      "Valve Design per ASME Standards",
      "Safety Feature Integration",
      "Manifold Block Design",
      "Material Selection for Petrochemical",
      "Certification and Testing",
    ],
  },
  {
    id: "wireless-sensor-node-case",
    title: "Wireless Sensor Node Case",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/hydronet/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/hydronet/2.png",
    ],
    features: [
      "Compact multi-sensor enclosure",
      "Tool-free battery access",
      "Integrated antenna mounting",
      "Desiccant cartridge support",
      "IP66 protection rating",
      "UV-resistant ABS material",
    ],
    summary:
      "Compact multi-sensor enclosure with tool-free battery access, integrated antenna mounting, and desiccant cartridge support for extended outdoor deployment.",
    importantParts: [
      "UV-resistant ABS housing",
      "Snap-fit battery door",
      "Antenna mounting post",
      "Desiccant cartridge pocket",
      "Multi-sensor PCB bracket",
      "Gasket sealing system",
    ],
    salientFeatures: [
      "IP66 protection for outdoor use.",
      "Tool-free battery replacement.",
      "Integrated antenna mounting.",
      "1-year sealed operation capability.",
      "UV-stable materials.",
    ],
    scopeOfWork: [
      "Compact Enclosure Design",
      "Battery Door Mechanism Design",
      "Antenna Integration",
      "Gasket and Sealing Design",
      "Prototype and Testing",
    ],
  },
  {
    id: "energy-meter-enclosure",
    title: "Energy Meter Enclosure",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/hydronet-2/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/hydronet-2/1.2.png",
    ],
    features: [
      "Wall-mounted smart meter enclosure",
      "Tamper-evident design features",
      "DIN rail mounting compatibility",
      "Thermal management design",
      "4 module slots capacity",
      "IEC61439 compliance",
    ],
    summary:
      "Wall-mounted smart meter enclosure with tamper-evident features, DIN rail mounting compatibility, and thermal management for utility deployment.",
    importantParts: [
      "Fire-rated plastic housing",
      "Tamper detection system",
      "DIN rail mounting hardware",
      "Thermal management vents",
      "Module slot assembly",
      "Locking door mechanism",
    ],
    salientFeatures: [
      "IEC61439 standard compliance.",
      "Tamper-evident construction.",
      "DIN rail and wall-mount options.",
      "4-module expansion capacity.",
      "Thermal vent design.",
    ],
    scopeOfWork: [
      "Enclosure Design per IEC Standards",
      "Tamper Feature Integration",
      "DIN Rail Compatibility Design",
      "Thermal Analysis",
      "Production Documentation",
    ],
  },

  {
    id: "3-axis-tilt-sensor",
    title: "3-Axis Tilt Sensor",
    category: "Industrial Sensors & Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/3-axis_tilt_sensor/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/3-axis_tilt_sensor/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/3-axis_tilt_sensor/1.3.png",
    ],
    features: [
      "Three-axis inclination sensing",
      "High precision angle detection",
      "Shock and vibration resistance",
      "Real-time orientation monitoring",
      "Industrial communication support",
      "Low power operation",
    ],
    summary:
      "High-precision 3-axis tilt sensor designed for industrial monitoring, structural safety, and machine alignment with reliable real-time orientation tracking.",
    importantParts: [
      "MEMS Accelerometer",
      "Signal Conditioning Circuit",
      "Microcontroller Unit",
      "RS485 Communication Interface",
      "Power Regulation Unit",
      "Industrial Enclosure",
    ],
    salientFeatures: [
      "Accurate 3-axis tilt angle measurement.",
      "High vibration and shock tolerance.",
      "Supports Modbus and RS485 communication.",
      "Low drift long-term stability.",
      "Compact industrial-grade housing.",
      "Low power consumption for remote deployment.",
    ],
    scopeOfWork: [
      "Sensor Hardware Design",
      "Signal Conditioning Development",
      "Tilt Calculation Algorithm",
      "Industrial Protocol Integration",
      "Mechanical Ruggedization",
      "Calibration and Validation",
    ],
  },

  {
    id: "360-degree-camera-4k",
    title: "360 Degree Camera with 4K Resolution",
    category: "Imaging & Embedded Vision Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/360_degree_camera_with_4k_resolution/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/360_degree_camera_with_4k_resolution/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/360_degree_camera_with_4k_resolution/1.3.png",
    ],
    features: [
      "360° panoramic video capture",
      "4K ultra HD recording",
      "Real-time video stitching",
      "Low-light image optimization",
      "Wireless connectivity",
      "Cloud media access",
    ],
    summary:
      "Advanced 360-degree 4K camera system built for immersive video capture, surveillance, and smart monitoring with seamless panoramic stitching and remote access.",
    importantParts: [
      "4K Image Sensors",
      "Video Processing Unit",
      "Wide-Angle Lens Array",
      "Wireless Communication Module",
      "Storage Controller",
      "Thermal Management System",
    ],
    salientFeatures: [
      "True 360° panoramic 4K recording.",
      "Real-time image stitching engine.",
      "Low-light optimized image processing.",
      "Wi-Fi enabled remote monitoring.",
      "Cloud storage integration support.",
      "Compact high-performance thermal design.",
    ],
    scopeOfWork: [
      "Imaging Hardware Design",
      "Lens and Sensor Integration",
      "Video Processing Development",
      "Wireless Connectivity Implementation",
      "Thermal Optimization",
      "Performance Validation",
    ],
  },

  {
    id: "industrial-iot-gateway",
    title: "Industrial IoT Gateway",
    category: "Industrial IoT & Edge Computing",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/indutrial_iot_gateway/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/indutrial_iot_gateway/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/indutrial_iot_gateway/1.3.png",
    ],
    features: [
      "Multi-protocol industrial connectivity",
      "Edge data processing",
      "Cloud integration",
      "Remote diagnostics",
      "Secure device management",
      "Rugged industrial deployment",
    ],
    summary:
      "Robust industrial IoT gateway enabling seamless machine connectivity, edge analytics, and secure cloud integration for modern factory automation environments.",
    importantParts: [
      "Industrial Processor",
      "RS485 / CAN Interfaces",
      "LTE & Ethernet Module",
      "Edge Analytics Engine",
      "Secure Storage Unit",
      "Rugged Enclosure",
    ],
    salientFeatures: [
      "Supports Modbus, CAN, and MQTT protocols.",
      "Real-time edge data filtering and processing.",
      "Cloud dashboard connectivity.",
      "Remote diagnostics and firmware updates.",
      "Industrial-grade thermal and surge protection.",
      "Secure encrypted communication support.",
    ],
    scopeOfWork: [
      "Gateway Hardware Design",
      "Industrial Protocol Integration",
      "Edge Computing Implementation",
      "Cloud Connectivity Setup",
      "Security Layer Development",
      "Field Deployment Testing",
    ],
  },

  {
    id: "iot-gateway",
    title: "IoT Gateway",
    category: "IoT Connectivity Solutions",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/iot_gateway/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/iot_gateway/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/iot_gateway/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/iot_gateway/1.4.png",
    ],
    features: [
      "Sensor aggregation",
      "Wireless and wired connectivity",
      "Cloud platform integration",
      "Remote device monitoring",
      "Secure data transmission",
      "Firmware OTA updates",
    ],
    summary:
      "Smart IoT gateway designed for sensor aggregation, secure communication, and cloud integration to simplify large-scale remote monitoring and connected deployments.",
    importantParts: [
      "Microprocessor Unit",
      "Wi-Fi / LTE Module",
      "Sensor Interface Ports",
      "Cloud Communication Engine",
      "Power Management Circuit",
      "Secure Boot Controller",
    ],
    salientFeatures: [
      "Supports multiple sensor protocols.",
      "Secure encrypted cloud communication.",
      "Remote monitoring and diagnostics.",
      "Over-the-air firmware updates.",
      "Reliable field deployment architecture.",
      "Scalable for multi-device installations.",
    ],
    scopeOfWork: [
      "Gateway Circuit Design",
      "Wireless Connectivity Integration",
      "Sensor Interface Development",
      "Cloud Platform Setup",
      "Security Implementation",
      "Validation and Field Testing",
    ],
  },

  {
    id: "obd-v4-system",
    title: "OBD V4 Smart Diagnostic Unit",
    category: "Automotive Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD2/OBD_V4_RENDER_23_NOV_2024_MG2_2.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD2/OBD_V4_RENDER_23_NOV_2024_MG2_2.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD2/OBD_V4_RENDER_23_NOV_2024_MG2_3.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD2/OBD_V4_RENDER_23_NOV_2024_MG2_3.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD2/OBD_V4_RENDER_23_NOV_2024_MG2_4.1.png",
    ],
    features: [
      "Real-time vehicle diagnostics",
      "Engine fault code detection",
      "CAN and OBD-II communication",
      "Live sensor data monitoring",
      "Cloud connectivity",
      "Remote firmware updates",
    ],
    summary:
      "Advanced OBD V4 smart diagnostic unit designed for real-time vehicle health monitoring, fault detection, and connected fleet diagnostics with secure cloud integration.",
    importantParts: [
      "OBD-II Interface",
      "CAN Communication Module",
      "Microcontroller Unit",
      "LTE / Wi-Fi Connectivity Module",
      "Power Management Circuit",
      "Diagnostic Processing Engine",
    ],
    salientFeatures: [
      "Supports standard OBD-II and CAN protocols.",
      "Real-time DTC fault code detection.",
      "Live engine and sensor parameter monitoring.",
      "Remote diagnostics through cloud platform.",
      "OTA firmware update capability.",
      "Compact automotive-grade rugged design.",
    ],
    scopeOfWork: [
      "OBD Hardware Design",
      "CAN Protocol Integration",
      "Diagnostic Firmware Development",
      "Cloud Connectivity Implementation",
      "Remote Monitoring Dashboard",
      "Testing and Automotive Validation",
    ],
  },
    {
      id: "footswitch",
      title: "Footswitch",
      category: "Mechanical Design",
      images: [
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.10.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.11.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.12.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.13.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.14.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.7.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.8.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.9.png",
      ],
      rotatedImages: {},
      features: [
        "Ergonomic industrial footswitch design",
        "Durable pedal actuation mechanism",
        "Heavy-duty enclosure construction",
        "Anti-slip surface design",
        "Reliable switching performance",
        "Compact and robust assembly",
      ],
      summary:
        "A mechanically robust industrial footswitch designed for reliable hands-free control in demanding operational environments.",
      importantParts: [
        "Pedal assembly",
        "Spring return mechanism",
        "Switch actuator",
        "Protective enclosure",
        "Anti-slip base",
        "Cable interface housing",
      ],
      salientFeatures: [
        "Ergonomic pedal operation",
        "High durability for industrial usage",
        "Stable anti-slip base structure",
        "Reliable long-life switching performance",
      ],
      scopeOfWork: [
        "Concept Design",
        "Mechanical CAD Design",
        "Enclosure Development",
        "Prototype Validation",
        "Manufacturing Support",
      ],
    },
  
    {
      id: "frizb-ai-box",
      title: "Frizb AI Box",
      category: "Mechanical Design",
      images: [
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/FRIZB_AI_BOX_S2.12.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/FRIZB_AI_BOX_S2.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/FRIZB_AI_BOX_S3.10.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/FRIZB_AI_BOX_S3.11.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/FRIZB_AI_BOX_S3.12.1.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/FRIZB_AI_BOX_S3.12.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/FRIZB_AI_BOX_S3.13.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/FRIZB_AI_BOX_S3.14.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/FRIZB_AI_BOX_S3.15.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/frizb_ai_box/FRIZB_AI_BOX_S3.9.png",
      ],
      rotatedImages: {},
      features: [
        "AI-enabled industrial enclosure",
        "Compact system packaging",
        "Thermal airflow optimization",
        "Structural rigidity design",
        "Cable routing support",
        "Field-ready robust construction",
      ],
      summary:
        "A compact AI box enclosure designed for embedded intelligence systems with optimized thermal management and rugged deployment readiness.",
      importantParts: [
        "Main enclosure body",
        "Ventilation channels",
        "Mounting brackets",
        "Connector access panels",
        "Cooling support structure",
        "Cable management frame",
      ],
      salientFeatures: [
        "Compact high-density enclosure",
        "Efficient thermal airflow path",
        "Strong structural protection",
        "Service-friendly access design",
      ],
      scopeOfWork: [
        "Industrial Design",
        "Mechanical CAD Development",
        "Thermal Optimization",
        "Prototype Validation",
        "DFM Support",
      ],
    },
  
    {
      id: "mcs",
      title: "MCS",
      category: "Mechanical Design",
      images: [
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.58.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.59.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.60.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.61.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.62.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.63.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.64.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.65.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S3.66.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S3.67.png",
      ],
      rotatedImages: {},
      features: [
        "Complex mechanical assembly system",
        "Precision-fit component structure",
        "High-strength frame design",
        "Assembly optimization",
        "Modular construction approach",
        "Manufacturing-ready configuration",
      ],
      summary:
        "A precision-engineered mechanical assembly system designed for structural stability, modular integration, and manufacturing efficiency.",
      importantParts: [
        "Primary support frame",
        "Assembly brackets",
        "Structural fasteners",
        "Load-bearing joints",
        "Mounting supports",
        "Protective outer frame",
      ],
      salientFeatures: [
        "Modular assembly architecture",
        "High structural strength",
        "Precision fitment across components",
        "Production-friendly mechanical design",
      ],
      scopeOfWork: [
        "System Assembly Design",
        "Mechanical CAD Modeling",
        "Tolerance Analysis",
        "Prototype Testing",
        "Production Engineering Support",
      ],
    },
  
    {
      id: "smart-tap",
      title: "Smart Tap",
      category: "Mechanical Design",
      images: [
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/smart_tap/1.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/smart_tap/2.png",
      ],
      rotatedImages: {},
      features: [
        "Touchless smart water dispensing design",
        "Compact sensor-integrated housing",
        "Waterproof enclosure structure",
        "Modern ergonomic aesthetics",
        "Easy maintenance access",
        "Reliable mounting mechanism",
      ],
      summary:
        "A smart tap mechanical design focused on touchless operation, compact integration, and durable long-term performance in modern environments.",
      importantParts: [
        "Sensor housing",
        "Water outlet assembly",
        "Mounting base",
        "Protective casing",
        "Internal routing chamber",
        "Maintenance access panel",
      ],
      salientFeatures: [
        "Touch-free user interaction",
        "Compact waterproof enclosure",
        "Elegant ergonomic structure",
        "Easy installation and servicing",
      ],
      scopeOfWork: [
        "Product Design",
        "Mechanical CAD Development",
        "Waterproof Enclosure Design",
        "Prototype Validation",
        "Manufacturing Support",
      ],
    },
  
    {
      id: "smart-wifi-stethoscope",
      title: "Smart Wi-Fi Stethoscope",
      category: "Mechanical Design",
      images: [
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/smart_Wi-Fi_stethoscope/1.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/smart_Wi-Fi_stethoscope/2.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/smart_Wi-Fi_stethoscope/3.png",
      ],
      rotatedImages: {},
      features: [
        "Portable medical device enclosure",
        "Integrated Wi-Fi electronics support",
        "Lightweight ergonomic body",
        "Doctor-friendly handling design",
        "Compact battery compartment",
        "Medical-grade assembly structure",
      ],
      summary:
        "A smart Wi-Fi stethoscope mechanical design built for portability, medical usability, and seamless embedded electronics integration.",
      importantParts: [
        "Chest piece housing",
        "Handle enclosure",
        "Battery compartment",
        "Electronics chamber",
        "Wireless module support",
        "Protective casing structure",
      ],
      salientFeatures: [
        "Compact portable medical form factor",
        "Ergonomic handling for clinicians",
        "Integrated wireless device support",
        "Medical-grade enclosure development",
      ],
      scopeOfWork: [
        "Medical Product Design",
        "Mechanical CAD Modeling",
        "Ergonomic Design Validation",
        "Prototype Development",
        "DFM and Assembly Support",
      ],
    },
  
    {
      id: "tensionmeter",
      title: "Tension Meter",
      category: "Mechanical Design",
      images: [
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.10.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.11.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.2.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.3.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.4.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.5.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.6.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.7.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.9.png",
        "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.png",
      ],
      rotatedImages: {},
      features: [
        "Industrial tension measurement device",
        "Precision force monitoring design",
        "Heavy-duty structural body",
        "Portable inspection-ready form factor",
        "High-load handling capability",
        "Reliable calibration support",
      ],
      summary:
        "A rugged tension meter designed for precise industrial force measurement with durable construction and reliable field performance.",
      importantParts: [
        "Load sensing frame",
        "Measurement body",
        "Calibration mechanism",
        "Display housing",
        "Mounting support structure",
        "Protective outer casing",
      ],
      salientFeatures: [
        "High-precision force measurement",
        "Strong industrial-grade construction",
        "Portable field operation design",
        "Reliable calibration stability",
      ],
      scopeOfWork: [
        "Mechanical Product Design",
        "Structural Analysis",
        "CAD Development",
        "Prototype Validation",
        "Production Support",
      ],
    },
];
