import { CaseStudy } from "../../types/case-study";

// ─── Mechanical Design ────────────────────────────────────────────────────────
export const mechanicalCaseStudiesData: CaseStudy[] = [
  {
    serialNumber: 2,
    id: "industrial-splice-detector",
    title: "Industrial Splice Detector",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/2/SPLICE_DETECTOR_RENDER_2.4.png",
      "/case-studies/mechanicalCaseStudies/2/SPLICE_DETECTOR_RENDER_2.5.png",
      "/case-studies/mechanicalCaseStudies/2/SPLICE_DETECTOR_RENDER_2.6.png",
    ],
    features: [
      "Extruded aluminium enclosure with heatsink fins",
      "M12 industrial circular connectors",
      "RS-232, RS-485, and EtherCAT / Profinet interfaces",
      "7-segment LED threshold display",
      "LED status indicators for real-time diagnostics",
      "24 VDC powered for industrial environments",
    ],
    summary:
      "A ruggedised industrial splice detector enclosure designed for manufacturing and quality inspection lines. The extruded aluminium body with integrated heatsink fins ensures reliable thermal performance during continuous operation. Industrial M12 connectors provide robust RS-232, RS-485, and EtherCAT/Profinet connectivity, while front-panel LED indicators and a 7-segment display give operators instant visibility into detection thresholds and system status. The 24 VDC power input and QR code traceability label support seamless factory floor integration.",
    importantParts: [
      "Extruded aluminium enclosure with heatsink fins",
      "M12 industrial circular connectors (multiple)",
      "7-segment LED display module",
      "LED status indicator array",
      "DIN rail or panel mounting hardware",
      "Industrial-grade PCB retention system",
    ],
    salientFeatures: [
      "Extruded aluminium construction with integral heatsink.",
      "M12 connectors for vibration-proof industrial wiring.",
      "RS-232, RS-485, and EtherCAT / Profinet support.",
      "Front-panel 7-segment threshold display.",
      "LED status indicators for real-time diagnostics.",
      "24 VDC industrial power input.",
    ],
    scopeOfWork: [
      "Mechanical enclosure design and aluminium extrusion profile",
      "Connector panel layout and I/O planning",
      "3D CAD modelling and detailing",
      "Thermal analysis and heatsink optimisation",
      "Design-for-manufacture review",
      "Prototype build and environmental testing",
    ],
  },
  {
    serialNumber: 3,
    id: "ott-media-gateway",
    title: "OTT Media Gateway",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG2.1.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG2.2.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG4.4.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG4.5.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG4.6.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG5.7.png",
      "/case-studies/mechanicalCaseStudies/3/OTT_RENDER_27_NOV_2024_MG5.8.png",
    ],
    features: [
      "Compact desktop enclosure with dual antenna mounts",
      "Angular faceted design language for premium shelf presence",
      "Front-panel Debug, IR EXT, USB, and SD Card ports",
      "Integrated antenna hinge mechanisms",
      "Ventilated base for passive thermal management",
      "Designed for consumer and commercial OTT streaming",
    ],
    summary:
      "A sleek OTT media gateway enclosure branded TEKION, designed for consumer and commercial streaming applications. The angular, faceted enclosure features dual external antenna mounts with articulating hinges, providing flexible positioning for optimal wireless reception. Front-panel access to Debug, IR EXT, USB, and SD Card interfaces simplifies setup and maintenance, while the ventilated base plate ensures reliable passive cooling during continuous streaming operation.",
    importantParts: [
      "Injection-moulded ABS primary enclosure shell",
      "Dual articulating antenna hinge mounts",
      "Front-panel I/O port assembly (USB, SD, IR, Debug)",
      "Ventilated base plate with rubber feet",
      "Internal antenna cable routing channels",
      "PCB and heatsink retention system",
    ],
    salientFeatures: [
      "Angular faceted design for premium shelf presence.",
      "Dual articulating antenna mounts for flexible positioning.",
      "Front-panel access to all user-facing ports.",
      "Passive cooling via ventilated base plate.",
      "Compact footprint for living room or rack placement.",
      "DFM-reviewed for high-volume injection moulding.",
    ],
    scopeOfWork: [
      "Industrial design and form exploration",
      "3D CAD enclosure modelling and detailing",
      "Antenna hinge mechanism design",
      "Thermal management analysis",
      "Design-for-manufacture review",
      "Prototype build and fit evaluation",
    ],
  },
  {
    serialNumber: 4,
    id: "rf-signal-generator-enclosure",
    title: "RF Signal Generator Enclosure",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/4/PG10_RENDER_28_OCT_2024_MG1.1.png",
      "/case-studies/mechanicalCaseStudies/4/PG10_RENDER_28_OCT_2024_MG1.2.png",
      "/case-studies/mechanicalCaseStudies/4/PG10_RENDER_28_OCT_2024_MG1.3.png",
    ],
    features: [
      "Heavy-duty sheet metal enclosure with ventilated panels",
      "Front-panel Ethernet, Analog Interface, and RF Output ports",
      "Integrated AC input (170 – 240 V) with IEC power entry",
      "LED status indicators (RST, PWR, STAT, CFG)",
      "N-type RF output connector and earth terminal",
      "Rack-mount and benchtop compatible form factor",
    ],
    summary:
      "A robust sheet metal enclosure designed for an RF signal generator platform. The heavy-duty construction provides effective EMI shielding and structural rigidity, while ventilated side panels ensure adequate airflow for sustained operation. The front panel houses Ethernet, analog interface, and N-type RF output connectors alongside LED status indicators and a main power switch. The universal AC input (170 – 240 V) and earth terminal support worldwide deployment in laboratory and production test environments.",
    importantParts: [
      "Powder-coated sheet metal enclosure panels",
      "IEC C14 power entry module with fuse",
      "N-type RF output connector",
      "D-sub analog interface connector",
      "RJ45 Ethernet management port",
      "LED indicator and switch assembly",
    ],
    salientFeatures: [
      "Heavy-duty sheet metal for EMI shielding.",
      "Ventilated panels for sustained thermal performance.",
      "Universal AC input (170 – 240 V, 50 – 60 Hz).",
      "N-type RF output for test and measurement.",
      "Front-panel LED indicators for system status.",
      "Rack-mount and benchtop compatible.",
    ],
    scopeOfWork: [
      "Sheet metal enclosure design and detailing",
      "Connector panel layout and cut-out engineering",
      "Ventilation and thermal management analysis",
      "EMI shielding strategy and review",
      "3D CAD modelling and drawing package",
      "Prototype fabrication and fit evaluation",
    ],
  },
  {
    serialNumber: 5,
    id: "pulse-oximeter-enclosure",
    title: "Pulse Oximeter Enclosure",
    category: "Mechanical Design",
    images: [
      "/case-studies/mechanicalCaseStudies/5/PULSE_OXIMETER_RENDER_2.1.png",
      "/case-studies/mechanicalCaseStudies/5/PULSE_OXIMETER_RENDER_2.2.png",
      "/case-studies/mechanicalCaseStudies/5/PULSE_OXIMETER_RENDER_3.1.png",
    ],
    features: [
      "Compact fingertip clip-on form factor",
      "Two-piece snap-fit shell with contrasting colours",
      "Finger channel optimised for comfort and sensor contact",
      "Medical-grade polycarbonate and ABS construction",
      "Designed for single-hand operation",
      "Ventilation slots for sensor heat dissipation",
    ],
    summary:
      "A compact pulse oximeter enclosure designed for clinical and point-of-care SpO2 monitoring. The two-piece clip-on design features a white polycarbonate upper shell and blue ABS cradle, providing a clean medical aesthetic and intuitive finger insertion. The internal finger channel geometry is optimised for consistent optical sensor contact across a range of finger sizes, while ventilation slots manage sensor heat during prolonged monitoring sessions.",
    importantParts: [
      "Medical-grade polycarbonate upper shell",
      "ABS lower cradle with finger channel",
      "Spring-loaded clip hinge mechanism",
      "Optical sensor window and alignment features",
      "Ventilation slots for thermal management",
      "Screw-fastened assembly for serviceability",
    ],
    salientFeatures: [
      "Clip-on design for single-hand operation.",
      "Optimised finger channel for consistent sensor contact.",
      "Medical-grade materials for clinical environments.",
      "Two-tone colour scheme for clear orientation.",
      "Ventilated design for extended monitoring.",
      "DFM-reviewed for injection moulding production.",
    ],
    scopeOfWork: [
      "Medical device enclosure concept design",
      "Finger channel ergonomic study",
      "3D CAD modelling and assembly detailing",
      "Material selection and biocompatibility review",
      "Hinge mechanism design and testing",
      "Design-for-manufacture documentation",
    ],
  },

  {
    serialNumber: 7,
    id: "obd-enclosure",
    title: "OBD Enclosure",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/10April2022TekionOBD.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/10April2022TekionOBD.5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/20Jan2022TekionOBD.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/10April2022TekionOBD.11.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD/10April2022TekionOBD.9.png",
    ],
    features: [
      "Lightweight composite flow meter housing",
      "Integrated display window",
      "Snap-fit assembly design",
      "Inline installation compatibility",
      "Minimal pressure drop design",
      "Engineering plastic construction",
    ],
    summary:
      "Lightweight composite flow meter housing with integrated display window, snap-fit assembly, and optimised for inline installation in fluid systems.",
    importantParts: [
      "Engineering polymer housing",
      "Transparent viewing window",
      "Snap-fit connector body",
      "Measurement turbine assembly",
      "Flow straightener",
      "Quick-disconnect couplings",
    ],
    salientFeatures: [
      "Lightweight engineering plastic construction.",
      "Integrated display window for reading.",
      "Snap-fit assembly for field serviceability.",
      "1-100 L/min flow rate capability.",
      "Minimal pressure drop design.",
    ],
    scopeOfWork: [
      "Enclosure Design and CAD",
      "Material Selection for Flow Compatibility",
      "Window Integration Design",
      "Flow Path Optimization",
      "Testing and Validation",
    ],
  },
  {
    serialNumber: 8,
    id: "pneumatic-test-jig",
    title: "Pneumatic Test Jig",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/pneumatic/PNEUMATIC_TEST_JIG_RENDER.2.1.png",
    ],
    features: [
      "Submersible temperature transmitter design",
      "Corrosion-resistant titanium probe",
      "Precision thermowell geometry",
      "IP68 waterproof rating",
      "Marine application grade",
      "5000m submersion depth rating",
    ],
    summary:
      "Submersible temperature transmitter with corrosion-resistant titanium probe, precision thermowell design, and IP68 waterproof rating for marine applications.",
    importantParts: [
      "Titanium probe and housing",
      "Precision thermowell",
      "RTD sensor element",
      "Waterproof connector",
      "Cable gland assembly",
      "Hydrodynamic fairings",
    ],
    salientFeatures: [
      "Titanium construction for corrosion resistance.",
      "IP68 waterproof rating (-40°C to +125°C).",
      "5000m submersion depth capability.",
      "±0.5°C measurement accuracy.",
      "Marine-grade reliability.",
    ],
    scopeOfWork: [
      "Probe Design and CAD",
      "Thermowell Optimization",
      "Material Selection for Seawater",
      "Waterproof Connector Integration",
      "Deep-water Testing Validation",
    ],
  },
  {
    serialNumber: 9,
    id: "rugged-communication-control-system-enclosure",
    title: "Rugged Communication Control System Enclosure",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SDR/SDR_RENDERING_11_JAN_2025_S1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SDR/SDR_RENDERING_11_JAN_2025_S1.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SDR/SDR_RENDERING_11_JAN_2025_S1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SDR/SDR_RENDERING_11_JAN_2025_S1.7.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SDR/SDR_RENDERING_11_JAN_2025_S1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ventilation_control_damper/military_man_bigcat_2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ventilation_control_damper/military_man_with_bigcat3.7.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ventilation_control_damper/military_man_with_bigcat3.6.png",
    ],
    features: [
      "Motorised ventilation damper assembly",
      "Low-friction blade mechanism",
      "Sealed bearing design",
      "Position feedback sensor",
      "Building automation integration",
      "100k cycle life rating",
    ],
    summary:
      "Motorised ventilation damper with low-friction blade mechanism, sealed bearing design, and position feedback for building automation integration.",
    importantParts: [
      "24V DC motor assembly",
      "Low-friction damper blade",
      "Sealed precision bearings",
      "Position feedback potentiometer",
      "Aluminium frame",
      "Thermal insulation gasket",
    ],
    salientFeatures: [
      "24V DC motor with modulating control.",
      "0-10V position feedback capability.",
      "100k cycle life rated construction.",
      "Low-friction for energy efficiency.",
      "Thermal break frame design.",
    ],
    scopeOfWork: [
      "Motor Assembly Design",
      "Blade Mechanism Development",
      "Bearing Selection and Integration",
      "Feedback Sensor Integration",
      "Testing and Life Cycle Validation",
    ],
  },
  {
    serialNumber: 10,
    id: "5g-router",
    title: "5G Router",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SMOAD/SMOAD.1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SMOAD/SMOAD.14.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SMOAD/SMOAD.15.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/SMOAD/SMOAD.png",
    ],
    features: [
      "Certified pressure relief valve design",
      "Redundant safety features",
      "Manifold-block integration",
      "ASME standards compliance",
      "Up to 5000 PSI pressure rating",
      "Zero leakage rating",
    ],
    summary:
      "Certified pressure relief valve with redundant safety features, manifold-block integration, and compliance with ASME standards for petrochemical applications.",
    importantParts: [
      "Ductile iron valve body",
      "Hardened steel seat",
      "Precision spring assembly",
      "Redundant sealing design",
      "Manifold integration block",
      "Inspection ports",
    ],
    salientFeatures: [
      "ASME certified design.",
      "Redundant safety mechanisms.",
      "Up to 5000 PSI rated capacity.",
      "Zero leakage performance.",
      "Petrochemical grade materials.",
    ],
    scopeOfWork: [
      "Valve Design per ASME Standards",
      "Safety Feature Integration",
      "Manifold Block Design",
      "Material Selection for Petrochemical",
      "Certification and Testing",
    ],
  },
  {
    serialNumber: 11,
    id: "emf-flow-meter",
    title: "EMF Flow Meter",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/hydronet/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/hydronet/2.png",
    ],
    features: [
      "Compact multi-sensor enclosure",
      "Tool-free battery access",
      "Integrated antenna mounting",
      "Desiccant cartridge support",
      "IP66 protection rating",
      "UV-resistant ABS material",
    ],
    summary:
      "Compact multi-sensor enclosure with tool-free battery access, integrated antenna mounting, and desiccant cartridge support for extended outdoor deployment.",
    importantParts: [
      "UV-resistant ABS housing",
      "Snap-fit battery door",
      "Antenna mounting post",
      "Desiccant cartridge pocket",
      "Multi-sensor PCB bracket",
      "Gasket sealing system",
    ],
    salientFeatures: [
      "IP66 protection for outdoor use.",
      "Tool-free battery replacement.",
      "Integrated antenna mounting.",
      "1-year sealed operation capability.",
      "UV-stable materials.",
    ],
    scopeOfWork: [
      "Compact Enclosure Design",
      "Battery Door Mechanism Design",
      "Antenna Integration",
      "Gasket and Sealing Design",
      "Prototype and Testing",
    ],
  },
  {
    serialNumber: 12,
    id: "ultrasonic-flow-meter",
    title: "Ultrasonic Flow Meter",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/hydronet-2/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/hydronet-2/1.2.png",
    ],
    features: [
      "Wall-mounted smart meter enclosure",
      "Tamper-evident design features",
      "DIN rail mounting compatibility",
      "Thermal management design",
      "4 module slots capacity",
      "IEC61439 compliance",
    ],
    summary:
      "Wall-mounted smart meter enclosure with tamper-evident features, DIN rail mounting compatibility, and thermal management for utility deployment.",
    importantParts: [
      "Fire-rated plastic housing",
      "Tamper detection system",
      "DIN rail mounting hardware",
      "Thermal management vents",
      "Module slot assembly",
      "Locking door mechanism",
    ],
    salientFeatures: [
      "IEC61439 standard compliance.",
      "Tamper-evident construction.",
      "DIN rail and wall-mount options.",
      "4-module expansion capacity.",
      "Thermal vent design.",
    ],
    scopeOfWork: [
      "Enclosure Design per IEC Standards",
      "Tamper Feature Integration",
      "DIN Rail Compatibility Design",
      "Thermal Analysis",
      "Production Documentation",
    ],
  },

  {
    serialNumber: 16,
    id: "iot-gateway",
    title: "IoT Gateway",
    category: "IoT Connectivity Solutions",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/iot_gateway/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/iot_gateway/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/iot_gateway/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/iot_gateway/1.4.png",
    ],
    features: [
      "Sensor aggregation",
      "Wireless and wired connectivity",
      "Cloud platform integration",
      "Remote device monitoring",
      "Secure data transmission",
      "Firmware OTA updates",
    ],
    summary:
      "Smart IoT gateway designed for sensor aggregation, secure communication, and cloud integration to simplify large-scale remote monitoring and connected deployments.",
    importantParts: [
      "Microprocessor Unit",
      "Wi-Fi / LTE Module",
      "Sensor Interface Ports",
      "Cloud Communication Engine",
      "Power Management Circuit",
      "Secure Boot Controller",
    ],
    salientFeatures: [
      "Supports multiple sensor protocols.",
      "Secure encrypted cloud communication.",
      "Remote monitoring and diagnostics.",
      "Over-the-air firmware updates.",
      "Reliable field deployment architecture.",
      "Scalable for multi-device installations.",
    ],
    scopeOfWork: [
      "Gateway Circuit Design",
      "Wireless Connectivity Integration",
      "Sensor Interface Development",
      "Cloud Platform Setup",
      "Security Implementation",
      "Validation and Field Testing",
    ],
  },

  {
    serialNumber: 17,
    id: "obd-v4-system",
    title: "OBD V4 Smart Diagnostic Unit",
    category: "Automotive Embedded Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD2/OBD_V4_RENDER_23_NOV_2024_MG2_2.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD2/OBD_V4_RENDER_23_NOV_2024_MG2_2.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD2/OBD_V4_RENDER_23_NOV_2024_MG2_3.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD2/OBD_V4_RENDER_23_NOV_2024_MG2_3.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/OBD2/OBD_V4_RENDER_23_NOV_2024_MG2_4.1.png",
    ],
    features: [
      "Real-time vehicle diagnostics",
      "Engine fault code detection",
      "CAN and OBD-II communication",
      "Live sensor data monitoring",
      "Cloud connectivity",
      "Remote firmware updates",
    ],
    summary:
      "Advanced OBD V4 smart diagnostic unit designed for real-time vehicle health monitoring, fault detection, and connected fleet diagnostics with secure cloud integration.",
    importantParts: [
      "OBD-II Interface",
      "CAN Communication Module",
      "Microcontroller Unit",
      "LTE / Wi-Fi Connectivity Module",
      "Power Management Circuit",
      "Diagnostic Processing Engine",
    ],
    salientFeatures: [
      "Supports standard OBD-II and CAN protocols.",
      "Real-time DTC fault code detection.",
      "Live engine and sensor parameter monitoring.",
      "Remote diagnostics through cloud platform.",
      "OTA firmware update capability.",
      "Compact automotive-grade rugged design.",
    ],
    scopeOfWork: [
      "OBD Hardware Design",
      "CAN Protocol Integration",
      "Diagnostic Firmware Development",
      "Cloud Connectivity Implementation",
      "Remote Monitoring Dashboard",
      "Testing and Automotive Validation",
    ],
  },
  {
    serialNumber: 18,
    id: "footswitch",
    title: "Footswitch",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.10.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.11.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.12.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.13.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.14.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.7.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.8.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/footswitch/FOOTSWITCH_27_APR_2026_S1.9.png",
    ],
    rotatedImages: {},
    features: [
      "Ergonomic industrial footswitch design",
      "Durable pedal actuation mechanism",
      "Heavy-duty enclosure construction",
      "Anti-slip surface design",
      "Reliable switching performance",
      "Compact and robust assembly",
    ],
    summary:
      "A mechanically robust industrial footswitch designed for reliable hands-free control in demanding operational environments.",
    importantParts: [
      "Pedal assembly",
      "Spring return mechanism",
      "Switch actuator",
      "Protective enclosure",
      "Anti-slip base",
      "Cable interface housing",
    ],
    salientFeatures: [
      "Ergonomic pedal operation",
      "High durability for industrial usage",
      "Stable anti-slip base structure",
      "Reliable long-life switching performance",
    ],
    scopeOfWork: [
      "Concept Design",
      "Mechanical CAD Design",
      "Enclosure Development",
      "Prototype Validation",
      "Manufacturing Support",
    ],
  },

  {
    serialNumber: 20,
    id: "mega-watt-charging-station",
    title: "Mega Watt Charging Station",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.58.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.59.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.61.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S2.65.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S3.66.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/MCS/MCS_ASSM_RENDER_S3.67.png",
    ],
    rotatedImages: {},
    features: [
      "Complex mechanical assembly system",
      "Precision-fit component structure",
      "High-strength frame design",
      "Assembly optimization",
      "Modular construction approach",
      "Manufacturing-ready configuration",
    ],
    summary:
      "A precision-engineered mechanical assembly system designed for structural stability, modular integration, and manufacturing efficiency.",
    importantParts: [
      "Primary support frame",
      "Assembly brackets",
      "Structural fasteners",
      "Load-bearing joints",
      "Mounting supports",
      "Protective outer frame",
    ],
    salientFeatures: [
      "Modular assembly architecture",
      "High structural strength",
      "Precision fitment across components",
      "Production-friendly mechanical design",
    ],
    scopeOfWork: [
      "System Assembly Design",
      "Mechanical CAD Modeling",
      "Tolerance Analysis",
      "Prototype Testing",
      "Production Engineering Support",
    ],
  },
  {
    serialNumber: 23,
    id: "600kg-cable-tension-measurement-system",
    title: "600Kg Cable Tension Measurement System",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.10.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.11.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.6.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.7.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.9.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/tensionmeter/TM450LB_RENDERING_28_MAR_2025_S1.1png.png",
    ],
    rotatedImages: {},
    features: [
      "Industrial tension measurement device",
      "Precision force monitoring design",
      "Heavy-duty structural body",
      "Portable inspection-ready form factor",
      "High-load handling capability",
      "Reliable calibration support",
    ],
    summary:
      "A rugged tension meter designed for precise industrial force measurement with durable construction and reliable field performance.",
    importantParts: [
      "Load sensing frame",
      "Measurement body",
      "Calibration mechanism",
      "Display housing",
      "Mounting support structure",
      "Protective outer casing",
    ],
    salientFeatures: [
      "High-precision force measurement",
      "Strong industrial-grade construction",
      "Portable field operation design",
      "Reliable calibration stability",
    ],
    scopeOfWork: [
      "Mechanical Product Design",
      "Structural Analysis",
      "CAD Development",
      "Prototype Validation",
      "Production Support",
    ],
  },

  {
    serialNumber: 24,
    id: "gimbal",
    title: "4-Axis Gimbal",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/GIMBAL/GIMBAL_4_AXIS.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/GIMBAL/GIMBAL_4_AXIS.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/GIMBAL/GIMBAL_4_AXIS.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/GIMBAL/GIMBAL_4_AXIS.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/GIMBAL/Gimble.mp4",
    ],
    rotatedImages: {},
    features: [
      "4-axis stabilization mechanism",
      "Precision rotational joints",
      "Lightweight structural design",
      "High dynamic balance performance",
      "Smooth motion control integration",
      "Robust mechanical frame",
    ],
    summary:
      "A precision-engineered 4-axis gimbal system designed for smooth stabilization, dynamic balancing, and high-performance motion control applications.",
    importantParts: [
      "Rotational joint assemblies",
      "Motor mounting brackets",
      "Stabilization frame",
      "Bearing supports",
      "Axis coupling elements",
      "Structural base plate",
    ],
    salientFeatures: [
      "High-precision multi-axis stabilization",
      "Lightweight and rigid structure",
      "Smooth rotational motion control",
      "Reliable mechanical balancing",
    ],
    scopeOfWork: [
      "Mechanical System Design",
      "CAD Modeling",
      "Motion Analysis",
      "Prototype Development",
      "Assembly Validation",
    ],
  },

  {
    serialNumber: 25,
    id: "industrial-camera-controller-unit",
    title: "Industrial Camera Controller Unit",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/IDOCK/FRIZB_IDOCK_RENDER_02_MAY_2026_S1.15.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/IDOCK/FRIZB_IDOCK_RENDER_02_MAY_2026_S1.17.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/IDOCK/FRIZB_IDOCK_RENDER_02_MAY_2026_S1.18.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/IDOCK/FRIZB_IDOCK_RENDER_02_MAY_2026_S1.19.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/IDOCK/FRIZB_IDOCK_RENDER_02_MAY_2026_S1.20.png",
    ],
    rotatedImages: {},
    features: [
      "Compact docking station design",
      "Device alignment and locking mechanism",
      "Cable management integration",
      "Robust enclosure structure",
      "User-friendly insertion design",
      "Stable base support",
    ],
    summary:
      "A compact docking station designed for secure device placement, efficient cable management, and reliable everyday usage.",
    importantParts: [
      "Docking slot assembly",
      "Alignment guides",
      "Base support structure",
      "Cable routing channels",
      "Protective housing",
      "Connector interface zone",
    ],
    salientFeatures: [
      "Secure and stable docking",
      "Compact ergonomic design",
      "Integrated cable management",
      "Durable enclosure construction",
    ],
    scopeOfWork: [
      "Product Design",
      "Mechanical CAD Development",
      "Ergonomic Optimization",
      "Prototype Testing",
      "Manufacturing Support",
    ],
  },

  {
    serialNumber: 26,
    id: "pc-oxy",
    title: "PC & Oxygen Assembly",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/PC&OXY/OXY_ASSY_RENDER_02_MAY_2026_S1.25.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/PC&OXY/OXY_ASSY_RENDER_02_MAY_2026_S1.26.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/PC&OXY/OXY_ASSY_RENDER_02_MAY_2026_S1.27.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/PC&OXY/OXY_ASSY_RENDER_02_MAY_2026_S1.28.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/PC&OXY/PC_ASSY_RENDER_02_MAY_2026_S1.23.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/PC&OXY/PC_ASSY_RENDER_02_MAY_2026_S1.24.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/PC&OXY/PC_ASSY_RENDER_02_MAY_2026_S1.32.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/PC&OXY/PC_OXY_ASSY_RENDER_02_MAY_2026_S1.31.png",
    ],
    rotatedImages: {},
    features: [
      "Integrated dual-system assembly design",
      "Robust enclosure and mounting structure",
      "Efficient internal component layout",
      "Thermal and airflow considerations",
      "Serviceable modular design",
      "Industrial-grade build quality",
    ],
    summary:
      "A combined PC and oxygen system assembly engineered for efficient integration, structural stability, and service-friendly design.",
    importantParts: [
      "Main enclosure frame",
      "Component mounting brackets",
      "Airflow channels",
      "Internal support structure",
      "Access panels",
      "Connector interface zones",
    ],
    salientFeatures: [
      "Integrated multi-system assembly",
      "Efficient thermal and airflow design",
      "Service-friendly modular structure",
      "Robust industrial construction",
    ],
    scopeOfWork: [
      "System Integration Design",
      "Mechanical CAD Modeling",
      "Thermal Considerations",
      "Prototype Validation",
      "Production Support",
    ],
  },

  {
    serialNumber: 27,
    id: "cable-tension-measurement-system",
    title: "Cable Tension Measurement System",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/TENSIONMETER_SMALL/TENSIONMETER_SENSOR_UNIT_28_APR_2026_S1.15.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/TENSIONMETER_SMALL/TENSIONMETER_SENSOR_UNIT_28_APR_2026_S1.16.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/TENSIONMETER_SMALL/TENSIONMETER_SENSOR_UNIT_28_APR_2026_S1.17.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/TENSIONMETER_SMALL/TENSIONMETER_SENSOR_UNIT_28_APR_2026_S1.18.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/TENSIONMETER_SMALL/TENSIONMETER_SENSOR_UNIT_28_APR_2026_S1.19.png",
    ],
    rotatedImages: {},
    features: [
      "Compact tension sensing unit design",
      "Precision mechanical housing",
      "Sensor integration support",
      "Lightweight structural body",
      "Portable inspection form factor",
      "Durable enclosure design",
    ],
    summary:
      "A compact tension meter sensor unit designed for precision measurement, portability, and reliable field usage.",
    importantParts: [
      "Sensor housing",
      "Load transfer structure",
      "Protective casing",
      "Mounting interface",
      "Internal support frame",
      "Connector interface",
    ],
    salientFeatures: [
      "Compact and portable design",
      "Precision measurement support",
      "Durable enclosure construction",
      "Reliable field performance",
    ],
    scopeOfWork: [
      "Mechanical Product Design",
      "CAD Modeling",
      "Sensor Integration Design",
      "Prototype Testing",
      "Manufacturing Support",
    ],
  },
  {
    serialNumber: 5,
    id: "inline-moisture-meter",
    title: "Inline Moisture Meter",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.21.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.19.png",
    ],
    features: [
      "Continuous PPG and SpO₂ biometric sensing",
      "Low-profile wrist-worn enclosure under 11 mm thick",
      "Qi wireless inductive charging",
      "5-day battery life with always-on display mode",
      "Interchangeable silicone strap system",
      "IPX7 water-resistant construction",
    ],
    summary:
      "A compact wrist-worn health monitor designed for continuous patient monitoring in both clinical and home settings. The ultra-slim form factor conceals the sensor array and battery within an 11 mm profile. Industrial design focused on comfort-first strap geometry, a scratch-resistant mineral glass lens, and a wireless charging surface that is flush with the underside of the device for one-hand dock placement.",
    importantParts: [
      "Mineral glass display lens",
      "Aluminium mid-frame with integrated antenna keep-out",
      "Custom silicone strap with quick-release lug",
      "Optical PPG / SpO₂ sensor window",
      "Inductive charging coil housing",
      "Haptic feedback motor mount",
    ],
    salientFeatures: [
      "Sub-11 mm total thickness for all-day comfort.",
      "Continuous 72-hour biometric monitoring.",
      "Qi wireless charging — no exposed contacts.",
      "IPX7 rated for swimming and showering.",
      "Interchangeable strap system for clinical and consumer use.",
      "Scratch-resistant mineral glass lens.",
    ],
    scopeOfWork: [
      "Wearable concept design and CMF",
      "Ergonomic wrist-geometry study",
      "3D CAD and DFM for injection moulding",
      "Strap and clasp mechanism design",
      "Prototype build and fit evaluation",
      "IP rating compliance review",
    ],
  },
  {
    serialNumber: 6,
    id: "desktop-moisture-meter",
    title: "Desktop Moisture Meter",
    category: "Industrial Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/industrial/paddy_moisture/PADDY_S1.6.png",
    ],
    features: [
      "IP67 and MIL-STD-810G rated enclosure",
      "Transflective LCD for sunlight-readable operation",
      "Reinforced TPE over-mould drop protection",
      "Large tactile buttons operable with thick gloves",
      "3.6 Ah Li-Ion battery with hot-swap capability",
      "Integrated probe storage and belt-clip holster",
    ],
    summary:
      "A ruggedised portable tester for electrical field diagnostics, engineered to survive harsh outdoor and industrial environments. The reinforced over-mould body absorbs 1.8 m drop impacts while the transflective display remains readable in direct sunlight. The control layout was validated with field technicians to ensure all primary functions are accessible single-handed, with large glove-safe buttons and a recessed joystick navigation cluster.",
    importantParts: [
      "PC/ABS primary shell with integral stiffening ribs",
      "TPE 1.8 m drop-rated over-mould frame",
      "Transflective 3.5″ display with gorilla glass",
      "IP67-sealed probe and power port bay",
      "Hot-swap 3.6 Ah Li-Ion battery system",
      "Rubberised tactile dome keypad",
    ],
    salientFeatures: [
      "IP67 and MIL-STD-810G certified.",
      "1.8 m drop-test compliant.",
      "Transflective display readable in full sunlight.",
      "All functions accessible single-handed.",
      "Hot-swap battery for uninterrupted field operation.",
      "Integrated test-lead storage reduces accessory loss.",
    ],
    scopeOfWork: [
      "Ruggedised industrial design concepting",
      "Drop and ingress protection engineering",
      "3D CAD surfacing and assembly modelling",
      "Field-technician usability study",
      "Prototype drop and environmental testing",
      "MIL-STD compliance documentation",
    ],
  },
  {
    id: "stellar",
    title: "Stellar",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/stellar/STELLAR_RENDER_07_MAY_2026_S1.4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/stellar/STELLAR_RENDER_07_MAY_2026_S1.5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/stellar/STELLAR_RENDER_07_MAY_2026_S1.6.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/stellar/STELLAR_RENDER_07_MAY_2026_S1.7.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/stellar/STELLAR_RENDER_07_MAY_2026_S1.8.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/stellar/STELLAR_RENDER_07_MAY_2026_S1.9.png",
    ],
    rotatedImages: {},
    features: [
      "Advanced industrial enclosure design",
      "Precision mechanical assembly",
      "Compact structural integration",
      "Thermal-aware enclosure layout",
      "Robust mounting architecture",
      "Modern industrial product aesthetics",
    ],
    summary:
      "Stellar is a precision-engineered mechanical system designed for robust structural integration, thermal efficiency, and reliable industrial deployment.",
    importantParts: [
      "Main enclosure body",
      "Internal mounting structures",
      "Ventilation and airflow sections",
      "Protective outer casing",
      "Connector access regions",
      "Structural support framework",
    ],
    salientFeatures: [
      "Compact and robust mechanical architecture",
      "Thermally optimized enclosure design",
      "Industrial-grade structural stability",
      "Clean and modern product integration",
    ],
    scopeOfWork: [
      "Industrial Product Design",
      "Mechanical CAD Modeling",
      "Structural Design Validation",
      "Prototype Development",
      "Manufacturing Support",
    ],
  },
  {
    id: "ecl-fuel-cell-generator",
    title: "ECL Fuel Cell Generator",
    category: "Mechanical Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ecl_fuel_cell/ECL_FUEL_CELL_GENERATOR_RENDER_08_MAY_2026_S1.10.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ecl_fuel_cell/ECL_FUEL_CELL_GENERATOR_RENDER_08_MAY_2026_S1.11.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ecl_fuel_cell/ECL_FUEL_CELL_GENERATOR_RENDER_08_MAY_2026_S1.12.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ecl_fuel_cell/ECL_FUEL_CELL_GENERATOR_RENDER_08_MAY_2026_S1.13.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ecl_fuel_cell/ECL_FUEL_CELL_GENERATOR_RENDER_08_MAY_2026_S1.15.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ecl_fuel_cell/ECL_FUEL_CELL_GENERATOR_RENDER_08_MAY_2026_S1.18.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ecl_fuel_cell/ECL_FUEL_CELL_GENERATOR_RENDER_08_MAY_2026_S1.19.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ecl_fuel_cell/ECL_FUEL_CELL_GENERATOR_RENDER_08_MAY_2026_S1.20.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ecl_fuel_cell/ECL_FUEL_CELL_GENERATOR_RENDER_08_MAY_2026_S1.21.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/mechanical/ecl_fuel_cell/ECL_FUEL_CELL_GENERATOR_RENDER_08_MAY_2026_S1.22.png",
    ],
    rotatedImages: {},
    features: [
      "Fuel cell generator mechanical assembly",
      "Industrial-grade structural enclosure",
      "Thermal and airflow optimized design",
      "Modular subsystem integration",
      "Heavy-duty mounting architecture",
      "High-efficiency cooling layout",
    ],
    summary:
      "ECL Fuel Cell Generator is a mechanically engineered power system platform designed for efficient thermal management, modular integration, and reliable industrial operation.",
    importantParts: [
      "Fuel cell enclosure assembly",
      "Thermal airflow channels",
      "Structural support frame",
      "Cooling and ventilation sections",
      "Power subsystem mounting brackets",
      "Industrial protective casing",
    ],
    salientFeatures: [
      "Robust industrial mechanical architecture",
      "Thermally optimized enclosure system",
      "Modular fuel cell integration",
      "Reliable heavy-duty structural design",
    ],
    scopeOfWork: [
      "Mechanical System Design",
      "Industrial CAD Modeling",
      "Thermal and Airflow Optimization",
      "Prototype Validation",
      "Manufacturing Support",
    ],
  },
];

// {
//   id: "qsafe-tilt-sensor",
//   title: "QSafe Tilt Sensor",
//   category: "Mechanical Design",
//   images: [
//     "/case-studies/mechanicalCaseStudies/6/QSAFE_TILT_SENSOR_RENDER_23_DEC_2023.16.png",
//     "/case-studies/mechanicalCaseStudies/6/QSAFE_TILT_SENSOR_RENDER_23_DEC_2023.17.png",
//     "/case-studies/mechanicalCaseStudies/6/QSAFE_TILT_SENSOR_RENDER_23_DEC_2023.20.png",
//   ],
//   features: [
//     "Sealed industrial enclosure with flanged mounting base",
//     "Power button and status LED for field diagnostics",
//     "IP-rated construction for outdoor and industrial use",
//     "Four-point flange mounting for structural installations",
//     "UV-stable grey ABS construction",
//     "Compact form factor for pole and surface mounting",
//   ],
//   summary:
//     "A ruggedised tilt sensor enclosure branded QSafe, designed for structural monitoring and safety applications in outdoor and industrial environments. The sealed grey ABS enclosure features a flanged four-point mounting base for secure attachment to poles, walls, and structural members. A front-panel power button and green status LED provide quick field diagnostics without requiring a connected display. The IP-rated construction ensures reliable operation in rain, dust, and temperature extremes.",
//   importantParts: [
//     "UV-stable ABS enclosure shell",
//     "Flanged four-point mounting base",
//     "Sealed power button assembly",
//     "Status LED indicator module",
//     "Internal gasket for IP-rated sealing",
//     "PCB and battery retention features",
//   ],
//   salientFeatures: [
//     "IP-rated sealed enclosure for outdoor deployment.",
//     "Four-point flange mounting for structural installations.",
//     "Front-panel power button and status LED.",
//     "UV-stable materials for extended sun exposure.",
//     "Compact form factor for unobtrusive installation.",
//     "DFM-approved geometry for production tooling.",
//   ],
//   scopeOfWork: [
//     "Enclosure concept design and form exploration",
//     "Mounting bracket and flange design",
//     "3D CAD modelling and detailing",
//     "Gasket and sealing strategy for IP compliance",
//     "Design-for-manufacture review",
//     "Prototype build and environmental testing",
//   ],
// },
