import { CaseStudy } from "../../types/case-study";

// ─── PCB Design ───────────────────────────────────────────────────────────────
export const pcbCaseStudiesData: CaseStudy[] = [
  {
    id: "medical-sensing-board",
    title: "Innovide",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/innovide/INNOVIDE_SIG123.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/innovide/INNOVIDE_SIG56.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/innovide/INNOVIDE_SIG123.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/innovide/INNOVIDE_SIG123456.svg",
    ],
    rotatedImages: { 0: 90, 1: 90, 2: 90, 3: 90 },
    features: [
      "Medical sensing PCB board",
      "High-precision analog front-end",
      "Multi-channel sensor interface",
      "Signal conditioning circuits",
      "Low-noise design",
      "Medical-grade certification path",
    ],
    summary:
      "Medical sensing PCB featuring high-precision analog signal conditioning for multi-channel biometric and environmental monitoring applications.",
    importantParts: [
      "Precision instrumentation amplifiers",
      "Multi-channel ADC",
      "Analog filter circuits",
      "Isolation transformers",
      "Shielded signal paths",
      "Low-noise voltage references",
    ],
    salientFeatures: [
      "High-precision analog signal conditioning.",
      "Multi-channel sensor interface capability.",
      "Low-noise design for accurate measurements.",
      "Medical-grade component selection.",
    ],
    scopeOfWork: [
      "Analog Circuit Design",
      "PCB Layout Design",
      "Signal Integrity Analysis",
      "Testing and Validation",
      "Medical Compliance Review",
    ],
  },
  {
    id: "iot-gateway-pcb",
    title: "IoT Gateway PCB",
    category: "PCB Design",
    images: [
      "/case-studies/PCB/ALPHION/ALPHION-AOLT-PR1_SIG12.svg",
      "/case-studies/PCB/ALPHION/ALPHION-AOLT-PR1_SIG345.svg",
      "/case-studies/PCB/ALPHION/ALPHION-AOLT-PR1_SIG678.svg",
      "/case-studies/PCB/ALPHION/ALPHION-AOLT-PR1_SIG12345678.svg",
    ],
    features: [
      "IoT gateway main board",
      "Multiple wireless protocol support",
      "Ethernet and USB interfaces",
      "Power management circuitry",
      "Compact form factor",
      "Cloud connectivity",
    ],
    summary:
      "IoT gateway PCB supporting multiple wireless protocols and cloud connectivity for smart home and industrial IoT applications.",
    importantParts: [
      "Multi-radio module",
      "Ethernet controller",
      "USB host/device controller",
      "Power management ICs",
      "Memory interface",
      "Environmental sensors",
    ],
    salientFeatures: [
      "Support for multiple wireless protocols.",
      "Integrated Ethernet and USB interfaces.",
      "Optimized power management for extended operation.",
      "Cloud-ready firmware platform.",
    ],
    scopeOfWork: [
      "Schematic Design",
      "PCB Layout Design",
      "Hardware Integration",
      "Firmware Development",
      "Testing and Validation",
    ],
  },
  {
    id: "high-speed-data-interface",
    title: "High-Speed Data Interface",
    category: "PCB Design",
    images: [
      "/case-studies/PCB/PCB-0541/PCB-0541-00_BRD_PR_SIG12.svg",
      "/case-studies/PCB/PCB-0541/PCB-0541-00_BRD_PR_SIG34.svg",
      "/case-studies/PCB/PCB-0541/PCB-0541-00_BRD_PR_SIG1234.svg",
      "/case-studies/PCB/PCB-0541/PCB-0541-00_BRD_PR_TB.svg",
    ],
    features: [
      "High-speed digital interface board",
      "PCIe and DDR3 support",
      "Controlled impedance routing",
      "Signal integrity optimization",
      "Compact high-density layout",
      "Multi-layer design",
    ],
    summary:
      "High-speed data interface PCB featuring PCIe and DDR3 connectivity with advanced signal integrity management for data-intensive applications.",
    importantParts: [
      "High-speed connector interface",
      "PCIe retimer/repeater circuits",
      "DDR3 termination network",
      "Precision voltage references",
      "Signal conditioning buffers",
      "Shielded routing",
    ],
    salientFeatures: [
      "High-speed PCIe and DDR3 support.",
      "Controlled impedance for signal integrity.",
      "Compact high-density layout design.",
      "Advanced crosstalk minimization.",
    ],
    scopeOfWork: [
      "High-speed Design",
      "Signal Integrity Analysis",
      "PCB Layout Design",
      "Impedance Tuning",
      "Testing and Validation",
    ],
  },
  {
    id: "portable-ev-charger-pcb",
    title: "Industrial Controller",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lucas_tvs/LUCAS TVS_PR1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lucas_tvs/LUCAS TVS_PR1_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lucas_tvs/LUCAS TVS_PR1_TOP.svg",
    ],
    rotatedImages: { 0: 90, 1: 90, 2: 90 },
    features: [
      "Industrial control board design",
      "Multi-layer PCB with high current traces",
      "Power delivery network optimization",
      "Industrial connectors and interfaces",
      "Thermal management design",
      "DFM-optimized layout",
    ],
    summary:
      "Industrial controller PCB designed for robust manufacturing and process control applications with high-current power distribution and optimized thermal management.",
    importantParts: [
      "High-current power distribution traces",
      "Industrial-grade connectors",
      "Thermal vias and copper pour",
      "EMI filtering components",
      "Precision resistor networks",
      "Industrial power supply module",
    ],
    salientFeatures: [
      "Optimized for high-current distribution.",
      "Enhanced thermal management with copper pour.",
      "Multi-layer design for signal integrity.",
      "DFM-reviewed for high-volume production.",
    ],
    scopeOfWork: [
      "Schematic Design",
      "PCB Layout Design",
      "Thermal Analysis",
      "DFM Review",
      "Testing and Validation",
    ],
  },
  {
    id: "aerospace-pcb",
    title: "Aerospace PCB",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/OBD/OBD_PR1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/OBD/OBD_PR1_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/OBD/OBD_PR1_TOP.svg",
    ],
    rotatedImages: { 0: 90, 1: 90, 2: 90 },
    features: [
      "Aerospace-grade PCB design",
      "High-speed digital interfaces (LVDS, SPI, I2C)",
      "8-layer controlled impedance stackup",
      "High-density BGA packages",
      "2312 total pin count",
      "Stringent reliability requirements",
    ],
    summary:
      "Aerospace PCB featuring high-density BGAs, multiple high-speed interfaces, and controlled impedance routing for mission-critical applications.",
    importantParts: [
      "135-pin BGA packages",
      "High-speed signal routing",
      "Controlled impedance traces",
      "Aerospace-grade components",
      "EMI/EMC shielding",
      "Thermal management system",
    ],
    salientFeatures: [
      "8-layer PCB with controlled impedance.",
      "Support for LVDS, SPI, and I2C protocols.",
      "High pin count (2312) for complex systems.",
      "Aerospace reliability standards compliance.",
    ],
    scopeOfWork: [
      "High-speed Design",
      "Signal Integrity Analysis",
      "PCB Layout Design",
      "Impedance Tuning",
      "Testing and Validation",
    ],
  },
  {
    id: "automotive-obd-pcb",
    title: "Automotive OBD",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_SIG1.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_SIG12.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/1.1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/1.2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_SIG1.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/1.3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_SIG12.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_SIG2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_TOP.svg",
    ],
    rotatedImages: { 0: 90, 1: 90, 2: 90, 3: 90 },
    features: [
      "Automotive OBD2 interface board",
      "Multi-protocol support (UART, I2C, SPI)",
      "4-layer PCB design",
      "EMC/EMI hardening for automotive",
      "997 total pin count",
      "LQFP 64 packages",
    ],
    summary:
      "Automotive OBD2 PCB enabling multiple communication protocols with automotive-grade EMC hardening for vehicle diagnostics.",
    importantParts: [
      "LQFP 64 microcontroller package",
      "Automotive OBD2 connector",
      "ESD protection circuits",
      "CAN transceiver",
      "Voltage regulation for automotive supply",
      "Diagnostic LED drivers",
    ],
    salientFeatures: [
      "Multi-protocol support (UART, I2C, SPI).",
      "4-layer automotive PCB stackup.",
      "High EMC/EMI immunity for in-vehicle operation.",
      "Optimized for diagnostics and data logging.",
    ],
    scopeOfWork: [
      "Schematic Design",
      "PCB Layout Design",
      "EMC Compliance",
      "Testing and Validation",
      "Automotive Certification",
    ],
  },
  // {
  //   id: "ubihub-pr1",
  //   title: "UBIHUB PR1",
  //   category: "PCB Design",
  //   images: [

  //   ],
  //   rotatedImages: {},
  //   features: [
  //     "Industrial IoT hub PCB board",
  //     "Multi-layer high-density PCB design",
  //     "Signal integrity optimized routing",
  //     "Power management and distribution",
  //     "Robust communication interface support",
  //     "Industrial-grade reliability design",
  //   ],
  //   summary:
  //     "UBIHUB PR1 is an industrial IoT hub PCB designed for reliable communication, signal integrity, and robust power management in connected embedded applications.",
  //   importantParts: [
  //     "Microcontroller processing unit",
  //     "Communication interface modules",
  //     "Power regulation circuits",
  //     "High-speed signal routing layers",
  //     "Protection and filtering components",
  //     "Industrial-grade connectors",
  //   ],
  //   salientFeatures: [
  //     "Multi-layer PCB optimized for industrial environments.",
  //     "Reliable power distribution and regulation design.",
  //     "Signal integrity focused routing for stable communication.",
  //     "Supports multiple embedded communication interfaces.",
  //   ],
  //   scopeOfWork: [
  //     "System Architecture Design",
  //     "PCB Layout Design",
  //     "Power Integrity Analysis",
  //     "Signal Integrity Validation",
  //     "Prototype Testing and Validation",
  //   ],
  // },
  {
    id: "fedarant-pcb-top-layer",
    title: "Fedarant PCB – Top Layer",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/seat_sensor_signal/P01201CB2-SEATSENSOR-SINGLE_PR1_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/seat_sensor_signal/P01201CB2-SEATSENSOR-SINGLE_PR1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/seat_sensor_signal/P01201CB2-SEATSENSOR-SINGLE_PR1_TB.svg",

      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/seat_sensor_flux/SEAT-SENSOR-21DEC2023-QMAX.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/seat_sensor_flux/SEAT-SENSOR-TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/seat_sensor_flux/SEAT-SENSOR-TOP.svg",
    ],
    features: [
      "Fedarant IoT Gateway – Top Layer View",
      "Multi-radio PCB (Wi-Fi / BLE 5.0 / ZigBee)",
      "Qualcomm QCA4020 SoC layout",
      "RF antenna keep-out zones",
      "4-layer controlled impedance stackup",
      "Compact 48 mm × 42 mm footprint",
    ],
    summary:
      "Top-layer view of the Fedarant IoT Micro Gateway PCB, highlighting the Qualcomm QCA4020 SoC placement, antenna keep-out zones, and the compact routing strategy that fits tri-radio connectivity into a 48 mm × 42 mm footprint.",
    importantParts: [
      "Qualcomm QCA4020 tri-radio SoC",
      "Skyworks RF Power Amplifier",
      "STMicro low-drop voltage regulators",
      "Integrated antenna structures",
    ],
    salientFeatures: [
      "Compact 48 mm × 42 mm PCB footprint.",
      "Dedicated RF keep-out zones for antenna performance.",
      "4-layer controlled impedance stackup.",
      "Clean power and ground separation for noise immunity.",
    ],
    scopeOfWork: [
      "Schematic entry and net-list validation",
      "PCB layout and top-layer component placement",
      "Antenna keep-out zone definition",
      "Signal integrity and EMC review",
      "PCB fabrication and assembly coordination",
    ],
  },
  {
    id: "arc-detector",
    title: "Arc Detector",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/arc_detector/AFDD-REV0P1_ARC DETECTOR_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/arc_detector/AFDD-REV0P1_ARC DETECTOR_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/arc_detector/AFDD-REV0P1_ARC DETECTOR_SP.svg",

      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/arc_detector/AFDD-REV0P1_ARC DETECTOR_TOP.svg",
    ],
    rotatedImages: {},
    features: [
      "Arc fault detection PCB design",
      "High-reliability protection circuitry",
      "Signal processing for fault detection",
      "Compact multi-layer board design",
      "Power monitoring integration",
      "Industrial-grade safety compliance",
    ],
    summary:
      "A high-reliability arc detector PCB developed for electrical fault detection, safety monitoring, and industrial protection applications.",
    importantParts: [
      "Arc sensing circuitry",
      "Signal conditioning stage",
      "Microcontroller unit",
      "Protection components",
      "Power regulation section",
      "Isolation and filtering circuits",
    ],
    salientFeatures: [
      "Fast arc fault detection capability",
      "Reliable industrial safety operation",
      "Compact multi-layer PCB architecture",
      "Integrated protection and monitoring design",
    ],
    scopeOfWork: [
      "Circuit Design",
      "PCB Layout Development",
      "Signal Integrity Analysis",
      "Safety Validation",
      "Prototype Testing",
    ],
  },

  {
    id: "stator-coil",
    title: "Stator Coil",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/stator_coil/STATOR-COIL-LAYER1.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/stator_coil/STATOR-COIL-LAYER2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/stator_coil/STATOR-COIL-TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/stator_coil/STATOR-COIL-TOP.svg",
    ],
    rotatedImages: { 0: 90, 1: 90, 2: 90, 3: 90 },
    features: [
      "High-current stator coil PCB design",
      "Multi-layer copper routing optimization",
      "Thermal management focused layout",
      "Power handling capability enhancement",
      "Electromagnetic performance optimization",
      "Industrial motor control application support",
    ],
    summary:
      "A stator coil PCB engineered for high-current handling, thermal efficiency, and reliable motor control system integration.",
    importantParts: [
      "Heavy copper traces",
      "Power distribution layers",
      "Thermal dissipation zones",
      "Motor drive interface",
      "Connector terminals",
      "High-current routing sections",
    ],
    salientFeatures: [
      "High-current carrying capability",
      "Thermally optimized PCB structure",
      "Reliable motor control integration",
      "Efficient multi-layer copper layout",
    ],
    scopeOfWork: [
      "Power Circuit Design",
      "PCB Layout Optimization",
      "Thermal Analysis",
      "Current Path Validation",
      "Prototype Verification",
    ],
  },

  {
    id: "rugged-obd",
    title: "Rugged OBD",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/rugged_obd/I01256CB1_20JUN2024_RUG_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/rugged_obd/I01256CB1_20JUN2024_RUG_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/rugged_obd/I01256CB1_20JUN2024_RUG_PR1_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/rugged_obd/I01256CB1_20JUN2024_RUG_SIG12.svg",
    ],
    rotatedImages: {},
    features: [
      "Automotive rugged OBD PCB design",
      "Vehicle diagnostic communication support",
      "High-vibration resistant layout",
      "Power protection and filtering",
      "Compact embedded system integration",
      "Automotive-grade reliability standards",
    ],
    summary:
      "A rugged OBD PCB developed for automotive diagnostics, reliable field performance, and stable communication in harsh vehicle environments.",
    importantParts: [
      "OBD communication interface",
      "Microcontroller processing unit",
      "Power protection stage",
      "Signal filtering circuits",
      "Connector interface module",
      "Automotive-grade protection components",
    ],
    salientFeatures: [
      "Reliable automotive diagnostic connectivity",
      "Rugged vibration-resistant PCB structure",
      "Stable power and signal integrity",
      "Compact embedded automotive integration",
    ],
    scopeOfWork: [
      "Automotive Circuit Design",
      "PCB Layout Development",
      "Power Integrity Analysis",
      "Environmental Validation",
      "Prototype Testing",
    ],
  },
  {
    id: "energy-meter",
    title: "Energy Meter",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/energy_meter/P01363MMC1-ENERGY METER_BOT_1.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/energy_meter/P01363MMC1-ENERGY METER_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/energy_meter/P01363MMC1-ENERGY METER_TOP.svg",
    ],
    rotatedImages: { 0: 90, 1: 90, 2: 90, 3: 90 },
    features: [
      "High-accuracy energy metering PCB",
      "Multi-layer compact board design",
      "Precise voltage and current sensing",
      "Stable power measurement circuitry",
      "Signal conditioning for metering accuracy",
      "Compliance-ready industrial design",
    ],
    summary:
      "A precision energy meter PCB designed for accurate power monitoring, efficient signal processing, and reliable long-term performance in metering applications.",
    importantParts: [
      "Energy metering IC",
      "Current sensing circuitry",
      "Voltage divider network",
      "Signal conditioning stage",
      "Power supply section",
      "Communication interface module",
    ],
    salientFeatures: [
      "High-accuracy power measurement",
      "Reliable long-term stability",
      "Compact multi-layer PCB design",
      "Optimized signal conditioning architecture",
    ],
    scopeOfWork: [
      "Circuit Design",
      "PCB Layout Development",
      "Signal Integrity Analysis",
      "Calibration Support",
      "Prototype Testing",
    ],
  },
  {
    id: "fe1600",
    title: "FE1600",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_MODULE_REV-02_PR1_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_closeup/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_MODULE_REV-02_PR1_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_closeup/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_MODULE_REV-02_PR1_SIG123_.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_closeup/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_MODULE_REV-02_PR1_SIG456.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_closeup/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_MODULE_REV-02_PR1_SIG789.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_closeup/5.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_MODULE_REV-02_PR1_SIG101112.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_closeup/6.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/FE1600/FE1600_MODULE_REV-02_PR1_BOT.svg",
    ],
    rotatedImages: {},
    features: [
      "High-density multi-layer PCB design",
      "Advanced signal routing architecture",
      "Optimized power distribution network",
      "High-speed signal integrity support",
      "Industrial-grade PCB reliability",
      "Compact modular layout structure",
    ],
    summary:
      "FE1600 is a high-density PCB platform engineered for reliable signal integrity, modular scalability, and industrial embedded applications.",
    importantParts: [
      "Signal routing layers",
      "Power distribution planes",
      "High-speed interface sections",
      "Ground isolation regions",
      "Connector interfaces",
      "Thermal management zones",
    ],
    salientFeatures: [
      "High-speed signal optimization",
      "Compact modular PCB architecture",
      "Reliable multi-layer stack-up",
      "Industrial-grade routing stability",
    ],
    scopeOfWork: [
      "Circuit Design",
      "PCB Layout Development",
      "Signal Integrity Analysis",
      "Power Integrity Validation",
      "Prototype Testing",
    ],
  },

  {
    id: "lbm",
    title: "LBM",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/LBM/LBM_REV1_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/LBM/LBM_closeup/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/LBM/LBM_REV1SIG1234.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/LBM/LBM_closeup/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/LBM/LBM_REV1SIG5678.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/LBM/LBM_closeup/3.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/LBM/LBM_REV1SIG11121314.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/LBM/LBM_closeup/4.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/LBM/LBM_REV1_BOT.svg",
    ],
    rotatedImages: {},
    features: [
      "Layer-balanced PCB architecture",
      "Optimized signal path routing",
      "Stable multi-layer stack design",
      "Efficient thermal distribution",
      "Compact embedded integration",
      "Reliable manufacturing-ready layout",
    ],
    summary:
      "LBM is a multi-layer PCB solution designed for balanced routing, thermal efficiency, and reliable embedded hardware integration.",
    importantParts: [
      "Signal routing sections",
      "Ground reference planes",
      "Thermal copper layers",
      "Connector interfaces",
      "Power management regions",
      "Embedded control sections",
    ],
    salientFeatures: [
      "Balanced multi-layer PCB design",
      "Optimized thermal performance",
      "Reliable embedded connectivity",
      "Compact routing architecture",
    ],
    scopeOfWork: [
      "PCB Architecture Design",
      "Multi-layer Routing",
      "Thermal Analysis",
      "Signal Integrity Validation",
      "Prototype Verification",
    ],
  },

  {
    id: "lightning",
    title: "Lightning",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lightning/LIGHTNING-PR1_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lightning/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lightning/LIGHTNING-PR1_TP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lightning/2.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lightning/LIGHTNING-PR1_TP2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lightning/LIGHTNING-PR1_BOT.svg",
    ],
    rotatedImages: {},
    features: [
      "High-speed PCB routing design",
      "Lightning-fast signal optimization",
      "Compact embedded board layout",
      "Signal and power isolation strategy",
      "Efficient multi-layer architecture",
      "Industrial-grade PCB stability",
    ],
    summary:
      "Lightning is a high-speed PCB platform focused on efficient signal routing, compact integration, and reliable embedded system performance.",
    importantParts: [
      "High-speed routing channels",
      "Power regulation sections",
      "Signal isolation layers",
      "Embedded controller interface",
      "Ground reference planes",
      "Connector integration areas",
    ],
    salientFeatures: [
      "Optimized high-speed signal paths",
      "Compact embedded PCB layout",
      "Stable multi-layer architecture",
      "Reliable industrial operation",
    ],
    scopeOfWork: [
      "PCB Design",
      "Signal Integrity Analysis",
      "Power Distribution Optimization",
      "Prototype Validation",
      "Manufacturing Support",
    ],
  },

  {
    id: "mx1",
    title: "MX1",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/MX1/Mx1_PR1_TOP.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/MX1/Mx1_PR1_TS1.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/MX1/Mx1_PR1_TS2.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/MX1/Mx1_PR1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/MX1/Mx1_PR1_ALL.svg",
    ],
    rotatedImages: {},
    features: [
      "Compact embedded PCB module",
      "Multi-section signal trace optimization",
      "Integrated power management layout",
      "Reliable layer stack architecture",
      "Efficient routing topology",
      "Scalable hardware platform",
    ],
    summary:
      "MX1 is a compact embedded PCB module engineered for scalable hardware integration, signal stability, and efficient routing performance.",
    importantParts: [
      "Signal trace sections",
      "Power routing layers",
      "Embedded processing region",
      "Ground shielding structure",
      "Connector interfaces",
      "Thermal dissipation zones",
    ],
    salientFeatures: [
      "Compact scalable PCB architecture",
      "Efficient routing topology",
      "Stable embedded hardware integration",
      "Reliable power distribution network",
    ],
    scopeOfWork: [
      "Embedded Hardware Design",
      "PCB Layout Development",
      "Signal Analysis",
      "Power Integrity Validation",
      "Prototype Testing",
    ],
  },

  {
    id: "pegasus",
    title: "Pegasus",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/pegasus/Pegasus_ALL LAYER.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/pegasus/pegasus_closeup/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/pegasus/Pegasus_SIG123.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/pegasus/Pegasus_SIG456.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/pegasus/Pegasus_SIG4678.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/pegasus/Pegasus_ALL LAYER_RS.svg",
    ],
    rotatedImages: {},
    features: [
      "Advanced multi-layer PCB platform",
      "Complex signal routing optimization",
      "High-density interconnect architecture",
      "Efficient thermal management",
      "Embedded systems compatibility",
      "Manufacturing-ready PCB stack-up",
    ],
    summary:
      "Pegasus is a high-density PCB platform designed for advanced signal routing, embedded integration, and reliable industrial-grade performance.",
    importantParts: [
      "Signal integrity routing layers",
      "Power distribution sections",
      "Thermal balancing regions",
      "Connector interface modules",
      "Ground shielding layers",
      "Embedded control circuitry",
    ],
    salientFeatures: [
      "Advanced multi-layer PCB routing",
      "Optimized thermal and signal performance",
      "Reliable embedded integration",
      "Scalable industrial-grade architecture",
    ],
    scopeOfWork: [
      "PCB Stack-up Design",
      "Signal Integrity Analysis",
      "Thermal Optimization",
      "Prototype Validation",
      "Production Support",
    ],
  },

  {
    id: "typheon",
    title: "Typheon",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/typheon/Typhoon_SIG123.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/typheon/typhoon_closeup/1.png",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/typheon/Typhoon_SIG78910.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/typheon/typhoon_closeup/2.png",
    ],
    rotatedImages: {},
    features: [
      "High-speed signal routing PCB",
      "Compact embedded hardware design",
      "Optimized layer distribution",
      "Reliable signal isolation structure",
      "Efficient PCB stack management",
      "Industrial embedded compatibility",
    ],
    summary:
      "Typheon is a compact PCB solution developed for high-speed signal routing, embedded integration, and stable industrial performance.",
    importantParts: [
      "Signal trace routing layers",
      "Embedded interface sections",
      "Ground shielding structure",
      "Power delivery network",
      "Thermal balancing areas",
      "Connector integration zones",
    ],
    salientFeatures: [
      "Reliable high-speed routing",
      "Compact embedded PCB platform",
      "Efficient signal isolation",
      "Stable industrial-grade operation",
    ],
    scopeOfWork: [
      "PCB Layout Design",
      "Signal Integrity Optimization",
      "Thermal Analysis",
      "Prototype Testing",
      "Manufacturing Validation",
    ],
  },
  {
    id: "motor-control-pcb",
    title: "Motor Control PCB",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "Three-phase motor control board",
      "PWM drive circuitry",
      "Current sensing and feedback",
      "Temperature monitoring",
      "Safety shutdown circuits",
      "High-current power stages",
    ],
    summary:
      "Motor control PCB featuring three-phase PWM drive circuitry, current feedback, and comprehensive safety protection for industrial motor control.",
    importantParts: [
      "Power MOSFET or IGBT modules",
      "Gate drive circuitry",
      "Current sensing resistors",
      "Temperature sensors",
      "Flyback protection diodes",
      "High-current traces",
    ],
    salientFeatures: [
      "Three-phase motor support.",
      "Real-time current feedback.",
      "Temperature-based protection.",
      "Smooth PWM control capability.",
    ],
    scopeOfWork: [
      "Power Stage Design",
      "Gate Drive Circuit Design",
      "PCB Layout Design (High-current)",
      "Thermal Management",
      "Testing and Validation",
    ],
  },
];
