import { CaseStudy } from "../../types/case-study";

// ─── PCB Design ───────────────────────────────────────────────────────────────
export const pcbCaseStudiesData: CaseStudy[] = [
  {
    id: "medical-sensing-board",
    title: "Innovide",
    category: "PCB Design",
    images: [
      "/case-studies/PCB/INNOVIDE/INNOVIDE_SIG45.svg",
      "/case-studies/PCB/INNOVIDE/INNOVIDE_SIG56.svg",
      "/case-studies/PCB/INNOVIDE/INNOVIDE_SIG123.svg",
      "/case-studies/PCB/INNOVIDE/INNOVIDE_SIG123456.svg",
    ],
    rotatedImages: { 0: 90, 1: 90, 2: 90, 3: 90 },
    features: [
      "Medical sensing PCB board",
      "High-precision analog front-end",
      "Multi-channel sensor interface",
      "Signal conditioning circuits",
      "Low-noise design",
      "Medical-grade certification path",
    ],
    summary:
      "Medical sensing PCB featuring high-precision analog signal conditioning for multi-channel biometric and environmental monitoring applications.",
    importantParts: [
      "Precision instrumentation amplifiers",
      "Multi-channel ADC",
      "Analog filter circuits",
      "Isolation transformers",
      "Shielded signal paths",
      "Low-noise voltage references",
    ],
    salientFeatures: [
      "High-precision analog signal conditioning.",
      "Multi-channel sensor interface capability.",
      "Low-noise design for accurate measurements.",
      "Medical-grade component selection.",
    ],
    scopeOfWork: [
      "Analog Circuit Design",
      "PCB Layout Design",
      "Signal Integrity Analysis",
      "Testing and Validation",
      "Medical Compliance Review",
    ],
  },
  {
    id: "iot-gateway-pcb",
    title: "IoT Gateway PCB",
    category: "PCB Design",
    images: [
      "/case-studies/PCB/ALPHION/ALPHION-AOLT-PR1_SIG12.svg",
      "/case-studies/PCB/ALPHION/ALPHION-AOLT-PR1_SIG345.svg",
      "/case-studies/PCB/ALPHION/ALPHION-AOLT-PR1_SIG678.svg",
      "/case-studies/PCB/ALPHION/ALPHION-AOLT-PR1_SIG12345678.svg",
    ],
    features: [
      "IoT gateway main board",
      "Multiple wireless protocol support",
      "Ethernet and USB interfaces",
      "Power management circuitry",
      "Compact form factor",
      "Cloud connectivity",
    ],
    summary:
      "IoT gateway PCB supporting multiple wireless protocols and cloud connectivity for smart home and industrial IoT applications.",
    importantParts: [
      "Multi-radio module",
      "Ethernet controller",
      "USB host/device controller",
      "Power management ICs",
      "Memory interface",
      "Environmental sensors",
    ],
    salientFeatures: [
      "Support for multiple wireless protocols.",
      "Integrated Ethernet and USB interfaces.",
      "Optimized power management for extended operation.",
      "Cloud-ready firmware platform.",
    ],
    scopeOfWork: [
      "Schematic Design",
      "PCB Layout Design",
      "Hardware Integration",
      "Firmware Development",
      "Testing and Validation",
    ],
  },
  {
    id: "high-speed-data-interface",
    title: "High-Speed Data Interface",
    category: "PCB Design",
    images: [
      "/case-studies/PCB/PCB-0541/PCB-0541-00_BRD_PR_SIG12.svg",
      "/case-studies/PCB/PCB-0541/PCB-0541-00_BRD_PR_SIG34.svg",
      "/case-studies/PCB/PCB-0541/PCB-0541-00_BRD_PR_SIG1234.svg",
      "/case-studies/PCB/PCB-0541/PCB-0541-00_BRD_PR_TB.svg",
    ],
    features: [
      "High-speed digital interface board",
      "PCIe and DDR3 support",
      "Controlled impedance routing",
      "Signal integrity optimization",
      "Compact high-density layout",
      "Multi-layer design",
    ],
    summary:
      "High-speed data interface PCB featuring PCIe and DDR3 connectivity with advanced signal integrity management for data-intensive applications.",
    importantParts: [
      "High-speed connector interface",
      "PCIe retimer/repeater circuits",
      "DDR3 termination network",
      "Precision voltage references",
      "Signal conditioning buffers",
      "Shielded routing",
    ],
    salientFeatures: [
      "High-speed PCIe and DDR3 support.",
      "Controlled impedance for signal integrity.",
      "Compact high-density layout design.",
      "Advanced crosstalk minimization.",
    ],
    scopeOfWork: [
      "High-speed Design",
      "Signal Integrity Analysis",
      "PCB Layout Design",
      "Impedance Tuning",
      "Testing and Validation",
    ],
  },
  {
    id: "portable-ev-charger-pcb",
    title: "Industrial Controller",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lucas_tvs/LUCAS TVS_PR1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lucas_tvs/LUCAS TVS_PR1_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/lucas_tvs/LUCAS TVS_PR1_TOP.svg",
    ],
    rotatedImages: { 0: 90, 1: 90, 2: 90 },
    features: [
      "Industrial control board design",
      "Multi-layer PCB with high current traces",
      "Power delivery network optimization",
      "Industrial connectors and interfaces",
      "Thermal management design",
      "DFM-optimized layout",
    ],
    summary:
      "Industrial controller PCB designed for robust manufacturing and process control applications with high-current power distribution and optimized thermal management.",
    importantParts: [
      "High-current power distribution traces",
      "Industrial-grade connectors",
      "Thermal vias and copper pour",
      "EMI filtering components",
      "Precision resistor networks",
      "Industrial power supply module",
    ],
    salientFeatures: [
      "Optimized for high-current distribution.",
      "Enhanced thermal management with copper pour.",
      "Multi-layer design for signal integrity.",
      "DFM-reviewed for high-volume production.",
    ],
    scopeOfWork: [
      "Schematic Design",
      "PCB Layout Design",
      "Thermal Analysis",
      "DFM Review",
      "Testing and Validation",
    ],
  },
  {
    id: "aerospace-pcb",
    title: "Aerospace PCB",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/OBD/OBD_PR1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/OBD/OBD_PR1_TB.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/OBD/OBD_PR1_TOP.svg",
    ],
    rotatedImages: { 0: 90, 1: 90, 2: 90 },
    features: [
      "Aerospace-grade PCB design",
      "High-speed digital interfaces (LVDS, SPI, I2C)",
      "8-layer controlled impedance stackup",
      "High-density BGA packages",
      "2312 total pin count",
      "Stringent reliability requirements",
    ],
    summary:
      "Aerospace PCB featuring high-density BGAs, multiple high-speed interfaces, and controlled impedance routing for mission-critical applications.",
    importantParts: [
      "135-pin BGA packages",
      "High-speed signal routing",
      "Controlled impedance traces",
      "Aerospace-grade components",
      "EMI/EMC shielding",
      "Thermal management system",
    ],
    salientFeatures: [
      "8-layer PCB with controlled impedance.",
      "Support for LVDS, SPI, and I2C protocols.",
      "High pin count (2312) for complex systems.",
      "Aerospace reliability standards compliance.",
    ],
    scopeOfWork: [
      "High-speed Design",
      "Signal Integrity Analysis",
      "PCB Layout Design",
      "Impedance Tuning",
      "Testing and Validation",
    ],
  },
  {
    id: "automotive-obd-pcb",
    title: "Automotive OBD",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_BOT.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_SIG1.svg",
      "https://d1yetprhniwywz.cloudfront.net/v2/case-studies/pcb/UBIHUB/UBIHUB_PR1_SIG12.svg",
    ],
    rotatedImages: { 0: 90, 1: 90, 2: 90, 3: 90 },
    features: [
      "Automotive OBD2 interface board",
      "Multi-protocol support (UART, I2C, SPI)",
      "4-layer PCB design",
      "EMC/EMI hardening for automotive",
      "997 total pin count",
      "LQFP 64 packages",
    ],
    summary:
      "Automotive OBD2 PCB enabling multiple communication protocols with automotive-grade EMC hardening for vehicle diagnostics.",
    importantParts: [
      "LQFP 64 microcontroller package",
      "Automotive OBD2 connector",
      "ESD protection circuits",
      "CAN transceiver",
      "Voltage regulation for automotive supply",
      "Diagnostic LED drivers",
    ],
    salientFeatures: [
      "Multi-protocol support (UART, I2C, SPI).",
      "4-layer automotive PCB stackup.",
      "High EMC/EMI immunity for in-vehicle operation.",
      "Optimized for diagnostics and data logging.",
    ],
    scopeOfWork: [
      "Schematic Design",
      "PCB Layout Design",
      "EMC Compliance",
      "Testing and Validation",
      "Automotive Certification",
    ],
  },
  {
    id: "fedarant-pcb-bottom-layer",
    title: "Fedarant PCB – Bottom Layer",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "Fedarant IoT Gateway – Bottom Layer View",
      "Multi-radio PCB (Wi-Fi / BLE 5.0 / ZigBee)",
      "Compact form factor design",
      "High-density SMD placement",
      "Controlled impedance routing",
      "RF-optimised ground planes",
    ],
    summary:
      "Bottom-layer view of the Fedarant IoT Micro Gateway PCB, showcasing the high-density SMD component placement and optimised ground plane strategy that supports simultaneous tri-radio operation across Wi-Fi, BLE 5.0, and ZigBee.",
    importantParts: [
      "Qualcomm QCA4020 tri-radio SoC",
      "Skyworks Wi-Fi Front End Module",
      "Macronix 32 Mb NOR Flash Memory",
      "CUI / Mornsun AC-DC power module",
    ],
    salientFeatures: [
      "High-density bottom-side component placement.",
      "Optimised ground planes for tri-radio RF performance.",
      "Controlled impedance traces for high-speed signals.",
      "Thermal relief vias for efficient heat dissipation.",
    ],
    scopeOfWork: [
      "PCB stack-up definition",
      "Component placement and routing",
      "RF ground plane optimisation",
      "DFM review and fabrication handoff",
    ],
  },
  {
    id: "fedarant-pcb-top-layer",
    title: "Fedarant PCB – Top Layer",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "Fedarant IoT Gateway – Top Layer View",
      "Multi-radio PCB (Wi-Fi / BLE 5.0 / ZigBee)",
      "Qualcomm QCA4020 SoC layout",
      "RF antenna keep-out zones",
      "4-layer controlled impedance stackup",
      "Compact 48 mm × 42 mm footprint",
    ],
    summary:
      "Top-layer view of the Fedarant IoT Micro Gateway PCB, highlighting the Qualcomm QCA4020 SoC placement, antenna keep-out zones, and the compact routing strategy that fits tri-radio connectivity into a 48 mm × 42 mm footprint.",
    importantParts: [
      "Qualcomm QCA4020 tri-radio SoC",
      "Skyworks RF Power Amplifier",
      "STMicro low-drop voltage regulators",
      "Integrated antenna structures",
    ],
    salientFeatures: [
      "Compact 48 mm × 42 mm PCB footprint.",
      "Dedicated RF keep-out zones for antenna performance.",
      "4-layer controlled impedance stackup.",
      "Clean power and ground separation for noise immunity.",
    ],
    scopeOfWork: [
      "Schematic entry and net-list validation",
      "PCB layout and top-layer component placement",
      "Antenna keep-out zone definition",
      "Signal integrity and EMC review",
      "PCB fabrication and assembly coordination",
    ],
  },
  {
    id: "rf-front-end-module",
    title: "RF Front-End Module",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "RF front-end amplifier module",
      "Multi-band support",
      "Impedance matching networks",
      "Harmonic filtering",
      "High efficiency design",
      "Compact integration",
    ],
    summary:
      "RF front-end module featuring multi-band support, impedance matching, and harmonic filtering for wireless communication systems.",
    importantParts: [
      "Power amplifier IC",
      "Low-noise amplifier",
      "RF switches",
      "Matching networks",
      "Filter circuits",
      "RF connectors",
    ],
    salientFeatures: [
      "Multi-band RF coverage.",
      "Optimized impedance matching.",
      "Harmonic and spurious suppression.",
      "High efficiency power amplification.",
    ],
    scopeOfWork: [
      "RF Circuit Design",
      "PCB Layout Design",
      "Impedance Matching",
      "RF Testing and Tuning",
      "Certification Support",
    ],
  },
  {
    id: "power-management-board",
    title: "Power Management Board",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "Multi-rail power distribution board",
      "Voltage regulation for various supply rails",
      "Current monitoring and protection",
      "Thermal management design",
      "Redundancy and failover capability",
      "Industrial power input",
    ],
    summary:
      "Power management PCB providing multi-rail voltage regulation, current monitoring, and protection for complex electronic systems.",
    importantParts: [
      "Multiple buck converter ICs",
      "High-current rectifiers",
      "Bulk and ceramic capacitors",
      "Current sensing resistors",
      "Protection circuits",
      "Thermal management vias",
    ],
    salientFeatures: [
      "Multi-rail voltage output capability.",
      "Individual rail current monitoring.",
      "Fault detection and protection.",
      "Optimized thermal dissipation design.",
    ],
    scopeOfWork: [
      "Power Supply Design",
      "Thermal Analysis",
      "PCB Layout Design",
      "Efficiency Optimization",
      "Testing and Validation",
    ],
  },
  {
    id: "battery-management-system",
    title: "Battery Management System",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "Multi-cell battery management board",
      "Cell balancing circuitry",
      "Voltage and temperature monitoring",
      "Safety protection mechanisms",
      "Fuel gauge integration",
      "Wireless charging support",
    ],
    summary:
      "Battery management system PCB featuring cell balancing, comprehensive monitoring, and safety protection for Li-ion and Li-Po battery packs.",
    importantParts: [
      "Battery management IC",
      "Cell balancing circuits",
      "Temperature sensors",
      "High-side current monitor",
      "Protection MOSFETs",
      "Wireless charging coil",
    ],
    salientFeatures: [
      "Automatic cell balancing.",
      "Comprehensive safety protection.",
      "Real-time state-of-charge monitoring.",
      "Wireless charging integration.",
    ],
    scopeOfWork: [
      "Battery Chemistry Selection",
      "Balancing Circuit Design",
      "PCB Layout Design",
      "Thermal Management",
      "Testing and Validation",
    ],
  },
  {
    id: "sensor-interface-board",
    title: "Sensor Interface Board",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "Multi-sensor conditioning board",
      "Analog signal processing",
      "Digital sensor interfaces",
      "I2C and SPI protocols",
      "Low-power design",
      "Integrated filtering",
    ],
    summary:
      "Sensor interface board providing analog and digital signal conditioning for multiple sensor types with integrated filtering and protocol conversion.",
    importantParts: [
      "Instrumentation amplifiers",
      "Analog-to-digital converters",
      "Digital-to-analog converters",
      "I2C/SPI interface ICs",
      "Filter networks",
      "ESD protection diodes",
    ],
    salientFeatures: [
      "Support for multiple sensor types.",
      "Integrated analog and digital processing.",
      "Low-power operation modes.",
      "Protocol conversion capability.",
    ],
    scopeOfWork: [
      "Sensor Selection and Integration",
      "Signal Conditioning Design",
      "PCB Layout Design",
      "Calibration and Testing",
      "Firmware Integration",
    ],
  },
  {
    id: "motor-control-pcb",
    title: "Motor Control PCB",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "Three-phase motor control board",
      "PWM drive circuitry",
      "Current sensing and feedback",
      "Temperature monitoring",
      "Safety shutdown circuits",
      "High-current power stages",
    ],
    summary:
      "Motor control PCB featuring three-phase PWM drive circuitry, current feedback, and comprehensive safety protection for industrial motor control.",
    importantParts: [
      "Power MOSFET or IGBT modules",
      "Gate drive circuitry",
      "Current sensing resistors",
      "Temperature sensors",
      "Flyback protection diodes",
      "High-current traces",
    ],
    salientFeatures: [
      "Three-phase motor support.",
      "Real-time current feedback.",
      "Temperature-based protection.",
      "Smooth PWM control capability.",
    ],
    scopeOfWork: [
      "Power Stage Design",
      "Gate Drive Circuit Design",
      "PCB Layout Design (High-current)",
      "Thermal Management",
      "Testing and Validation",
    ],
  },
  {
    id: "communication-module",
    title: "Communication Module",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "Multi-protocol communication board",
      "Ethernet, CAN, RS-485 support",
      "Isolation and filtering",
      "Industrial connector interface",
      "EMI/EMC hardening",
      "Compact module design",
    ],
    summary:
      "Communication module PCB providing multi-protocol connectivity with industrial hardening for factory floor and process control applications.",
    importantParts: [
      "Ethernet PHY and magnetics",
      "CAN transceiver",
      "RS-485 driver/receiver",
      "Isolation transformers",
      "EMI filters",
      "Industrial connectors",
    ],
    salientFeatures: [
      "Multi-protocol communication support.",
      "Industrial isolation and filtering.",
      "Compact modular form factor.",
      "EMI/EMC compliance design.",
    ],
    scopeOfWork: [
      "Protocol Selection and Integration",
      "Isolation and Filtering Design",
      "PCB Layout Design",
      "Connector Integration",
      "Testing and Validation",
    ],
  },
  {
    id: "audio-processing-board",
    title: "Audio Processing Board",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "Audio codec and DSP board",
      "Multi-channel input/output",
      "Digital signal processing",
      "Low-noise analog section",
      "Microphone amplification",
      "Speaker drive capability",
    ],
    summary:
      "Audio processing PCB featuring codec, DSP, and multi-channel analog I/O for professional audio and voice communication applications.",
    importantParts: [
      "Audio codec IC",
      "DSP processor",
      "Microphone preamplifier",
      "Speaker amplifier",
      "Audio filters",
      "Shielded audio connectors",
    ],
    salientFeatures: [
      "Multi-channel audio input/output.",
      "On-board digital signal processing.",
      "Low-noise analog design.",
      "Professional audio quality.",
    ],
    scopeOfWork: [
      "Audio Codec Integration",
      "DSP Algorithm Development",
      "Analog Audio Design",
      "PCB Layout Design (Low-noise)",
      "Testing and Validation",
    ],
  },
  {
    id: "lighting-control-pcb",
    title: "Lighting Control PCB",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "LED driver and dimming board",
      "PWM control circuitry",
      "Color temperature control",
      "Power factor correction",
      "Thermal management",
      "Communication interface",
    ],
    summary:
      "Lighting control PCB featuring LED driver, PWM dimming, and color temperature control for smart lighting and building automation systems.",
    importantParts: [
      "LED driver IC",
      "PWM dimmer circuits",
      "Power factor correction circuit",
      "RGB control circuits",
      "Thermal sensing",
      "Communication interface",
    ],
    salientFeatures: [
      "Multi-channel LED driver capability.",
      "PWM dimming control.",
      "RGB and white-tuning support.",
      "Power factor correction.",
    ],
    scopeOfWork: [
      "LED Driver Integration",
      "Dimming Circuit Design",
      "Color Control Implementation",
      "PCB Layout Design",
      "Testing and Validation",
    ],
  },
  {
    id: "fpga-development-board",
    title: "FPGA Development Board",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "FPGA carrier and development platform",
      "FPGA socket and support circuits",
      "Memory interface (DDR, Flash)",
      "I/O expansion connectors",
      "Power distribution design",
      "Debug and programming port",
    ],
    summary:
      "FPGA development board providing carrier platform with memory interface, I/O expansion, and comprehensive power management for FPGA prototyping.",
    importantParts: [
      "FPGA socket and retention",
      "DDR3 memory interface",
      "NAND Flash storage",
      "I/O expansion connectors",
      "Power management circuits",
      "JTAG programming interface",
    ],
    salientFeatures: [
      "Full FPGA socket support.",
      "High-speed DDR3 memory interface.",
      "Multiple I/O expansion options.",
      "Professional development platform.",
    ],
    scopeOfWork: [
      "FPGA Integration Planning",
      "Memory Interface Design",
      "Power Distribution Design",
      "PCB Layout Design",
      "Testing and Validation",
    ],
  },
  {
    id: "thermal-management-pcb",
    title: "Thermal Management PCB",
    category: "PCB Design",
    images: ["/case-studies/image_vacationing.png"],
    features: [
      "Thermal control and monitoring board",
      "Temperature sensor interface",
      "Fan control circuits",
      "Heat dissipation optimization",
      "Redundant cooling paths",
      "Remote monitoring capability",
    ],
    summary:
      "Thermal management PCB featuring temperature monitoring, fan control, and heat dissipation optimization for high-power computing and industrial applications.",
    importantParts: [
      "Temperature sensor circuits",
      "PWM fan control drivers",
      "Thermal interface materials",
      "Heat pipe integration",
      "Remote monitoring interface",
      "Thermal de-rating circuits",
    ],
    salientFeatures: [
      "Multi-point temperature monitoring.",
      "Intelligent fan control algorithms.",
      "Optimized heat dissipation paths.",
      "Redundant cooling capability.",
    ],
    scopeOfWork: [
      "Thermal Analysis",
      "Temperature Sensor Integration",
      "Fan Control Design",
      "PCB Layout Design (Thermal)",
      "Testing and Validation",
    ],
  },
];
