import { CaseStudy } from "../../../../types/case-study";
import { CaseStudyCard } from "@/components/case-study-card";

// This would typically come from a database or API
const caseStudiesData: CaseStudy[] = [
  {
    id: "Security-System-Controller",
    title: "Security System Controller",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Embedded-System-with-RTOS/Security-Controller-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Embedded-System-with-RTOS/Security-Controller-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Embedded-System-with-RTOS/Security-Controller-c.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Embedded-System-with-RTOS/Security-Controller-d.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Embedded-System-with-RTOS/Security-Controller-e.jpg",
    ],
    features: [
      "Hardware / Firmware design and Development",
      "Mechanical /Enclosure Design / DFM",
      "IMx6 CPU / STM32",
      "Linux / RTOS",
      "High Density Digital",
      "FCC Class B certified",
    ],
    summary:
      "It is a powerful Edge controller device used in high security applications with multi-protocol sensors and reader inputs. The system is powered through POE+ and has options for power backup using an external power supply or battery. It can work as a stand alone device or can be cascaded to control multiple access points.",
    importantParts: [
      "Freescale iMX6 Application Processor",
      "ST Micro High Performance MCU",
      "Lattice Programmable Logic Device",
      "Linear Technologies POE+ Controller",
    ],
    salientFeatures: [
      "POE+ powered edge controller.",
      "Multiple dedicated Processors.",
      "Hardware encrypted communication.",
      "Scalable from one to networked multi-unit configuration.",
      "OSDP and Weigand Protocol for connection to card readers.",
      "Auxiliary input and output.",
      "Wet or Dry Relay setting.",
      "Remote Firmware Upgrade",
      "Built-in Inrush and overvoltage protection.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Board Bring-up and testing",
      "ID / Enclosure Design",
    ],
  },
  {
    id: "fpga-based-health-monitoring-system",
    title: "FPGA Based Health Monitoring System",
    category: "Medical Device Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/FPGA-Based-Structural-Health-Monitoring-System/SHM-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/FPGA-Based-Structural-Health-Monitoring-System/SHM-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/FPGA-Based-Structural-Health-Monitoring-System/SHM-c.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/FPGA-Based-Structural-Health-Monitoring-System/SHM-d.jpg",
    ],
    features: [
      "FPGA-based signal processing",
      "Real-time health monitoring",
      "Multi-sensor integration",
      "Wireless connectivity",
      "Low power consumption",
      "Medical grade certification",
    ],
    summary:
      "An advanced health monitoring system utilizing FPGA technology for real-time processing of multiple biosignals. The system integrates various sensors to monitor vital signs and provides wireless connectivity for remote monitoring. Designed with medical-grade standards for reliability and accuracy in clinical environments.",
    importantParts: [
      "Xilinx Zynq FPGA",
      "Analog Devices Precision ADCs",
      "Texas Instruments Power Management",
      "Nordic Semiconductor Wireless Module",
    ],
    salientFeatures: [
      "Real-time signal processing using FPGA.",
      "Multi-channel biosignal acquisition.",
      "Wireless data transmission.",
      "Low noise analog front-end.",
      "Battery-powered operation.",
      "Medical device compliance (FDA/CE).",
      "Secure data encryption.",
      "Remote monitoring capabilities.",
      "Alarm and alert system.",
    ],
    scopeOfWork: [
      "System Architecture Design",
      "FPGA Development and Programming",
      "Analog Circuit Design",
      "PCB Layout and Design",
      "Firmware Development",
      "Testing and Validation",
      "Regulatory Compliance",
    ],
  },
  {
    id: "Control-system-with-POE-Switch-and-RTOS",
    title: "Control System with POE Switch and RTOS",
    category: "Industrial Control Systems",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Control_system_with_POE_Switch_and_RTOS/Control_system_with_POE_Switch_and_RTOS-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Control_system_with_POE_Switch_and_RTOS/Control_system_with_POE_Switch_and_RTOS-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Control_system_with_POE_Switch_and_RTOS/Control_system_with_POE_Switch_and_RTOS-c.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Control_system_with_POE_Switch_and_RTOS/Control_system_with_POE_Switch_and_RTOS-d.jpg",
    ],
    features: [
      "Real-Time Operating System",
      "POE+ Switch Integration",
      "Industrial Grade Components",
      "Ethernet Communication",
      "Modular Design Architecture",
      "Remote Management Capability",
    ],
    summary:
      "A comprehensive industrial control system featuring integrated POE+ switching capabilities and real-time operating system. The system provides centralized control for multiple devices while delivering power and data through a single ethernet connection. Designed for harsh industrial environments with robust communication protocols.",
    importantParts: [
      "ARM Cortex-A9 Processor",
      "Marvell POE+ Switch Controller",
      "Industrial Ethernet PHY",
      "Isolated Power Supplies",
    ],
    salientFeatures: [
      "Integrated POE+ switching (up to 24 ports).",
      "Real-time deterministic control.",
      "Industrial temperature range operation.",
      "Redundant power supply options.",
      "SNMP network management.",
      "Web-based configuration interface.",
      "Modbus and Ethernet/IP protocols.",
      "DIN rail mounting.",
      "LED status indicators.",
    ],
    scopeOfWork: [
      "System Requirements Analysis",
      "Hardware Architecture Design",
      "RTOS Implementation",
      "Network Stack Development",
      "Power Management Design",
      "EMC/EMI Compliance Testing",
      "Industrial Certification",
    ],
  },
  {
    id: "Lithium-Titanate-Power-Bank",
    title: "Lithium Titanate Power Bank",
    category: "Power Electronics Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Lithium-Titanate-Power-Bank/Lithium-Titanate-Power-Bank-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Lithium-Titanate-Power-Bank/Lithium-Titanate-Power-Bank-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Lithium-Titanate-Power-Bank/Lithium-Titanate-Power-Bank-c.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Lithium-Titanate-Power-Bank/Lithium-Titanate-Power-Bank-d.jpg",
    ],
    features: [
      "3000 mAh Power Bank",
      "High Current, Super Fast Charging (under 10 Mins)",
      "Inbuilt Safety Features",
      "OLED Display",
      "Firmware Development",
      "Enclosure Design",
    ],
    summary:
      "A power bank using a Lithium Titanate battery with super-fast charging characteristics. The design is based on a high power current source and monitoring system using a PIC Microcontroller. The lithium-titanate battery's unique anode structure allows for rapid recharging, achieving a full charge in less than 10 minutes. The power bank can also be charged conventionally via Micro USB and includes built-in safety features to prevent overcharging and deep discharge.",
    importantParts: [
      "Analog Devices High power current source",
      "Microchip 8 bit Microcontroller",
      "Electronics Assembly OLED display 96 x 16 dots",
      "Richtek Boost regulator",
      "Texas Instruments 10-A Fully-Integrated Synchronous Boost Converter",
      "Texas Instrument Current Sense Amplifier",
      "Texas Instrument Buck Switching Regulator",
    ],
    salientFeatures: [
      "High Current, Super-Fast charging",
      "Inherently safe Design",
      "3000 mAh Capacity",
      "Normal and Fast charge Modes",
      "OLED for Status display",
    ],
    scopeOfWork: [
      "Hardware Design",
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "Board Bring-up and testing",
      "Enclosure Design",
    ],
  },
  {
    id: "OBD-2-Device-with-LoRa-and-BLE",
    title: "Automotive OBD Device with LoRa and BLE",
    category: "Automotive Electronics",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/OBD2-Device-with-LoRa-and-BLE/OBD-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/OBD2-Device-with-LoRa-and-BLE/OBD-b.jpg",
    ],
    features: [
      "Complete product development",
      "HW / FW / Linux System Integration",
      "Charging and Firmware upgrade of Custom OBD2 Devices",
      "Mechanical / Enclosure Design",
      "Contract Manufacturing",
    ],
    summary:
      "Developed for an automotive solutions company, this device reads car data via the OBD port, transmitting it to a central server using LoRa for on-premises communication and indoor location tracking. It features an STM32F Microcontroller, supports multiple OBD protocols (ISO, J1850, CAN), and includes two BLE radios for device communication and beaconing. A key feature is its pass-through design, allowing other OBD devices to be used simultaneously. The handheld, battery-operated device has an 800 mAh Li-Po battery, chargeable from the OBD port, with a cut-off mechanism to prevent draining the car battery. It also includes an accelerometer to detect car status, a special connector for a Smart OBD charging station for diagnostics and firmware updates, and an integrated LED torch for locating the OBD port in low light.",
    importantParts: [
      "ST Microelectronics ARMCortex-M0 32-bit RISC MCU.",
      "OBDSOL OBD Translator.",
      "MultiTech LoRa Module.",
      "Raytac BLE Module.",
      "ST Microelectronics Accelerometer.",
      "Atmel EEPROM.",
      "Texas Instruments Li-Po Charger.",
    ],
    salientFeatures: [
      "Rugged Automotive Product.",
      "Multi Radio Design - LoRa, BLE, BLE Beacon.",
      "Automotive grade ESD/ EMI / Voltage spike protection.",
      "Multiprotocol OBD communication.",
      "Integrated LED torchlight.",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "Board Bring-up and testing",
      "Enclosure Design.",
      "Coordination with Mold manufacturer",
      "FCC / CE certification",
      "Packing Box Design",
      "Low volume production",
    ],
  },
  {
    id: "BLE-tag-with-Wireless-Charging",
    title: "Low Power BLE Tag with Wireless Charging",
    category: "IoT Devices",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/BLE-tag-with-Wireless-Charging/BLE-Tag-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/BLE-tag-with-Wireless-Charging/BLE-Tag-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/BLE-tag-with-Wireless-Charging/BLE-Tag-c.jpg",
    ],
    features: [
      "Low power BLE Tag - NRF52 Chipset",
      "AirFuel RF wireless Charging",
      "Multiple sensors - Light, Motion, temperature, SoS Switch, etc",
      "Hardware / Firmware Development",
      "ID / Mechanical Design",
    ],
    summary:
      "This project combines a Low power BLE tag and WattUp wireless charging technology. The device has a press button switch and multiple sensors on board. It can be programmed to send a message when either a switch press or any sensor event is triggered. The wireless charging capability is provided by proprietary WattUp wireless charging technology. It allows for contact-less orientation-free charging of the tags. The device is super low power consuming and will run for upto a month on a single charge. They can be recharged easily by dropping them on a charging pad. The devices are BLE 5.0 compliant and can be used to form BLE mesh networks. They can be used as Indoor location sensing beacons, Indoor Asset tracking, SOS buttons, Etc.",
    importantParts: [
      "Nordic Semi BLE 5.0 Chipset",
      "Dialog WattUp Wireless Charging SOC",
      "ST Micro Accelerometer, Gyro, Magnetometer, Temperature Sensor",
      "Lite-on Ambient Light Photo Sensor",
      "Texas Instruments LiPo battery charger",
      "ST Micro LDO Voltage regulator",
    ],
    salientFeatures: [
      "BLE 5.0 Device",
      "Ultra-Low power tag.",
      "WattUp RF wireless Charging Technology",
      "Multiple sensors - Light, Motion, temperature, etc",
      "Push Button",
      "Meshing capability",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "Enclosure Design",
      "Board Bring-up and testing",
    ],
  },
  {
    id: "IOT-Module-with-Wi-Fi-BLE-ZigBee",
    title: "Connectivity Module based on Qualcomm QCA4020",
    category: "IoT Devices",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Module-with-Wi-Fi_BLE_ZigBee/IOT-Module-with-Wi-Fi_BLE_ZigBee-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Module-with-Wi-Fi_BLE_ZigBee/IOT-Module-with-Wi-Fi_BLE_ZigBee-b.jpg",
    ],
    features: [
      "Qualcomm QCA4020 Chipset",
      "Dual Wi-Fi / BLE 5.0 / ZigBee / Thread",
      "Hardware Design",
      "PCB Design",
      "Firmware Development",
      "RF Calibration",
    ],
    summary:
      "It is a connectivity module based on the Qualcomm QCA 4020 Wireless SoC. The QCA4020 is a Qualcomm solution for the IOT domain. It has dual band Wi-Fi, BLE 5.0 and ZigBee radios all in one SoC. The module can be used in a multitude of IOT applications. The device can act as a Gateway between the internet and other IOT devices with BLE or ZigBee connectivity. The QCA4020 is a low power SOC that integrates a Cortex M4F for application processing, Cortex M0 for network stack processing, and a separate processor for Wi-Fi. It has hardware level encryption and Co-Existence capability for Wi-Fi and BLE radios. The Module can be used in a range of applications like Smart Home, Networking, Entertainment and Smart Cities.",
    importantParts: [
      "Qualcomm Wi-Fi, BLE, ZigBee, Thread",
      "Skyworks Wi-Fi Front End Module",
      "Skyworks RF Amplifier",
      "Macronix 16Mb NOR Flash Memory",
    ],
    salientFeatures: [
      "Dual Band Wi-Fi, BLE 5.0, ZigBee, Thread.",
      "Meshing Capability",
      "Multiple I/O pins",
      "Compact Design: 39mm x 28mm x 4mm",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "RF Calibration and Tuning",
      "Board Bring-up and testing",
    ],
  },
  {
    id: "IOT-micro-gateway",
    title: "IOT Micro Gateway",
    category: "IoT Devices",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Micro-Gateway/IOT-Micro-Gateway-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Micro-Gateway/IOT-Micro-Gateway-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Micro-Gateway/IOT-Micro-Gateway-c.jpg",
    ],
    features: [
      "Qualcomm QCA4020 Chipset",
      "Dual Band Wi-Fi, Bluetooth 5.0, ZigBee",
      "Hardware / Firmware / RF Development",
      "Power Supply Design",
      "Enclosure design / ID",
      "Compact Design: 42mm x 36mm x 27mm",
    ],
    summary:
      "This device is an IOT Micro Gateway powered by Qualcomm QCA 4020 chipset. It has Wi-Fi, Bluetooth 5.0 and ZigBee. It will bridge IOT devices through BLE or ZigBee and the Internet, through Wi-Fi. It has an in-built power supply and comes in a sleek form factor which can be plugged into any wall outlet just like a mobile phone charger. The device can handle multiple wireless devices at a time while being connected through Wi-Fi as well. It finds numerous applications in both consumer and industrial settings.",
    importantParts: [
      "Qualcomm Wi-Fi, BLE, ZigBee, Thread",
      "Skyworks Wi-Fi Front End Module",
      "Skyworks RF Amplifier",
      "Macronix NOR Flash Memory",
      "CUI Power Supply Module",
    ],
    salientFeatures: [
      "Dual Band Wi-Fi, BLE 5.0, ZigBee, Thread.",
      "Inbuilt power supply",
      "Meshing Capability",
      "Compact Design: 42mm x 36mm x 27mm",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "RF Calibration and Tuning",
      "Enclosure Design",
      "Board Bring-up and testing",
    ],
  },
  {
    id: "kneeling_system",
    title: "Kneeling and Levelling System",
    category: "Embedded System Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-Kneeling-and-Levelling-System/Kneeling-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-Kneeling-and-Levelling-System/Kneeling-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-Kneeling-and-Levelling-System/Kneeling-c.jpg",
    ],
    features: [
      "Complete product development",
      "NPI Contract manufacturing",
      "Test jigs / Test plans comprehensive documentation",
      "Volume Production",
      "Encapsulated in Epoxy",
      "ARAI ( Automotive standards) certified",
      "FCC / Vibration / Temp Tested",
      "Tier 1 Automotive client",
    ],
    summary:
      "This project was designed and executed by Qmax for a Tier 1 Indian Automotive customer. The requirement was to design a kneeling and levelling system for heavy vehicles. Heavy duty vehicles like Trailers and Buses Use Pneumatic suspensions otherwise called as air springs. They are reinforced rubber bellows which are inflated and works as suspension. They are inflated or deflated according to the height required and when passengers get in or alight. The air suspension must be precisely controlled for a smooth ride. Qmax was assigned to develop a control system for the kneeling and levelling system. The system takes in parameters and commands from the Vehicles CAN control bus and executes them to control the suspension. The system must be fast, responsive and rugged.The device is built around a Microchip 18F45K80 high performance, automotive grade, 8-bit MCU with integrated ECAN Feature. The MCU boasts low power consumption and high precision. The project involved Potting of the PCBA inside the enclosure. All the thermal and physical stresses involved has been considered during the design. Qmax did the initial prototyping and pilot production run of around 2000 Units.",
    importantParts: [
      "Microchip High performance, automotive grade, 8-bit MCU",
      "Microchip High-Speed CAN Transceiver",
      "NXP ESD Protection IC",
      "ST Micro Switching Voltage Regulator",
    ],
    salientFeatures: [
      "Automotive grade product",
      "Rugged construction",
      "CAN protocol communication",
      "Ultra-fast response",
      "IP69K compliant inside enclosure",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "Board Bring-up and testing",
      "Manufacturing Coordination",
    ],
  },
  {
    id: "Precision-Filtration-Control-System",
    title: "Precision Filtration Control System",
    category: "Industrial Automation",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Precision-Filtration-control-System/Precision-Filtration-control-System-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Precision-Filtration-control-System/Precision-Filtration-control-System-b.jpg",
    ],
    features: [
      "Industrial Automation project",
      "Complete design and development",
      "Sensor inputs, I/O and Pump controls",
      "Mixed Signal / High Current",
    ],
    summary:
      "The precision pump control system was designed for a filtration products company. It is used for controlling a filtration unit with high accuracy and precision. The filtration unit consists of pumps and multiple sensors. Temperature and pressure and flow sensors are used to detect the condition of the fluid. The controller uses an Arm Cortex A53 to control the entire system. The device takes multiple sensor inputs and actuates solenoid valves and pumps based on embedded control logic. The inputs are all provided with ESD protection. The output lines are protected against Inrush and voltage spikes.",
    importantParts: [
      "Arm Cortex A53 SBC",
      "Texas Instruments Precision Sensor Interface",
      "Texas Instruments 4 Port USB 2.0 Hub",
      "Texas Instruments Bi-Directional Voltage Level Translator",
      "Texas Instruments PWM High Side Driver",
      "Texas instruments Precision Power Switch",
      "Texas Instruments Dual Op-Amp",
      "Texas Instruments Step Down Converter",
    ],
    salientFeatures: [
      "Industrial Grade Design",
      "ESD and EMI Protection",
      "Mixed Signal Board",
      "Multiple Sensors inputs",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "Board Bring-up and testing",
    ],
  },
  {
    id: "polyphase-power_measurement",
    title: "Polyphase Power Measurement System",
    category: "Power Electronics Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Polyphase-Power-Measurement-System/Polyphase-Power-Measurement-System-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Polyphase-Power-Measurement-System/Polyphase-Power-Measurement-System-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Polyphase-Power-Measurement-System/Polyphase-Power-Measurement-System-c.jpg",
    ],
    features: [
      "Polyphase Power measurement system",
      "Texas Instruments MSP430F6779 SOC",
      "Hardware Design",
      "Firmware Development",
      "PCB Design",
    ],
    summary:
      "The power measurement system is designed based on a MSP430F6779 Polyphase Phase Metering SOC. It is used to measure the energy flowing in different branches of a power supply network. The PCBA is designed to fit inside a Distribution box besides a Miniature Circuit breaker. Voltage samples are fed to the board through a Potential transformer and voltage divider arrangement. Current samples are fed through a current transformer. The MSP430 MCU applies a digital signal processing algorithm to compute power and other parameters.",
    importantParts: [
      "Texas Instruments Polyphase Phase metering SOC",
      "Quad, 3MHz, Low-Power, Low-Noise, RRI/O, 1.8V CMOS Op-Amp",
      "MOSFET Array",
      "Low-Voltage 27V PMOS-NMOS Bridge Driver",
      "CR Magnetics Current Transformer",
    ],
    salientFeatures: [
      "In-situ measurement of Electrical Parameters",
      "Highly Accurate and precise",
      "Specially designed PCB to fit Distribution box",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "Board Bring-up and testing",
    ],
  },
  {
    id: "IOT-connectivity-dongle-BLE-ZIGBEE",
    title: "USB Dongle for IOT Applications",
    category: "IoT Devices",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Dongle-BLE_ZigBee/BLE-Dongle-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Dongle-BLE_ZigBee/BLE-Dongle-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Dongle-BLE_ZigBee/BLE-Dongle-c.jpg",
    ],
    features: [
      "Qualcomm QCA4024 Chipset",
      "Complete product development",
      "Hardware, Firmware, Mechanical design",
      "RF design and optimisation",
      "BLE 5.0 / Zigbee / Thread",
    ],
    summary:
      "The device in the picture is a USB dongle for IOT Applications. It is based on the Qualcomm QCA 4024 SoC having BLE 5.0, ZigBee and Thread. It can be used to add BLE or Zigbee capability to any device just by plugging it in to a USB port. The device has serial port communication capability through the USB 3.0 interface and can be easily included to existing hardware for a wide variety of applications. The QCA 4024 comes with Meshing capability for both BLE and ZigBee. This can be very useful in applications like Home Automation or Sensor mesh network. A co-existence mechanism available on the Dongle allows both BLE and ZigBee to work simultaneously. The QCA 4024 chipset comes with SDK that is available for different profiles. Custom firmware can be easily made to suit Unique customer requirements.",
    importantParts: [
      "Qualcomm BLE, ZigBee, Thread",
      "Skyworks Power Amplifier",
      "FTDI USB to Serial converter",
      "Walsin SP3T RF switch",
      "Macronix 64 Mb NOR Flash Memory",
      "Richtek Buck Regulator",
      "Texas Instruments LDO Voltage Regulator",
    ],
    salientFeatures: [
      "BLE 5.0, ZigBee, Thread.",
      "Meshing Capability",
      "Multiple I/O pins",
      "Serial Communication",
      "USB3.0",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "RF Calibration and Tuning",
      "Enclosure Design / Industrial Design",
      "Board Bring-up and testing",
      "Low Volume Manufacturing",
    ],
  },
  {
    id: "IOT-Power-Measurement-Unit",
    title: "Power Measurement Unit",
    category: "Power Electronics Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Power-Measurement-Unit-with-USB/Power-Measurement-Unit-with-USB-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Power-Measurement-Unit-with-USB/Power-Measurement-Unit-with-USB-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Power-Measurement-Unit-with-USB/Power-Measurement-Unit-with-USB-c.jpg",
    ],
    features: [
      "Complete product development",
      "Texas Instruments MSP 430 Based Design",
      "AC voltage / Current / Power / Energy / PF Measurement",
      "HW / FW / Mechanical Design",
      "UL60950 Compliant",
    ],
    summary:
      "The Power Measurement Unit isused to monitor power consumption of the device connected to it. It will be connected between the device and wall outlet. It communicates with a Host through a USB connection.The measured parameters are sent to the Host for further processing. The data can be sent to the Cloud for storage and analytics. This data can be remotely viewed on an Android application or Web based Dashboard. The heart of the system is a Texas Instruments MSP430AFE253, a 16-bit Ultra-Low-Power RISC Microcontroller. It has 24-bit sigma-delta ADCs which enables precise measurement of the power. The device can measure root mean square voltage, root mean square current, active power, reactive power, apparent power, power factor, AC frequency.The acquired data is transferred through the USB port by a UART to USB Converter.",
    importantParts: [
      "Texas Instruments 16 Bit RISC MCU",
      "FTDI Full Speed USB to UART converter",
      "Everlight 4 Pin DIP Phototransistor Photocoupler",
      "CUI DC to DC Converter",
    ],
    salientFeatures: [
      "In-situ measurement of Electrical Parameters",
      "Isolated UART Communication",
      "Low-Cost Design",
      "Highly Accurate and precise",
      "Modular Stackable Design",
      "Specially designed PCB to fit in19 Inch Racks",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "Board Bring-up and testing",
    ],
  },
  {
    id: "iot-gateway",
    title: "IOT Gateway",
    category: "IoT Devices",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Gateway/IOT-Gateway-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Gateway/IOT-Gateway-b.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Gateway/IOT-Gateway-c.jpg",
    ],
    features: [
      "Qualcomm QCA4531 + QCA4024",
      "WiFi, BLE 5.0, Zigbee, SIG Mesh",
      "Firmware and Hardware Development",
      "Enclosure Design",
    ],
    summary:
      "The IOT gateway designed by Qmax is based on the Qualcomm QCA4531 + QCA 4024 chipsets. It has Wi-Fi, BLE 5.0, ZigBee and Thread. It connects to Internet using Wi-Fi or Ethernet. The gateway connects to other devices through BLE or ZigBee. This way, the Gateway acts as a bridge between the IOT devices on side and the Internet on the other.The QCA4531 has inbuilt Ethernet and PCIe features. We can add other functionality to the gateway through the PCIe slot available on board. The device is powered by an external Power Adapter. The QCA4531 is a low-cost turnkey solution that brings high-performance connectivity capabilities in a user programmable Linux/ OpenWRT environment. OpenWRT offers a built-in package manager that allows packages to be installed directly from a software repository, greatly simplifying development. Benefiting from the extended range based on 2x2 11n, it is designed to serve as a feature-rich IoE node and as a hub to bridge between multiple protocols and ecosystems. The QCA4531 can function as an Access Point supporting up to 16 simultaneous devices and is also power-optimized to enable appliances to meet international standards for energy efficiency. It supports the AllJoyn connectivity software framework and services, allowing devices to discover, connect and communicate directly with one another. The QCA4024 SoC is a multi-mode system-on-chip with support for Bluetooth 5 and 802.15.4-based technologies, including Zigbee and Thread. This low power SOC integrates a Cortex M4F for application processing and a Cortex M0 for network stack processing designed to enable a highly concurrent multiple radio solution. The QCA4020 SDK from Qualcomm Technologies pre-integrates support for advanced security features and mesh networking. This solution complements portions of the portfolio beyond IoT devices to address multiple industries.",
    importantParts: [
      "Qualcomm Wi-Fi SoC",
      "Qualcomm BLE, ZigBee, Thread",
      "Skyworks Wi-Fi Front End Module",
      "Skyworks RF Amplifier",
      "Macronix NOR Flash Memory",
      "FTDI USB to Serial converter",
      "Walsin SP3T RF switch",
      "Macronix 64 Mb NOR Flash Memory",
      "Winbond 512 MB DDR2 RAM",
    ],
    salientFeatures: [
      "Dual Band Wi-Fi, BLE 5.0, ZigBee, Thread.",
      "PCIe add-on Slot",
      "Ethernet",
      "USB",
      "DC Jack",
      "LED indications",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "RF Calibration and Tuning",
      "Enclosure Design",
      "Board Bring-up and testing",
    ],
  },
  {
    id: "Wearable-Biosensor",
    title: "Sports Wearable with Biosensor",
    category: "IoT Devices",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Wearable-biosensor/Wearable-biosensor.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Wearable-biosensor/Wearable-biosensor-b.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Wearable-biosensor/Wearable-biosensor-c.png",
    ],
    features: [
      "Sports wearable based on Qualcomm QCA4024",
      "Complete product development",
      "Hardware, Firmware development, RF Calibration",
      "BLE 5.0 / Zigbee / Thread",
      "BLE Mesh",
    ],
    summary:
      "The device is a wearable biosensor that can detect six critical health readings. It is based on the Qualcomm QCA 4024 SoC having BLE 5.0, ZigBee and Thread. The biosensor used is Mediatek Sensio MT6381. Having the form factor of a Watch, It takes readings from the wrists to track heart rate information, blood pressure trends, peripheral oxygen saturation levels and more, all in nearly 60 seconds. The device is intended to be used by sportspersons for active tracking and performance improvement planning. It can be used in training for Team Sports like football to assess the conditions of all the players and make strategic decisions. The wearables on all the players can mesh together and form a local network. Data is transmitted over the BLE5.0 or ZigBee mesh network to the Master receiver.",
    importantParts: [
      "Qualcomm BLE, ZigBee, Thread",
      "Mediatek Biosensor",
      "Skyworks Power Amplifier",
      "FTDI USB to Serial converter",
      "Walsin SP3T RF switch",
      "Macronix 64 Mb NOR Flash Memory",
      "Richtek Buck Regulator",
      "Texas Instruments LDO Voltage Regulator",
    ],
    salientFeatures: [
      "6-in-1 Biosensor Readings",
      "BLE 5.0, ZigBee, Thread Connectivity",
      "BLE Mesh Networking",
      "Watch Form Factor",
      "Fast 60-second readings",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "RF Calibration and Tuning",
      "Board Bring-up and testing",
    ],
  },
  {
    id: "Smart-OBD-Charging-Station",
    title: "Smart OBD Charging Station",
    category: "Automotive Electronics",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Smart-OBD-Charging-Station/Smart-OBD-Charging-Station-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Smart-OBD-Charging-Station/Smart-OBD-Charging-Station-b.png",
    ],
    features: [
      "Complete product development",
      "HW / FW / Linux System Integration",
      "Charging and Firmware upgrade of Custom OBD2 Devices",
      "Mechanical / Enclosure Design",
      "Contract Manufacturing",
    ],
    summary:
      "This device was developed for an Automotive solutions company. Qmax has design and developed an OBD 2 device with LoRa and BLE device for the same customer. You can find the project in our portfolio. That device is portable and has a LiPo battery. It also required firmware update from time to time. Qmax proposed the development of this Smart OBD charging station for charging the OBD device while firmware upgrade is done simultaneously. The major challenge was designing an interface to access the microcontroller inside the OBD device. Qmax designed special OBD connectors and mating plugs to fulfill this requirement. The system runs on a 64-bit ARM Cortex A53 processor running a custom Linux application. The smart charging station can house upto 15 OBD devices at a time. The power to charge the Batteries is delivered by a specially designed power supply. The Linux system monitors and controls the power to each of the 15 OBD devices. The device is connected to the Cloud engine through Wi-fi or Ethernet. It can connect to a local Smart phone using BLE for configuration or local status updates. The device checks for latest firmware update available on the cloud and compares it with each of the plugged in OBD device. It upgrades the firmware automatically in the ones that has older firmware. The system has built in fail-safe mechanism to prevent device memory corruption or device failure in case the OBD device is plugged out in the middle of a firmware upgrade or charging session. Qmax did the complete mechanical design of this product. We have designed a custom enclosure and mounting mechanism. The PCB is long and must be adequately supported to prevent damage during usage. Apart from the initial prototypes, we have supported the customer for the trial production run.",
    importantParts: [
      "ARM Cortex A53 processor",
      "Semtech I/O Expander",
      "Silicon Labs USB to UART converter",
      "Texas Instruments 7 Port Full Speed USB Hub",
      "Texas Instruments Step down DC-DC Converter",
      "Richtek Step down DC-DC Converter",
    ],
    salientFeatures: [
      "Rugged Industrial Product.",
      "Anodized Aluminium enclosure",
      "Spring loaded contacts for Firmware upgrade",
      "Wi-Fi, Ethernet, USB",
    ],
    scopeOfWork: [
      "Schematics Entry",
      "PCB Layout Design",
      "PCB Fabrication and Assembly",
      "Firmware development",
      "Board Bring-up and testing",
      "Enclosure Design.",
      "Low volume production",
    ],
  },
  {
    id: "Industrial-Controller",
    title: "Industrial Controller",
    category: "Robotics",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Industrial-Controller/Industrial-Control-a.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Industrial-Controller/Industrial-Control-b.jpg",
    ],
    features: [
      "Robotics Controller Board",
      "6 Layer PCB",
      "Interfaces: PCIE, HDMI, USB3.0, USB2.0, SPI, I2C",
      "Total pin count: 3089",
      "Packages Used: QFN 64, LQFP 144",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Aerospace-PCB",
    title: "Aerospace PCB",
    category: "Robotics",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Aerospace-PCB/Aerospace-a.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Aerospace-PCB/Aerospace-b.jpg",
    ],
    features: [
      "Aerospace Board",
      "Interfaces: LVDS, SPI, I2C",
      "8 Layer PCB",
      "High Density",
      "Total pin count: 2312",
      "Packages Used: 135 Pin BGAs",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Automotive-OBD",
    title: "Automotive OBD PCB",
    category: "Automotive Electronics",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-OBD/Automotive-OBD.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-OBD/Automotive-OBD-A.jpg",
    ],
    features: [
      "Automotive OBD PCB",
      "Interfaces: UART, I2C, SPI",
      "4 Layer PCB",
      "Total pin count: 997",
      "Packages Used: LQFP 64",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Security-Controller",
    title: "Security Controller",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Security-Controller/Security-Controller.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Security-Controller/Security-Controller.png",
    ],
    features: [
      "Chipset: IMx6 CPU / PoE / Hi Density",
      "PCB Design / Fabrication / Assembly",
      "EMI Testing, DFx Analysis",
      "Thermal Analysis / SI Analysis",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Automotive-HID-PCB",
    title: "Automotive HID PCB",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-HID-PCB/Automotive-HID-PCB.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-HID-PCB/Automotive-HID-PCB-a.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-HID-PCB/Automotive-HID-PCB-b.png",
    ],
    features: [
      "Atmel MCU / Hi Density",
      "EMI/ESD Protection",
      "8 Layer PCB, Blind/Buried Vias",
      "PCB Design / Fabrication / Assembly",
      "EMI Testing, DFx Analysis",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Networking-Device",
    title: "Networking Device",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Networking-Switch/Networking-Switch.png",
    ],
    features: [
      "High Speed Networking Board",
      "10 Gbps / DDR3",
      "28 layers / 1300 Pins BGAs",
      "High Current / Ultrahigh density",
      "Total Pin Count: 18000 pins",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Networking-Switch",
    title: "Networking Switch",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Networking-Device/Networking-Device.png",
    ],
    features: [
      "Networking-Device",
      "Router Line card - Networking Board",
      "Interfaces: 40 port 10GBs High speed and QDR",
      "20 Layer PCB",
      "Ultra High-Density PCB",
      "Total pin count: 33312",
      "Packages Used: 1365 Pins BGA",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Blade-NIC-Server",
    title: "Blade NIC Server",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Blade-NIC-Server/Blade-NIC-Server-a.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Blade-NIC-Server/Blade-NIC-Server-b.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Blade-NIC-Server/Blade-NIC-Server-c.png",
    ],
    features: [
      "Blade-NIC-Server",
      "High density",
      "Blade server Application",
      "14 layers",
      "High Speed 10 Gbps Ethernet",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "ATE-PCB",
    title: "ATE PCB",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/ATE-PCB/ATE-a.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/ATE-PCB/ATE-b.png",
    ],
    features: [
      "ATE-PCB",
      "ATE Test Board",
      "18 Layer PCB",
      "Total pin count: 2826",
      "High Density PCB",
      "Packages Used: 484 Pins BGA",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "IOT-Gateway",
    title: "IOT Gateway",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Gateway/IOT%20Gateway%20(1).png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Gateway/IOT-Gateway-a.jpg",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/IOT-Gateway/IOT-Gateway-b.jpg",
    ],
    features: [
      "IOT-Gateway",
      "4 Layer PCB",
      "Layout optimized for RF sections",
      "High Density PCB",
      "Total pin count: 1952",
      "Packages Used: 156Pins QFN, 84 pin BGA",
      "Interfaces: DDR3, PCIe, RJ45, USB, UART, I2C",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Automotive-Control",
    title: "Automotive Control",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-control/Automotive-Control.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-control/Automotive-Control-a.png",
    ],
    features: [
      "Atmel MCU/ Multiple Interconnects",
      "PCB Design / Fabrication / Assembly",
      "Low EMI design",
      "8 Layer PCB, Blind/Buried Vias",
      "Surge / ESD protection",
      "EMI Testing, DFx Analysis",
      "Thermal Analysis / SI Analysis",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Automotive-Keypad-Interface",
    title: "Automotive Keypad Interface",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-Keypad-Interface/Automotive-Keypad-Interface-a.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-Keypad-Interface/Automotive-Keypad-Interface-b.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Automotive-Keypad-Interface/Automotive-Keypad-Interface-c.png",
    ],
    features: [
      "Automotive Grade PCBA",
      "EMI and ESD Protection",
      "6 Layer PCB, Blind/Buried Vias",
      "PCB Design / Fabrication / Assembly",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Medical-Electronics",
    title: "Medical Electronics",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Medical-PCB/Medical-a.png",
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Medical-PCB/Medical-b.jpg",
    ],
    features: [
      "Medical Electronics Board",
      "2 Layer PCB",
      "High Density PCB",
      "Packages Used: 14Pins BGA 0.5mm pitch",
      "Interfaces: UART, I2C",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Video-Processor",
    title: "Video Processor",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/Video-Processor/Video-Processor.png",
    ],
    features: [
      "Video Processing Hardware",
      "High speed digital / PCIE / DDR3",
      "Cadence Allegro",
      "High Current",
      "Total pin count : 16533",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Set-Top-Box",
    title: "Set Top Box",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/STB-PCB/STB-a.png",
    ],
    features: [
      "Set Top Box",
      "4 layers",
      "High speed Digital / Analog",
      "Medium density / High volume product",
      "Consumer Electronics",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  {
    id: "Wi-Fi-AP",
    title: "WiFi AP",
    category: "PCB Design",
    images: [
      "https://d1yetprhniwywz.cloudfront.net/case-studies-images/WiFi-AP/WiFi-AP.png",
    ],
    features: [
      "Low density, Consumer grade wireless AP",
      "Wireless LAN Application",
      "4 layer",
      "High Speed Digital, RF",
      "High Volume product",
    ],
    summary: "",
    importantParts: [],
    salientFeatures: [],
    scopeOfWork: [],
  },
  // Add more case studies here...
];

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const caseStudy = caseStudiesData.find((cs) => cs.id === slug);
  if (!caseStudy) {
    return {
      title: "Case Study Not Found",
    };
  }
  return {
    title: caseStudy.title,
  };
}

export default async function CaseStudyPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const caseStudy = caseStudiesData.find((cs) => cs.id === slug);

  if (!caseStudy) {
    return <div>Case Study Not Found</div>;
  }

  return (
    <div className="min-h-screen bg-white">
      <CaseStudyCard caseStudy={caseStudy} />
    </div>
  );
}

export async function generateStaticParams() {
  return caseStudiesData.map((caseStudy) => ({
    slug: caseStudy.id,
  }));
}
